### ISSUE TITLE
Getting exceptions because of missing centipede builds

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10143]
https://pantheon.corp.google.com/errors/detail/CJ-y55f4xPn2pgE;filter=%5B%22centipede%22%5D;time=P1D?project=clusterfuzz-external
https://pantheon.corp.google.com/errors/detail/COH5rbeRof_FhAE;filter=%5B%22centipede%22%5D;time=P1D?project=clusterfuzz-external
https://pantheon.corp.google.com/errors/detail/CJGl2d7ovuWAQw;filter=%5B%22centipede%22%5D;time=P1D?project=clusterfuzz-external

**Comment by jonathanmetzman** [comment]
I wonder if this will resolve itself after the builds happen for the first time.

**Comment by jonathanmetzman** [comment]
This has been resolved.

**Comment by jonathanmetzman** [comment]
Actually it hasn't.

**Comment by jonathanmetzman** [comment]
It's our top error now. https://pantheon.corp.google.com/errors/detail/CPbo9qXUrMvRBg;filter=%5B%5D;time=P1D?project=clusterfuzz-external
@Alan32Liu can you look into this?

**Comment by Alan32Liu** [comment]
Sure! I have some slides due today but will investigate it tmr.

**Comment by Alan32Liu** [comment]
[All occurrence](https://pantheon.corp.google.com/logs/query;query=centipede%0Aseverity%3E%3DNOTICE;timeRange=PT12H;cursorTimestamp=2023-04-27T05:54:43.840474865Z?project=clusterfuzz-external) of that error is caused by project `neomutt` with `none` sanitizer, due to [errors in getting the list of build urls](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2023-04-27T05:55:25.364096405Z;query=centipede%0Aseverity%3E%3DNOTICE%0Atimestamp%3D%222023-04-27T05:54:40.169371983Z%22%0AinsertId%3D%22px5p65mptabf28gcj%22;timeRange=PT12H?project=clusterfuzz-external).

This is because `gs://clusterfuzz-builds-centipede/neomutt/` only contains `address` sanitizer's `zip` files (and `srcmap.json`), nothing about `none`. Other projects seem normal.

OSS-Fuzz's [build log](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#neomutt) shows the project has had build failures for over a year, due to [a timeout in build-check with `none` sanitizer](https://oss-fuzz-build-logs.storage.googleapis.com/log-2a39351b-c1a9-44c8-8cce-de5275daa8c8.txt), which likely caused the error.
This `timeout` can be reproduced locally.

I can investigate further into this later.
