### ISSUE TITLE
Unexpected large amounts of corpora

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#1030]
Hi, just wanted to merge latest corpora and saw that some fuzzers have >167k files where they had just ~2k before. The project code didn't change and the coverage was pretty good before (with those ~2k corpora). After downloading all 167k files it turned out that the clang -merge=1 step resulted in just 1 (one) single new corpus (which makes ~350 in total).

It feels as if there is something wrong, please have a look into that.

Project: wget2
Downloads: gs://wget2-corpus.clusterfuzz-external.appspot.com/libFuzzer/wget2_libwget_atom_url_fuzzer/*

**Comment by oliverchang** [comment]
Will take a closer look next week, but the jump appears to have occurred around Nov 14/15. Did anything change around then?

**Comment by kcc** [comment]
Did we update libFuzzer around that time?

**Comment by kcc** [comment]
I was investigating another case of abnormal corpus growth and it looks like it's caused by the recent libFuzzer's stack depth instrumentation -- it's too aggressive and if the target has deep recursion it may lead to crazy corpus sizes over time. 

I've submitted a stop gap to make it less aggressive, will investigate further next week. 
http://llvm.org/viewvc/llvm-project?view=revision&revision=320237
@morehouse FYI

**Comment by kcc** [comment]
A better fix: http://llvm.org/viewvc/llvm-project?view=revision&revision=320259
@oliverchang please roll the new libFuzzer -- it is very likely going to fix this issue too.

**Comment by oliverchang** [comment]
Ok, rolling and trying a rebuild.

**Comment by oliverchang** [comment]
Thanks Kostya, I see that on https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-12-04/2017-12-10/fuzzer/libFuzzer_wget2_libwget_atom_url_fuzzer and https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-12-04/2017-12-10/fuzzer/libFuzzer_wget2_libwget_sitemap_url_fuzzer the corpus size is back to 500~ from 100k~

**Comment by rockdaboot** [comment]
Great, thank you !
