### ISSUE TITLE
CIFuzz action is fuzzing the wrong code for topic branch pushes (sibling of #3731)

### ISSUE THREAD

**Issue by hartwork** [google/oss-fuzz#10472]
Hi!

The CIFuzz GitHub Action came to my attention through pull request https://github.com/libexpat/libexpat/pull/677 (and also https://github.com/USBGuard/usbguard/pull/568) . If my understanding is correct, the action always builds the the latest commit on the default branch, e.g. for Expat …

https://github.com/google/oss-fuzz/blob/8d1f1306fda3464fb3a7ec8b4227308d315ed495/projects/expat/Dockerfile#L20

…, even when the CI run was triggered by a push to a topic branch or by new commits offered through a pull request, i.e. not the default branch.

My impression is that:

- this issue is not specific to Expat but structural to the GitHub Action, and that
- this makes the action fuzz the wrong code and as a result makes misleading statements about the code that was supposed to be under inspection.

I'd be happy to learn that this is a misunderstanding. What do you think?

Thanks and best, Sebastian

**Comment by oliverchang** [comment]
Hi! CIFuzz actually checks out the code at the relevant revision. The upstream Dockerfile says that we clone from the default branch, but there's an additional step to check out the correct revision. CC @jonathanmetzman

**Comment by hartwork** [comment]
@oliverchang @jonathanmetzman not so fast please. First of all some proof or a pointer to where and how that is happening would have been nice. Since I seem to have to do the leg work myself here, (in a new branch) I made Expat's CMake build system [produce some debug info](https://github.com/libexpat/libexpat/commit/1a49342bd55407e77669cfabaca77a4c95b3f082) about the Git repo state around it and the environment variables and also [force the build to fail](https://github.com/libexpat/libexpat/commit/4d559a6a5f97a2822f1258fc66939740b7f511f0) to see if CiFuzz would prove being affected. From that experiment I can say now that while there seems that intends to replace the code by other code based on `GITHUB_*` variables, it fails in practice with error…

```
2023-06-06 15:54:19,304 - root - ERROR - Can not check out requested state 1e69fef73ab6f142d1c6a6003f6ae475a9fa0e06. Using current repo state.
```

…and hence the added debug output and the forced build failure had zero effect on the CI run, which is in conflict with the statements you made.

The related CI log is at https://github.com/libexpat/libexpat/actions/runs/5190685002/jobs/9357468659#step:4:566 and I'm also [attaching a full copy](https://github.com/google/oss-fuzz/files/11666783/cifuzz_expat_1e69fef73ab6f142d1c6a6003f6ae475a9fa0e06_build_log.txt) that will outlive that CI log link.

To me this finding proves that the CiFuzz action is broken. I would like to suggest to:
- please re-open this issue
- please do not fall back to the default code but instead fail the build loudly
- please consider adding a docker build argument to not even clone the default branch if not meant to be used later

Thank you!

CC @DavidKorczynski

**Comment by jonathanmetzman** [comment]
CIFuzz works (checks out pull requests or a specific commit from master) in the general case, see these as proof:
https://github.com/systemd/systemd/actions/runs/5190612625/jobs/9357290691?pr=27942#step:4:163
https://github.com/systemd/systemd/actions/runs/5190612625/jobs/9357290691?pr=27942#step:4:1483
While it's possible CIFuzz is broken in the general case, there are a lot of users of CIFuzz, I think I would have gotten complaints from them. I think it's more likely that it's broken in the case of expat.

> @oliverchang @jonathanmetzman not so fast please. First of all some proof or a pointer to where and how that is happening would have been nice. 

It's not so easy to understand the source, but here it is: https://github.com/google/oss-fuzz/blob/master/infra/repo_manager.py#L196
https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/continuous_integration.py#L196

Since I seem to have to do the leg work myself here, (in a new branch) I made Expat's CMake build system [produce some debug info](https://github.com/libexpat/libexpat/commit/1a49342bd55407e77669cfabaca77a4c95b3f082) about the Git repo state around it and the environment variables and also [force the build to fail](https://github.com/libexpat/libexpat/commit/4d559a6a5f97a2822f1258fc66939740b7f511f0) to see if CiFuzz would prove being affected. From that experiment I can say with confidence now that while there seems to be code that intends to replace the default-branch code by other code based on `GITHUB_*` variables, it fails in practice with error…
> 
> ```
> 2023-06-06 15:54:19,304 - root - ERROR - Can not check out requested state 1e69fef73ab6f142d1c6a6003f6ae475a9fa0e06. Using current repo state.
> ```
> 
> …and hence the added debug output and the forced build failure had zero effect on the CI run, which is in conflict with the statements you made.

How did you make CIFuzz run here? On-push to a branch? This isn't how it's normally used, could you open a PR and see if it works as intended there?


> 
> The related CI log is at https://github.com/libexpat/libexpat/actions/runs/5190685002/jobs/9357468659#step:4:566 and I'm also [attaching a full copy](https://github.com/google/oss-fuzz/files/11666783/cifuzz_expat_1e69fef73ab6f142d1c6a6003f6ae475a9fa0e06_build_log.txt) that will outlive that CI log link.
> 
> To me this finding proves that the CiFuzz action is broken. I would like to suggest to:
> 
> * please re-open this issue
> * please consider not falling back to the default code but to instead fail the build loudly

Probably a good idea.

> * please consider adding a docker build argument to not even clone the default branch if not meant to be used later

This is a bit of an invasive change to OSS-Fuzz, I'd rather keep things simpler for users on the oss-fuzz, even if it means CIFuzz code has to be more complex/brittle.

> 
> Thank you!
> 
> CC @DavidKorczynski


I'm pretty sure youre running into an edge case we don't handle, which is when a project is named differently than in projects/$PROJECT_NAME

**Comment by hartwork** [comment]
Hi @jonathanmetzman, thanks for re-opening the issue and for sharing more details :pray: 

Regarding the name mismatch, I just did the same with usbguard where the naming seems to fully match, except in a fork repository (due to lack of push permissions). The result was the same:
```
2023-06-06 19:42:18,245 - root - ERROR - Can not check out requested state 5fe2754c3c9ce218b068ea7d9dd5902347635446. Using current repo state.
```
So we can rule out that it's the name mismatch and that it's specific to expat.

When taking the same code to a pull request (on a fork, targetting the fork, https://github.com/hartwork/usbguard/pull/1) I get error…
```
2023-06-06T19:50:26.5272443Z 2023-06-06 19:50:26,525 - root - ERROR - Can not check out requested state refs/pull/1/merge. Using current repo state.
```
…which could mean that CiFuzz is not using the correct Git remote to fetch from, since the fork has `refs/pull/1/merge` and its origin doesn't.

(I would rather not open pull requests at the origin repositories to not pollute that space, for now.)

What do you think?

**Comment by jonathanmetzman** [comment]
> Hi @jonathanmetzman, thanks for re-opening the issue and for sharing more details pray
> 
> Regarding the name mismatch, I just did the same with usbguard where the naming seems to fully match, except in a fork repository (due to lack of push permissions). The result was the same:
> 
> ```
> 2023-06-06 19:42:18,245 - root - ERROR - Can not check out requested state 5fe2754c3c9ce218b068ea7d9dd5902347635446. Using current repo state.
> ```
> 
> So we can rule out that it's the name mismatch and that it's specific to expat.

Ah so my best guess now is the issue is specific to the setups we are trying here. For example, CIFuzz is known to not work when targeting forks: https://github.com/google/oss-fuzz/issues/3731

> 
> When taking the same code to a pull request (on a fork, targetting the fork, [hartwork/usbguard#1](https://github.com/hartwork/usbguard/pull/1)) I get error…
> 
> ```
> 2023-06-06T19:50:26.5272443Z 2023-06-06 19:50:26,525 - root - ERROR - Can not check out requested state refs/pull/1/merge. Using current repo state.
> ```
> 
> …which could mean that CiFuzz is not using the correct Git remote to fetch from, since the fork has `refs/pull/1/merge` and its origin doesn't.
> 
> (I would rather not open pull requests at the origin repositories to not pollute that space, for now.)
> 
> What do you think?

Perhaps I made some bad design decisions, but I only anticipated CIFuzz being used to test master (when code is committed) or pull requests to the main repo, so I think if we're trying to test CIFuzz without doing those, I think we're going to get weird results because we're not using CIFuzz as intended.

**Comment by jonathanmetzman** [comment]
I think we can only really show CIFuzz has an issue if we test it on a pull request or push to master.

**Comment by hartwork** [comment]
@jonathanmetzman the examples at https://google.github.io/oss-fuzz/getting-started/continuous-integration/ do not disable use in a fork. I can accept the priority argument but a GitHub Actions action that does not support push events (#10472) and forks (#3731) properly is not a well-behaved GitHub action.
