### ISSUE TITLE
Must Python projects be 3.9-compatible?

### ISSUE THREAD

**Issue by pnacht** [google/oss-fuzz#10502]
My project has type-hints only available as of 3.10 (specifically, `list` instead of `typing.List` and `dict` instead of `typing.Dict`).

I'm trying to get it to run with CFLite and so I'm following the instructions in the docs. I've reached the point of [local testing](https://google.github.io/clusterfuzzlite/build-integration/#testing-locally). When I run `check_build`, it fails complaining about my new-style type hints. Replacing them with `typing.List` makes the build pass.

I've found the following, from which I take it that projects are always run on Python 3.9.

https://github.com/google/oss-fuzz/blob/51a64fec1f0f5454c1db2d68c76b40741da4fc7b/infra/base-images/base-builder/compile_python_fuzzer#L36-L37

Is this correct? If so, this should probably be clearly stated in the [Python integration documentation](https://google.github.io/clusterfuzzlite//build-integration/python-lang/).

**Comment by DavidKorczynski** [comment]
You should be able to use python 3.10. Could you try and do the same as `scipy` but for a version that satisfies your needs? I think that should work.
https://github.com/google/oss-fuzz/blob/51a64fec1f0f5454c1db2d68c76b40741da4fc7b/projects/scipy/Dockerfile#L18-L23

The code you link to shouldn't be triggered in `check_build` so I assume that's not actually where the error occurs? I think it's likely because the base images in general has a Python 3.8 image version:

https://github.com/google/oss-fuzz/blob/51a64fec1f0f5454c1db2d68c76b40741da4fc7b/infra/base-images/base-builder/Dockerfile#L22-L24
