### ISSUE TITLE
spring-cloud-config: EnvironmentFuzzer and ConfigServerPropertiesFuzzer failing on every run

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10601]
Please fix this

Failing with:

```
 "Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
[rules_jni]: Failed to find libjvm.so. Add it to the library search path or set JAVA_HOME
```

**Comment by jonathanmetzman** [comment]
CC @kyakdan @fmeum @0roman @henryrneh

**Comment by jonathanmetzman** [comment]
Same happening to spring-cloud-netflix_HostnameBasedUrlRandomizerFuzzer

**Comment by fmeum** [comment]
Since `libjvm.so` is part of the JDK and something fails in `apt`, it's possible that fixing the `apt` failure also fixes the Jazzer failure.

**Comment by jonathanmetzman** [comment]
Is jazzer tryign to install libjvm via apt? I don't think apt packages can be installed because the instances have limited internet access (@oliverchang is this right?)

**Comment by fmeum** [comment]
No, not Jazzer, but this particular project appears to install a custom JDK in its `build.sh` using `apt` and sets it as the `JAVA_HOME` for Jazzer: https://github.com/google/oss-fuzz/blob/7accb03eee4613d40f801c9eeb752e2336504839/projects/spring-cloud-config/build.sh#L78

If this install step fails but the build script itself doesn't fail, Jazzer will start but fail to find the relevant part of the JDK to launch a JVM.

Maybe the fix is to move the `apt` step to the Dockerfile?

**Comment by jonathanmetzman** [comment]
I think this is the correct fix. Yep!

**Comment by henryrneh** [comment]
I can have a look and try to fix it later this week or next week, thanks @jonathanmetzman @fmeum !

**Comment by fmeum** [comment]
I submitted https://github.com/google/oss-fuzz/pull/10666
