### ISSUE TITLE
some wireshark fuzz runs fail to sync corpus due to size explosion

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1087]
https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-01-11/2018-01-17/fuzzer/libFuzzer/job/libfuzzer_asan_wireshark

libFuzzer_wireshark_fuzzshark_ip - minimized corpus size (41319, 34 MB)
libFuzzer_wireshark_fuzzshark_ip_proto-udp - minimized corpus size (45157, 26 MB)

But problem is size explosion. We run corpus minimization once a day, but after few fuzz runs, corpus just explodes. Current size is ~200K which is crazy. There is either some randomness or instability in fuzz target causing this.

gsutil ls gs://wireshark-corpus.clusterfuzz-external.appspot.com/libFuzzer/wireshark_fuzzshark_ip/ | wc -l
197833

@jwzawadzki - can you please take a look or any ideas to fix this. you can try running these targets locally and see corpus growing very fast.

**Comment by inferno-chromium** [comment]
afl stability numbers are low here as well.

fuzzerFuzz target | logs | total_crashes | new_crashes | known_crashes | edge_cov | func_cov | corpus_size | corpus_backup | avg_exec_per_sec | new_tests_added | stability
afl_wireshark_fuzzshark_ip_proto-udp | Logs | 826 | 2 | 8 | 35.09% (91692/261312) | 42.20% (29628/70208) | 45157 (26 MB) | Download | 1,737.431 | 0 | 39.265
afl_wireshark_fuzzshark_ip | Logs | 73 | 0 | 5 | 35.55% (92927/261363) | 43.72% (30693/70207) | 41319 (34 MB) | Download | 590.464 | 0 | 32.247

**Comment by kcc** [comment]
One thing that I observe is that malloc/free are not balanced in the target. 
This causes the asan build to spend too much time running lsan on the first iterations
until leak checking gets disabled. See http://llvm.org/docs/LibFuzzer.html#leaks
```
INFO: libFuzzer disabled leak detection after every mutation.
      Most likely the target function accumulates allocated
      memory in a global state w/o actually leaking it.
      You may try running this binary with -trace_malloc=[12]      to get a trace of mallocs and frees.
      If LeakSanitizer is enabled in this process it will still
      run on the process shutdown.

```

This may or may not be related to the corpus size explosion

**Comment by kcc** [comment]
Next roadblock: I am hitting https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5452 pretty soon.

**Comment by kcc** [comment]
There are a few bugs filed already: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label:Proj-wireshark against this and related targets, that are not fixed. 

I also see some bugs (timeouts, buffer overflows, assertion failuers, allocation failures, etc) that were not filed automatically yet, probably exactly because oss-fuzz is having trouble dealing with the huge corpus. 

So, I'd just recommend @jwzawadzki to run the target on all items of the full corpus and fix whatever reproduces

**Comment by kcc** [comment]
And there is most definitely some global state being modified in the target. 
I've merged the corpus once with -timeout=1 (i.e. the new corpus should not have bugs nor timeouts)
and the resulting corpus has various bugs and timeouts. 

Giving up for now. Please ping this issue when then shallow bugs on this targets are fixed (if the corpus size problem remains)

**Comment by jwzawadzki** [comment]
Hi,

Is this bug a new issue, or size explosion was always the problem?
Honestly I am not aware of recent code changes in wireshark,
nor in base corpus, which could cause that.

I tried to take a look on bug report for 5452, and access full corpus
(following the https://github.com/google/oss-fuzz/blob/master/docs/corpora.md),
but I don't have access to it (I am not in wireshark project.yaml).

Pinging some people from project.yaml list (@Lekensteyn, @moshekaplan, @crondaemon, @rknall), Can you please take a look on this issue?

**Comment by inferno-chromium** [comment]
This is not a new issue, we just discovered it while analyzing some gsutil rsync failures in our logs. This is important issue since right now fuzzing on those targets will not work at all with that huge corpus size.

@jwzawadzki - you can access corpus after we add you to project.yaml file, can you send a pull request and we can ask other maintainers to +1.

**Comment by inferno-chromium** [comment]
@Lekensteyn, @moshekaplan, @crondaemon, @rknall - did you get a chance to take a look. if you guys don't care about this target, please disable it in build configuration. This is causing >200K files in our gcs buckets and causing some annoying exceptions.

**Comment by catenacyber** [comment]
@kcc Is that why I could find a timeout bug in Wireshark, not yet reported by oss-fuzz ?
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14362
A first fix has been pushed, see https://code.wireshark.org/review/#/c/25497/

**Comment by kcc** [comment]
> https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14362

I don't have access to this. 
But generally, yea, if the target has too many shallow crashes (as this one has) 
it stops finding any new ones (or at least does it very slow)

**Comment by jwzawadzki** [comment]
Hello,

It's not really related to size explosion, but as being adviced we're trying to fix current issues, and timeout issues from corpus.

I was trying to diagnose 'ASSERT: result != 0' [https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4026]. this assert line seems to be caused by g_get_home_dir() calling getpwuid_r() which is failing (no /etc/passwd in worker?).

I did change: https://code.wireshark.org/review/#/c/25545/2/tools/oss-fuzzshark/fuzzshark.c, and today issues 4700, 4302, 4139, 4026, 4589 got marked as fixed. (yesterday we did fix only for 5452, which is still open).

Looking at logs after 9am, all have 500-600 bytes, with output:
```
test it
(process:1): GLib-WARNING **: getpwuid_r(): failed due to unknown user id (0)
(process:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
g_home=(null)
```
Next line was trying to printf result of g_get_user_data_dir().
There is no crash indicator about loader not founding the symbol, but glib documentation tells that g_get_user_data_dir() is provided since glib-2.6, so I need to ask does workers uses prehistoric glib version?

I already pushed change: https://code.wireshark.org/review/#/c/25551/2/tools/oss-fuzzshark/fuzzshark.c, it should restore fuzzer back to normal.

Still I wonder:
 - what is current status of fuzzers? log files don't help.
 - if worker have (or might have) different glib version than is installed during building, during building we're checking if glib-2.22 is installed. In some places we also have some GLIB_CHECK_VERSION macros to check if we can use some recent glib functions.
 - How does work assigning the crash to bug?
   For example I am looking at crash https://oss-fuzz.com/v2/testcase-detail/4823573425291264,
   which is caused by timeout, it was generated by fuzzer: libFuzzer_wireshark_fuzzshark_ip, and it's marked as issue 4026. Issue 4026 is using Fuzzer: libFuzzer_wireshark_fuzzshark_udp_port-dns.
Does some output parser is confused by every time repeated: "(process:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed" ?

**Comment by Lekensteyn** [comment]
[probably not related to the corpus explosion, but as a heads up:]
I am currently lagging behind with processing oss-fuzz reports, but just FYI: at least one report resulted from a difference in the fuzz target (fuzzshark) and the actual users (tshark, wireshark). Real users wrap the dissection function in a TRY/CATCH block which will capture `DISSECTOR_ASSERT` and the like. This is not done by fuzzshark which can result in the program aborting (which will not happen in the real world).

**Comment by inferno-chromium** [comment]
@jwzawadzki - you can see stats here - https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-01-03/2018-02-04/fuzzer/libFuzzer/job/libfuzzer_asan_wireshark and for this fuzz target by clicking fuzz target name here which leads to https://oss-fuzz.com/v2/fuzzer-stats/by-day/2018-02-02/2018-02-04/fuzzer/libFuzzer_wireshark_fuzzshark_ip/job/libfuzzer_asan_wireshark

Regarding https://oss-fuzz.com/v2/testcase-detail/4823573425291264, result != 0 is first line in crash state, but there are still 2 more frames used to deduplicate - dissect_thrift_map, dissect_thrift_common. But you are right, it is marking everything as assertion failure due to this. Is there a way to suppress this assertion, then crash state and type will be correct.

**Comment by inferno-chromium** [comment]
No longer 200K, it is 95K now, closing.
