### ISSUE TITLE
coverage_extra_args not honored in coverage build

### ISSUE THREAD

**Issue by gedigi** [google/oss-fuzz#10887]
I recently onboarded the `aptos-core` project and I noticed that its coverage build fails:

https://oss-fuzz-build-logs.storage.googleapis.com/log-402c8a27-d2bd-4d65-80e6-8be662548bb0.txt

The `project.yaml` [file](https://github.com/google/oss-fuzz/blob/master/projects/aptos-core/project.yaml#L13) contains the appropriate `coverage_extra_args` parameter that should prevent the issue from happening.

Locally, the command:
```bash
python infra/helper.py coverage aptos-core
```
produces the same error, but by adding `-- -ignore-filename-regex='.*/rustc/.*'` it builds successfully.

Please advise.

**Comment by Alan32Liu** [comment]
Hi @gedigi, could you please try removing [the single quote in the arg](https://github.com/google/oss-fuzz/blob/master/projects/aptos-core/project.yaml#L13)? Here is [an example usage of `-ignore-filename-regex`](https://google.github.io/oss-fuzz/advanced-topics/code-coverage/#additional-arguments-for-llvm-cov-cc-only).

I think the error is caused by an incorrect interpretation of `'.*/rustc/.*'`.
We cannot reproduce it locally because bash can handle it as expected.
I can reproduce the error using `python infra/helper.py coverage aptos-core -- "-ignore-filename-regex='.*/rustc/.*'"`.

**Comment by gedigi** [comment]
Thanks, I can reproduce the error with quotes, and I get no error without. However - without the extra argument - the `coverage` command does not get the directive in `projects.yaml`:

```bash
~/src/oss-fuzz $ cat projects/aptos-core/project.yaml | tail -1
coverage_extra_args: -ignore-filename-regex=.*/rustc/.*
~/src/oss-fuzz $ python infra/helper.py coverage aptos-core 
INFO:__main__:Downloading corpora for aptos-core project to /home/gerardo/src/oss-fuzz/build/corpus/aptos-core.
INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e HELPER=True -e FUZZING_LANGUAGE=rust -e PROJECT=aptos-core -e SANITIZER=coverage **-e COVERAGE_EXTRA_ARGS=** -e ARCHITECTURE=x86_64 -e HTTP_PORT=8008 -p 8008:8008 -v /home/gerardo/src/oss-fuzz/build/corpus/aptos-core:/corpus -v /home/gerardo/src/oss-fuzz/build/out/aptos-core:/out -t gcr.io/oss-fuzz-base/base-runner coverage.

```

is this the expected behavior for local builds?

**Comment by Alan32Liu** [comment]
> without the extra argument - the `coverage` command does not get the directive in `projects.yaml`:

That seems to be another bug we should fix.
Thanks for reporting this, I will look into it later.

**Comment by gedigi** [comment]
thanks - created a [PR](https://github.com/google/oss-fuzz/pull/10904/files) to solve this
