### ISSUE TITLE
base-builder:  '/usr/lib/libFuzzingEngine.a': No such file or directory

### ISSUE THREAD

**Issue by holiman** [google/oss-fuzz#11159]
Something seems to be amiss with the base-builder.
```
$ docker pull gcr.io/oss-fuzz-base/base-builder:latest
latest: Pulling from oss-fuzz-base/base-builder
Digest: sha256:e40819d173af6fa804acfa201398708cc8f6587c761dde9e4b53f3e708bee14d
Status: Image is up to date for gcr.io/oss-fuzz-base/base-builder:latest
gcr.io/oss-fuzz-base/base-builder:latest

$ docker run -it gcr.io/oss-fuzz-base/base-builder bash
root@b3f8c3b41086:/src# ls $LIB_FUZZING_ENGINE
ls: cannot access '/usr/lib/libFuzzingEngine.a': No such file or directory
```
Don't know if it's something on my end, but I don't see how

**Comment by DavidKorczynski** [comment]
Am not sure what the specific issue is since the above is not a workflow as such in the OSS-Fuzz infra.

The path of `LIB_FUZZING_ENGINE` is overwritten https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_afl#L27 and https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_honggfuzz#L20 in various places throughout the infra, and the var itself is also overwritten https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_libfuzzer#L19 . These overwrites occur when you run e.g. `python3 infra/helper.py build_fuzzers ...`.

What are you trying to achieve here?

**Comment by holiman** [comment]
Right, confusion on my side. I was debugging a different step, and then I forgot to perform the build_fuzzers , and thought that the fuzzers would be already present in the image. Sorry for the noise!
