### ISSUE TITLE
truncated MSAN report

### ISSUE THREAD

**Issue by titanous** [google/oss-fuzz#1118]
The testcase at https://oss-fuzz.com/v2/testcase-detail/6286705993711616 appears to have a MSAN report that is cut off:

```
==1==WARNING: MemorySanitizer: use-of-uninitialized-v
```

**Comment by inferno-chromium** [comment]
Reuploaded as https://oss-fuzz.com/v2/testcase-detail/5445478331187200 (it is a dupe of https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5623).

We need to fix the reproducibility since we try to compare crash state against the original stacktrace(which is truncated). maybe we should discard it.

**Comment by inferno-chromium** [comment]
We deployed a fix which should remove such cases. Basically, it will try to minimize such cases still and then update crash paramaters.

**Comment by inferno-chromium** [comment]
Seems fixed, i see proper crash states for recent afl crashes. @jonathanmetzman as fyi.
