### ISSUE TITLE
bugs.chromium.org issue not synced to oss-fuzz issue

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#1124]
https://oss-fuzz.com/v2/testcase-detail/4891144551923712 is marked as fixed, but the linked
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5717 is still open.

**Comment by inferno-chromium** [comment]
another instance of https://github.com/google/oss-fuzz/issues/1038. adding more debugging code now.

**Comment by inferno-chromium** [comment]
till then, i readded the bug mapping so that this bug will close as verified soon.

**Comment by inferno-chromium** [comment]
Debugging for similar issue lead to this

1. Filed new bug in triage task.
2018-02-04 10:34:00.843 PST
Updated testcase 4961303614455808 (bug 5988).
2018-02-04 10:34:01.229 PST
Filed new issue 5988 for testcase 4961303614455808.

2. Lost testcase bug information in next iteration of that triage task.
2018-02-04 11:20:36.457 PST
Updated testcase 4961303614455808 (bug ). 
2018-02-04 11:20:36.458 PST
Updated testcase 4961303614455808 group to 6466324713701376. 

Only way this can happen is if testcase.put() failed which i have no clue how it can. @oliverchang - thoughts ?

**Comment by oliverchang** [comment]
Only thing I can think of is Datastore eventual consistency (https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/#eventual-consistency-in-cloud-datastore)

In issue_filing right after we file the issue (where we update the testcase's bug id), we do `updateGroupBug`, which runs a query to look for all testcases with the same group id, and do a db.put() on all of them (which also means we don't log them since it's a batch put). If the group query returned a stale result for the testcase we just updated, we lose the bug association.

**Comment by inferno-chromium** [comment]
Thanks @oliverchang, i looked at updateGroupBug, but missed the point about batch put. Let me add a delay somewhere.

**Comment by oliverchang** [comment]
I think I might have a better fix, I'll upload it in a bit.

**Comment by inferno-chromium** [comment]
Thanks @oliverchang for the fix.

Lets keep bug open for another week, i can check back next week to see if any other instances turn up, if not, will close.
