### ISSUE TITLE
honggfuzz: false positive with strlcat

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#11255]
Not reproducible with libFuzzer : 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64321

Is something wrong with honggfuzz ?

**Comment by bvanassche** [comment]
I think that a bug got introduced in some fuzzing infrastructure a few days ago. Since a few days ago I started noticing multiple incorrect reports about strlcat() output buffer overflows. Here is an example of such an issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64351. That issue is about an output buffer overflow for the following code:
```
char            defbuf[512];
[ ... ]
strlcat(defbuf, quoted_string_buffer, sizeof(defbuf));
```
I think that strlcat() guarantees that it does not overflow its output buffer if it is used as above.

**Comment by catenacyber** [comment]
Seems fixed last week-end for me

**Comment by catenacyber** [comment]
Likely by https://github.com/google/honggfuzz/commit/191266061f5cd89082a0238b04cb367f8e099e17 thanks @robertswiecki
