### ISSUE TITLE
minimized testcase isn't very minimal

### ISSUE THREAD

**Issue by josephbisch** [google/oss-fuzz#1129]
I'm looking at https://oss-fuzz.com/v2/testcase-detail/5404984473550848.

The "minimized testcase" is still ~1 KB. When trying to further minimize the testcase locally, I was able to quickly get a 16 byte testcase with libfuzzer (my own fuzz target build outside of the context of oss-fuzz).

I then noticed that the job type was afl_asan_irssi, so I downloaded the build that was linked from that page and I tried using the supplied afl-tmin (and supplied fuzz target) to minimize the testcase and got a 19 byte reproducer.

**Comment by oliverchang** [comment]
I suspect this is because we check that the top 3 stack frames are the same during minimization on our infrastructure, but as this is a stack overflow, the top frames shift around quite often while the testcase is minimized.

**Comment by oliverchang** [comment]
@inferno-chromium I verified from logs that it was indeed because the frames shifted around during minimization, leading us to failing the task. Do you think it's worth adding a special case or stack overflows?

**Comment by inferno-chromium** [comment]
@oliverchang - i think we can ignore crash state comparison when minimizing stack overflow, and just check for crash type ? i think we kind of do this for timeout and ooms by using a custom crash state of fuzz target name, so for stack overflow, we can either turn this into same custom crash state OR ignore that during minimization. We can base this decision, by checking how reliable stack overflow bugs are for fuzz target, do they get closed because of stacks shifting in a couple of days ? if yes, then we can even change their crash state to fuzz target name. thoughts ?

**Comment by inferno-chromium** [comment]
This can be a risky fix as well. What if there are multiple stack overflows and we jump to the other one during minimization. I think better to be on side of caution and leave testcase unminimized than trying to minimize and  create a duplicate. What can happen is we will keep minimizing to another crash state and keep losing original bug. Lets hold on this for now.

**Comment by oliverchang** [comment]
Sounds reasonable. Closing this for now then!

**Comment by elizabethdinella** [comment]
@oliverchang can you describe the minimization process? Is it simply random mutations + the caveat that the top 3 stack frames must be equivalent?

**Comment by kcc** [comment]
It's simply random mutations that try to reduce the input size. 

If ASAN's dedup token is used, it also checks that the token is preserved. 
Otherwise it simply checks that some crash is still there. 
https://github.com/llvm-mirror/compiler-rt/blob/master/lib/fuzzer/FuzzerDriver.cpp#L367
