### ISSUE TITLE
Replicating Docker environment locally and confirming UBSan crash

### ISSUE THREAD

**Issue by matt-kwong** [google/oss-fuzz#1154]
Context here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6171

We're trying to fix this crash and think being able to replicate this locally would make debugging much easier. Also, a few of us have tried, but not been able to make sense of this crash. Could you confirm if this looks like a legitamate crash, and if so, do you have any tips on how to approach fixing this? We're quite stuck. Thanks!

**Comment by kcc** [comment]
The first thing that I recommend doing in such cases is to look for the sources of 'non-reproducible' behavior. Since we are already testing this code with asan, but *not* with msan, at least on oss-fuzz, 
the first step would be to check this code of uses of uninitialized values. 

I'll poke at this case a bit more.

**Comment by kcc** [comment]
This is a real bug but we are not doing great job reporting it. 
If you add -fsanitize=alignment to ubsan flags you'll see that the 
pointer passed to the constructor is not 16-byte aligned. 
(Also, filed #1156)

This happens because you rely on malloc returning 16-byte aligned pointer. 
In many cases malloc will do that, but not always (but e.g. asan's malloc is always 16-byte aligned).
Now, if malloc does return a non-16-byte aligned pointer, it doesn't mean you will actually crash. 
Bad things will happen only if the compiler uses some instructions that require 16-byte alignment. 
In this case the compiler chose to use movaps.

The fix is to use aligned memory (via `memalign` or some such). 

hth

**Comment by kcc** [comment]
you are welcome! 

I tried to build the docker image for grpc but the build is currently broken.
So, here are un-tested hint: you can `apt-get install gdb` inside the docker image to get gdb to debug things. In this case, the debugger would instantly point you at the movaps
