### ISSUE TITLE
Security categorization often wrong for debug assertions

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1168]
In the case where OSS-Fuzz finds a assertion, it marks it as a non-security bug. Unfortunately this is wrong for the cases where the assertion only happens in debug builds, and in release builds what happens is memory corruption.

This could be detected by re-running the crasher on a release build and if that's a security issue, considering the assertion failure as a security issue. For spidermonkey I try to do these manually, but automation handling them would be great.

**Comment by kcc** [comment]
Part of the problem is that we don't distinguish debug and release builds. 
More generally, I think it's mostly impossible to distinguish security vs non-security bugs automatically (or at all) .
Some of the scariest **security** bugs I've seen were miscomputations and null derefs. 

But the categorization does not affect how the bug are treated by the oss-fuzz bug tracker.

**Comment by inferno-chromium** [comment]
How often do you see this usecase ?

We can have both debug and release builds, it increase the maintenance burden. We can also run a debug build found testcase with another specific build (like release) automatically, however, we wont change crash params and security flags, so it wont help to mark that issue tracker bug as security.

In chromium land, we have this concept of security asserts, which are also enabled in release build (https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/wtf/Assertions.h?type=cs&q=SECURITY_ASSERT&sq=package:chromium&l=51). And we add a specific parse signature for that. But that means, you would need to know beforehand which assert can have security implications.

@oliverchang @mbarbella  - do you have any other ideas of simplifying this for all projects in oss-fuzz.

**Comment by inferno-chromium** [comment]
@alex - release build can be changed easily by removing this i think - https://github.com/google/oss-fuzz/blob/master/projects/spidermonkey/build.sh#L27.

Upto you, how much you care about asserts ? Lets wait @oliverchang to respond, we might keep both debug and release builds.

**Comment by alex** [comment]
Yes, agreed that changing the `build.sh` would be straightforward. I think catching regular asserts is very useful. I don't think fuzzing both debug and release would add a ton of value, compared to my suggestion of using release to verify a debug bug.

**Comment by oliverchang** [comment]
Sorry missed this in my inbox somehow. Our security categorisation is a best effort heuristic -- even for the usual crash types (null derefs, buffer overflows, wild derefs) we can't really be 100% sure about whether if they're security relevant or not. As Kostya mentioned earlier it doesn't affect how we treat them.

I feel like maintaining a separate release build is more trouble than it's worth because it doesn't necessarily increase our accuracy at this. How much value would this give you?

**Comment by alex** [comment]
Of all the projects I work on, it'd only affect spidermonkey. There it'd save me a few minutes of work for each bug.

**Comment by oliverchang** [comment]
I'm not sure it's worth supporting this then (at least for now), as it'd increase our maintenance burden a fair bit.

If this comes up again, we can revisit. Thanks for bringing it up.
