### ISSUE TITLE
unable to access clusterfuzz dashboard

### ISSUE THREAD

**Issue by jvaclav-rh** [google/oss-fuzz#12159]
Hi, recently I requested for a project to be added to oss-fuzz (#12105), but I still don't have access to the clusterfuzz dashboard.

When trying to access it with my Google account (same email as in the `project.yaml` file), I get this error:
> You (email=jvaclav@redhat.com) are not authorized to access this page!

Is there some additional steps I need to take? I did not find anything regarding this, so I just assume something went wrong somewhere.

**Comment by DavidKorczynski** [comment]
This is because you only added a `project.yaml` file -- you need to add an appropriate fuzzing harness set up as well. Specifically, [build.sh](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#buildsh), [Dockerfile](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dockerfile) and a set of fuzz harnesses.

**Comment by DavidKorczynski** [comment]
Closing this, let me know if the issue persist after the `build.sh` and `Dockerfile` has been added
