### ISSUE TITLE
Bugs not getting filed?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1221]
https://oss-fuzz.com/v2/testcases?open=yes&project=imagemagick&issue=no

shows numerous reproducible crashes that don't have bugs created for them

**Comment by inferno-chromium** [comment]
This happens when we incorrectly closed a testcase and then another one showed up, we wait for 2 days before filing the new one. this helps to throttle spam if we have a bug in our framework or if testcase is flaky. These will auto-file in 2 days. Will keep this issue open till then and then close.

E.g. see https://oss-fuzz.com/v2/testcase-detail/6486704652288000 is open since similar https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6760 was just closed. It could be due to flake, so throttle is important.

**Comment by alex** [comment]
Ok! I guess this is all working as intended.

It might be nice of the UI communicated this somehow, but 👍

**Comment by inferno-chromium** [comment]
https://oss-fuzz.com/v2/testcase-detail/5681728522813440 is open since similar https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5362 was just closed
