### ISSUE TITLE
wrong WontFix conclusion drawn

### ISSUE THREAD

**Issue by jbeulich** [google/oss-fuzz#12475]
Seeing

"Updates:
	Status: WontFix

Comment #4 on issue 70918 by ClusterFuzz-External: xen:x86_instruction_emulator: ASSERT: is_x86_user_segment(seg) || is_x86_system_segment(seg)
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70918#c4

ClusterFuzz testcase 6577340535078912 is flaky and no longer crashes, so closing issue."

I'm puzzled. The issue was supposedly fixed [1], so marking as WontFix doesn't look appropriate.

[1] https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=5ed317c45d7323a6985797dc9a2d39d8c5df8201

**Comment by oliverchang** [comment]
Thanks for the report and sorry for the confusing. Reproducing crashes is occassionally flaky on our infrastructure, which causes some bugs to get marked as WontFix instead of Fixed. 

WontFix has the same implications as Fixed for our automation -- the only difference is the actual status string itself.
