### ISSUE TITLE
buganizer spamming my email

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#12523]
buganizer-system@google.com is sending me an email for each past issue to my ossfuzz projects ! That means > one thousand emails. Can this be stopped now? thanks!

**Comment by davidben** [comment]
+1

I gather there's some kind of automated metadata update in the bugs, but can this metadata update be batched so that we only get one email for all of them? Or perhaps done in a way that doesn't send emails? (I know Monorail had some way for updates to suppress emails.)

**Comment by jonathanmetzman** [comment]
Very sorry for this. I had it stopped.

**Comment by rouault** [comment]
thanks

**Comment by evverx** [comment]
@jonathanmetzman thank you for fixing this.

Looks like all those notifications were sent to gmail addresses only in my case. I wonder if non-gmail addresses are no longer supported? (I know it wasn't possible to do much with those addresses apart from receiving notifications but it was useful in some cases)

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman thank you for fixing this.
> 
> Looks like all those notifications were sent to gmail addresses only in my case. I wonder if non-gmail addresses are no longer supported? (I know it wasn't possible to do much with those addresses apart from receiving notifications but it was useful in some cases)
> 
> Edit: Looks like something similar is being discussed in [#12508 (comment)](https://github.com/google/oss-fuzz/issues/12508#issuecomment-2375263992).

Could you share an issue where this happened?

**Comment by evverx** [comment]
I received more than a thousand notifications and when I saw this issue I just dropped them all because I assumed they affected all the issues where I had ever been CCed. Then I went to the elfutils mailing list (https://sourceware.org/pipermail/elfutils-devel/2024q3/thread.html) and didn't find anything there even though it's the primary contact there. The systemd and util-linux notifications went to my gmail address only (even though my non-gmail address is listed there too).
