### ISSUE TITLE
sqlite3 doesn't build.

### ISSUE THREAD

**Issue by mvanotti** [google/oss-fuzz#12709]
It seems like after sqlite3's commit [d8c0e0184226bdae](https://sqlite.org/src/info/d8c0e0184226bdae), `configure` no longer accepts the `--enable-shared` flag.

This flag was added in PR #10397 to add support for fuzz introspector.

**Comment by DavidKorczynski** [comment]
Added a fix here: https://github.com/google/oss-fuzz/pull/12710

However, a failed build is not as such an OSS-Fuzz issue because more or less at any moment there are some projects failing builds. There is a build status list here https://oss-fuzz-build-logs.storage.googleapis.com/index.html or https://introspector.oss-fuzz.com/indexing-overview
