### ISSUE TITLE
Autocomplete/filtering for upload testcase job dropdown

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1275]
If you're involved in many projects the number of items in the dropdown can be prohibitive to easy usage. It'd be great if it was a filterable/autocompletable dropdown ala https://select2.org/getting-started/basic-usage

**Comment by inferno-chromium** [comment]
it is actually filterable, you need to type the entry and it works. it is not intuitive, so what you type does not show up but the entry does get selected. This is due to polymer component https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu. we couldnt find a good polymer component that takes care of this today, which is sad. Probably file a bug on polymer elements.

**Comment by alex** [comment]
https://github.com/kolarski/select2-wrapper appears to be basically what you'd want, but it's from several years ago

**Comment by inferno-chromium** [comment]
That wont work since it is on Polymer 1.0, and we are on Polymer 2.0. Also, if such components dont update, we get stuck on migration.

**Comment by inferno-chromium** [comment]
filed https://github.com/PolymerElements/paper-dropdown-menu/issues/285

**Comment by inferno-chromium** [comment]
Should be fixed.
