### ISSUE TITLE
Include commit ID for cloned repositorties in testcase details

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1298]
Our project @ImageMagick has recently added a lot of dependencies to the fuzzer so we can also test the libraries that we use. In our Dockerfile we clone a set of repositories. It would be nice if the test-case creator could include a commit id for all the repositories that were cloned. This would make it a lot easier for us to report an issue upstream.

**Comment by jonathanmetzman** [comment]
This is an interesting idea. 
But I'm not sure how feasible it is for OSS-Fuzz to do this automagically since I don't think it knows about the repos used in a build (I'll try to figure out if this is true). 

Maybe you can add a step to build.sh that lists the versions of the repos in a file (let's call it VERSIONS) and then when you see a bug report you can find out the versions by downloading the build and reading the VERSIONS file.

**Comment by alex** [comment]
I think it does know, the regression ranges contain all the repos.

**Comment by jonathanmetzman** [comment]
@alex Thanks for pointing this out. 
@dlemstra I think I misunderstood you. Did you mean something other than this
![image](https://user-images.githubusercontent.com/31354670/38387784-da3d6128-38cd-11e8-8e5a-0ba70ec1bc16.png)

**Comment by dlemstra** [comment]
Thats what I meant. Never noticed that I could open that. Thanks for pointing that out @jonathanmetzman  and @alex !

**Comment by dlemstra** [comment]
@jonathanmetzman  and @alex. Looks like it is not always reported? https://oss-fuzz.com/v2/testcase-detail/5664142049411072?noredirect=1. This testcase used openjpeg but that library is not in that list.

**Comment by jonathanmetzman** [comment]
I'll try to figure out why this is next week.

**Comment by oliverchang** [comment]
This is likely because openjpeg was not cloned in our dockerfile for the earlier revision for that regression range.

i.e. openjpeg was added on Mar 25 in https://github.com/google/oss-fuzz/pull/1268, while the earlier commit in the regression range was built on Mar 22: https://github.com/imagemagick/imagemagick/commit/4fc6fc13832a0ab0037040cc951ace96b240eb22

**Comment by dlemstra** [comment]
Thanks for looking into this @oliverchang  👍
