### ISSUE TITLE
Expected latency for bug fixes?

### ISSUE THREAD

**Issue by fenner** [google/oss-fuzz#1303]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7471 reports a bug that I fixed 4 days ago. The report at https://oss-fuzz.com/v2/testcase-detail/5102970128564224?noredirect=1 says it ran against 883934016bd47181f32f031fe3c7d409d4c5fa82, which was a couple of weeks ago.  When a bug gets fixed, how long should we expect clusterfuzz to still be discovering it?

**Comment by inferno-chromium** [comment]
0:883934016bd47181f32f031fe3c7d409d4c5fa82 is regression range which means it calculated where the bug was first introduced at. 883934016bd47181f32f031fe3c7d409d4c5fa82 is the first revision when net-snmp project was built, so 0:883934016bd47181f32f031fe3c7d409d4c5fa82 means that this bug reproduced on the first archived build.

ClusterFuzz checks if a bug is fixed everyday. Last run can be checked in stacktrace, see section "Last tested stacktrace" which shows revision d1d0fe26a6d250656a4b1770bde2667ea44a9b33 or build generated on 20180408. When a bug is fixed, ClusterFuzz will autodetect in ~day since we generate only one build per day.
