### ISSUE TITLE
Incorrect regression revision range

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1307]
It looks like an incorrect regression range was reported for this issue: https://oss-fuzz.com/v2/testcase-detail/5163059740934144?noredirect=1. The clone should (and probably was) be done with the latest commit on the master but 63e57aa1ed4a07b809188d936015db0fd4394afb is reported as the commit ID that was used.

**Comment by inferno-chromium** [comment]
For imagemagick revision 6e9e67bfe3783c3516918441f2a123e68cd2d8bb, what was the libraw commit id, isnt it 63e57aa1ed4a07b809188d936015db0fd4394afb.

regression range means when the bug was introduced, so this is not using latest master, but an older build where bug was first seen.

**Comment by dlemstra** [comment]
Would it be an option to also include the current commit id in the message? When we report the issue upstream it is a bit annoying for the maintainers that the line numbers don't match the specified commit id. But thinking about this I could also copy past the link from the stack trace. I really love that link. +💯 for whoever added that feature 👍

**Comment by inferno-chromium** [comment]
Can you explain more. We already have a "Last tested Stacktrace <commit_id>" section in most reports (unless report is fixed in <1 day)
e.g. checkout.
https://oss-fuzz.com/v2/testcase-detail/5831210287759360

We check report is fixed once a day (since oss-fuzz builder builds once a day) and update this Last tested stacktrace section.

**Comment by dlemstra** [comment]
This issue was created on Sun, Apr 8, 2018, 2:04 PM. On April 6 and 8 the file `dcraw_common.cpp` was touched so the commit where this was reported should be a later one. And to be clear I am not talking about our commit id but the commit id of the libraw repository that we also cloned.

p.s. Cool that you added a picture to your profile 👍

**Comment by inferno-chromium** [comment]
I think what you mean here is in "Fixed Revision Range" field where we report the "Last run at":, you actually want the revision of all components and not just imagegraphics one.

And just fyi, regression range will always have old revision since it tells where bug was introduced. When reported bug upstream, you should use data from "Fixed Revision Range" field where it was last tested.

Does that sound correct ?

**Comment by dlemstra** [comment]
We cannot use the "Fixed Revision Range" because the issue is not yet fixed. We would like to tell the maintainer of the upstream repository with which commit id the code was tested.

**Comment by inferno-chromium** [comment]
We now have a dedicated section "LAST TESTED REVISION", if you expand that, it gives info on all components used in that revision. E.g. check in https://oss-fuzz.com/v2/testcase-detail/5831210287759360. Once a bug is fixed, then we instead show the "FIXED REVISION RANGE" section.
When filing a bug upstream, you can use data from "LAST TESTED REVISION" and stacktrace from "Last tested stacktrace" section (if not available, ORIGINAL STACKTRACE).
