### ISSUE TITLE
Unable to access reports I am included on

### ISSUE THREAD

**Issue by kaleb-himes** [google/oss-fuzz#1323]
Hi,

I work for wolfSSL Inc. and am cc'd on reports with the email ```kaleb<at>wolfssl<dot>com``` but am unable to view reports because oss-fuzz.com will only let me log in with my gmail address. I have associated ```kaleb<dot>himes<at>gmail<dot>com``` with that email and still I get:

```
You (email=Kaleb<dot>himes<at>gmail<dot>com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.
```

I also had my fellow colleague add me to the google group ```wolfSSL_OSS-Fuzz``` on both email accounts (wolfssl and gmail) and still cannot view reports.

Could you please fix this? Let me know if you need any more info.

Cheers,

Kaleb

**Comment by inferno-chromium** [comment]
See https://github.com/google/oss-fuzz#accepting-new-projects

be associated with a Google account (why?). If you use an alternate email address linked to a Google Account, it will ONLY give you access to filed bugs in issue tracker and NOT to ClusterFuzz dashboard (due to appengine api limitations).

**Comment by inferno-chromium** [comment]
Please add your gmail address to project.yaml for ClusterFuzz access.
