### ISSUE TITLE
starting at step zero

### ISSUE THREAD

**Issue by cary-clark** [google/oss-fuzz#1344]
I work on Skia, and am responsible for this bug:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7882

0) I can comment on this bug, but can't assign it to myself. That aside, I'd like zero-assumption steps on how to reproduce the bug.

Starting here:
https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

1) It tells me 
"If you have already integrated the fuzz target with your build and test system, all you do is run"

Since Skia is a multi-person project, I do not know how to tell if this condition has been met. Skia does have an active fuzzer target, but I don't know if this is related to your fuzz target or not.

2) Assuming that 1) is not integrated, what do I do next? Do the repro steps require Linux? Do they require a chrome repo? It says "If you are not sure how to build the fuzzer using the project's build system" implying (to me) that how I build (git, gn, ninja) should be related to how I build your fuzzer, but I don't think that's the case. Skia, Chrome, and depot_tools all have a folder named "infra", but none contain a helper.py.

3) I find it puzzling that the email reporting the bug tells me that the vulnerability will be disclosed in 60 days but leaves me no way to contact a human being short of filing this bug. Feels like a ransom demand.

**Comment by jonathanmetzman** [comment]
> 0. I can comment on this bug, but can't assign it to myself.

Will look into this.

>That aside, I'd like zero-assumption steps on how to reproduce the bug.

1. Download the [testcase](https://oss-fuzz.com/download?testcase_id=5702854485475328)
2. Open the testcase [page](https://oss-fuzz.com/testcase?key=5702854485475328)
3. Download the build from the testcase page and unzip it
4. ```$ ./path/to/unzipped/build/image_filter_deserialize_width ./path/to/testcase/clusterfuzz-testcase-minimized-image_filter_deserialize_width-5702854485475328```

I think that ordinarily you should be able to build the `fuzz` target in skia (using msan since that's what this bug was found with) and then run ./out/fuzz -t filter_fuzz -b ./path/to/testcase. However MSAN seems to complain another bug whenever `fuzz` is run, not sure if this is real or a problem with msan on rodete. 

I was able to repro with chromium's filter_fuzz_stub though:
```
$ gn gen out/lf-msan --args='is_debug=false use_libfuzzer=true optimize_for_fuzzing=true is_msan=true use_goma=true'
$ ninja -j2500 -C out/lf-msan/ filter_fuzz_stub
$ MSAN_OPTIONS="allocator_may_return_null=1" ./out/lf-msan/filter_fuzz_stub /path/to/clusterfuzz-testcase-minimized-image_filter_deserialize_width-5702854485475328
```

>It tells me "If you have already integrated the fuzz target with your build and test system, all you do is run"
> Since Skia is a multi-person project, I do not know how to tell if this condition has been met. Skia does have an active fuzzer target, but I don't know if this is related to your fuzz target or not.

It is not met. Skia is in a weird place with ClusterFuzz because it builds targets for ClusterFuzz that are not build-able from the skia repo. I think for reproduction skia devs are supposed to repro using the `fuzz` target. @kjlubick,maybe this should be changed? I believe Kevin was also working on automating reproduction on your end.

>Assuming that 1) is not integrated, what do I do next? 

Clone the OSS-Fuzz repo and then run the steps under "Reproduce using latest OSS-Fuzz build:"

>Do the repro steps require Linux?

I think so. We haven't tested it on Windows or Mac but I wouldn't be shocked if it worked.
 
>It says "If you are not sure how to build the fuzzer using the project's build system" implying (to me) that how I build (git, gn, ninja) should be related to how I build your fuzzer, but I don't think that's the case. Skia, Chrome, and depot_tools all have a folder named "infra", but none contain a helper.py.

These instructions are correct. `helper.py` and `infra` directory are located in the OSS-Fuzz repo. The instructions are general instructions for all OSS-Fuzz projects.

>I find it puzzling that the email reporting the bug tells me that the vulnerability will be disclosed in 60 days but leaves me no way to contact a human being short of filing this bug. Feels like a ransom demand.

It's a reminder of our automated policy which projects agree to before being submitted to OSS-Fuzz. Maybe the wording can be improved.

**Comment by jonathanmetzman** [comment]
Could you try again to assign the issue to yourself?

**Comment by cary-clark** [comment]
Yes, that worked, thanks

**Comment by kjlubick** [comment]
The "allocating too much memory" part of the test case is masking the underlying crash.  The fuzzer limits large allocations of memory when fuzzing (and when reproducing in docker).  I'll work with Cary to better reproduce this.

**Comment by kjlubick** [comment]
$ export  MSAN_OPTIONS=allocator_may_return_null=1
$ gdb out/MSAN/fuzz
(gdb) r -t filter_fuzz -b  /path/to/download
...
(gdb) bt

does the trick.  It is strange that MSAN only says "Segmentation fault" and doesn't dump a stacktrace.  IT is more curious that ASAN builds, and normal Clang builds don't fail like this either.

**Comment by inferno-chromium** [comment]
Lets discuss the part about easy reproduction offline, i think @kjlubick is looking into a skia-specific reproduction instructions.
