### ISSUE TITLE
bad_build_check: use seed_corpus

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1355]
Add one more check to https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check

The check should unpack seed corpus for the given fuzz target (if it exists), and do `./fuzz_target -runs=0 fuzz_target_seed_corpus` to perform regression testing.

**Comment by inferno-chromium** [comment]
I think we do somethings redundant OR confusing

we do run_fuzzer which unarchives seed corpus and runs with it.
bad_build_check does the redundant part of run_fuzzer and does not do anything with seed corpus.

Why does test_all need to run_fuzzer at all, why not just bad_build_check which also unpacks seed corpus in similar way. i think run_fuzzer can be left as is since it is needed in infra/helper.py if someone wants to just run fuzzer without bad build checks.

**Comment by inferno-chromium** [comment]
Ok then,

I think we can get rid of SKIP_TEST_TARGET_RUN from gcb/build.py
remove SKIP_TEST_TARGET_RUN and run_fuzzer from test_all
add seed corpus run to bad_build_check (i hope not more things break :(
