### ISSUE TITLE
Request read access to OSS-Fuzz issues for HarfBuzz

### ISSUE THREAD

**Issue by cjchapman** [google/oss-fuzz#1501]
Hi Folks,

I'm on the mailing list for OSS-Fuzz issues for HarfBuzz, but I am not allowed to view the issues linked in the emails.

For example, if I try to view:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8831
I get:
"You do not have permission to view the requested page. 
Reason: User is not allowed to view this issue"
(while logged in as cchapman@typekit.com)

Likewise, for:
https://oss-fuzz.com/v2/testcase-detail/5750092395970560?noredirect=1
I get:
"You (email=cchapman@typekit.com) are not authorized to access this page!
Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz."

Help?

Thanks,
Chris

**Comment by inferno-chromium** [comment]
See
https://github.com/google/oss-fuzz#accepting-new-projects
email
* be associated with a Google account (why?). If you use an alternate email address linked to a Google Account, it will ONLY give you access to filed bugs in issue tracker and NOT to ClusterFuzz dashboard (due to appengine api limitations).

**Comment by behdad** [comment]
Ok, thanks. They we probably should get replace our non-Googler contributors with their gmail addresses.

**Comment by behdad** [comment]
Did this one for Khaled, the only other non-Google address:
https://github.com/google/oss-fuzz/pull/1503
