### ISSUE TITLE
corpus cotains number files that change

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#154]
It seems that the corpus files now have both an sha1 file and a numbered file like 0000000000000042. I think the number files contain the same content as the other files. But they seem to get regenerated often, which a new timestamp, so they get transferred all the time.

**Comment by inferno-chromium** [comment]
Those numbered files are coming from normalizing the names of seed corpus files from a recent change (#129). These files are minimized locally, and then new files are synced in to gcs bucket. Once a day, the entire corpus on gcs is pruned and minimized at a global level. What you are seeing is some duplication caused due to previous sha1 names in seed corpus and new numbered files, but hopefully corpus pruning will remove the duplicate keeping one or the other. By tmrw, duplicate files will be removed. If you see files with any duplicate files with same content after a day or two, can you report the bucket path here and we can debug more.
