### ISSUE TITLE
Build failures on several projects (BAD BUILD: ... does not seem to be compiled with UBSan)

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#1542]
Just got emails for libpsl, libidn, wget2... is it temporary or what is wrong suddenly ?

**Comment by franziskuskiefer** [comment]
The [NSS build as well](https://oss-fuzz-build-logs.storage.googleapis.com/log-1be8eb41-3aaa-4d3c-baeb-ba2fe9200ecb.txt). It builds fine locally though.

**Comment by evverx** [comment]
It seems that something has changed and made [UBSAN_CALLS_THRESHOLD_FOR_UBSAN_BUILD](https://github.com/google/oss-fuzz/blob/7f26e2fd92b427931d15cf7e243a09e89fb3fd27/infra/base-images/base-runner/bad_build_check#L33) too high:
```sh
$ sudo docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -e SANITIZER=undefined -v /home/vagrant/oss-fuzz/build/out/systemd:/out -t gcr.io/oss-fuzz-base/base-runner
root@dcaff761dac5:/$ for FUZZER in /out/fuzz-{dhcp-server,dns-packet,journal-remote}; do echo $FUZZER $(objdump -dC $FUZZER | egrep "callq\s+[0-9a-f]+\s+<__ubsan" -c); done
/out/fuzz-dhcp-server 184
/out/fuzz-dns-packet 183
/out/fuzz-journal-remote 170
```
Is it possible to get the images used 3 days ago to check if everything is fine when the same code is built with them?

**Comment by titanous** [comment]
I'm seeing this on yajl-ruby as well.

**Comment by Dor1s** [comment]
Interesting. Thanks for reporting! Looking.

**Comment by Dor1s** [comment]
@evverx, I've downloaded the build from https://pantheon.corp.google.com/storage/browser/clusterfuzz-builds/expat?prefix=expat-undefined-20180618 and see the following numbers:

```
$ objdump -dC fuzz-dhcp-server | egrep "callq\s+[0-9a-f]+\s+<__ubsan" -c
426
$ objdump -dC fuzz-dns-packet | egrep "callq\s+[0-9a-f]+\s+<__ubsan" -c
425
$ objdump -dC fuzz-journal-remote | egrep "callq\s+[0-9a-f]+\s+<__ubsan" -c
412
```

And the same for other targets, e.g. expat was 583 and now is 343.

**Comment by Dor1s** [comment]
Aaaah, that's because of my recent change https://github.com/google/oss-fuzz/commit/63d9392e59bad3d19217997614c5fefd125b897c that removed sanitizer flags from fuzzing engines! 

libFuzzer had about 240 calls to UBSan runtime while was instrumented with it. Now, I should lower the threshold by ~250, I guess.

**Comment by Dor1s** [comment]
Just let me ensure real quick that none of the projects failed with ASan threshold being too high, and I'll deploy the patch + re-build the images.

**Comment by Dor1s** [comment]
Yeah, ASan threshold still looks good.

**Comment by Dor1s** [comment]
Deployed the fix and kicked off base-images rebuild. Will keep an eye in case any of the failures won't get closed. I apologize for the noise.

Also, I don't really like the new threshold values, will think about them as well. Maybe we can have some other check instead of the existing one. The problem is that e.g. `fuzz-journal-remote` from systemd has 170 calls to UBSan runtime when built with UBSan and 165 calls to UBSan when built with ASan. So, it's not clear what threshold value could be a safe one...

At the same time though, I can't find any other target that has less than 200 calls to UBSan runtime when built with UBSan. I was suspecting systemd might be built improperly, but that doesn't seem to be the case.

**Comment by Dor1s** [comment]
I've also kicked off the build check task, that has closed most of the bugs. Some of the bugs are still open though due to the network failures happened during the build. Re-launched the build as well.

**Comment by Dor1s** [comment]
All of the bugs are closed as of now, except of qubes-os one, which seems absolutely valid:

```
root@22a3e92945bd:/out# objdump -dC input-proxy-receiver_fuzzer | egrep "callq\s+[0-9a-f]+\s+<__ubsan" -c
166
...
root@22a3e92945bd:/src/qubes-os/app-linux-input-proxy# make -n
make -C src all
make[1]: Entering directory '/src/qubes-os/app-linux-input-proxy/src'
clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -g -Wall -Wextra -Werror -O2 -std=gnu99 -Wno-missing-braces -Wno-missing-field-initializers   -c -o input-proxy-sender.o input-proxy-sender.c
clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -g -Wall -Wextra -Werror -O2 -std=gnu99 -Wno-missing-braces -Wno-missing-field-initializers   -c -o common.o common.c
clang   input-proxy-sender.o common.o   -o input-proxy-sender
clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -g -Wall -Wextra -Werror -O2 -std=gnu99 -Wno-missing-braces -Wno-missing-field-initializers   -c -o input-proxy-receiver.o input-proxy-receiver.c
clang   input-proxy-receiver.o common.o   -o input-proxy-receiver
make[1]: Leaving directory '/src/qubes-os/app-linux-input-proxy/src'
```

I'll post a comment on the corresponding bug that it is valid.
