### ISSUE TITLE
No builds currently happening

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1560]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html indicates that it's been two days since the last builds

**Comment by inferno-chromium** [comment]
Looks like /build/oss-fuzz$ ./infra/base-images/all.sh
is failing

+ ninja install-cxx
ninja: error: '/src/llvm/projects/libcxx/include/cxx-headers', needed by 'projects/libcxx/include/CMakeFiles/install-cxx-headers', missing and no known rule to make it
The command '/bin/sh -c /root/checkout_build_install_llvm.sh' returned a non-zero code: 1

@morehouse @oliverchang - fyi.

@alex - if you have time, can you see how to fix this compile failure. otherwise, we will debug this on Monday.

**Comment by inferno-chromium** [comment]
Probably because of https://chromium.googlesource.com/chromium/src/+/3d5707168d4a32ba432ebc7df3697a6b184a81aa

**Comment by inferno-chromium** [comment]
caused during when MSan built

cmake -G "Ninja" \
      -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
      -DLLVM_USE_SANITIZER=Memory -DCMAKE_INSTALL_PREFIX=/usr/msan/ \
      -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
      -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" \
      -DCMAKE_CXX_FLAGS="-fsanitize-blacklist=$WORK/msan/blacklist.txt" \
      $SRC/llvm
ninja cxx
ninja install-cxx
rm -rf $WORK/msan

**Comment by oliverchang** [comment]
I've rolled back clang for now to unblock our builds.

**Comment by morehouse** [comment]
Landed a fix in https://reviews.llvm.org/rL335507

**Comment by inferno-chromium** [comment]
Thanks a ton @morehouse !!
