### ISSUE TITLE
Manually reassign an issue/testcase to a different fuzz target?

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1640]
Currently, some of FreeType's targets are under active development. Today, I split a few targets that had a very slow part in it; basically built a new target that chews on the slow part while the rest of the target works on the rest.

For simplicity: I split target `A` into `A1` and `A2`. Until today, `A1` and `A2` got executed within the same target, corpus, etc; from tomorrow on, `A1` and `A2` will be executed separately from each other and `A1` will keep all history with OSS-Fuzz, all reported bugs, etc. `A2` will start from scratch.

(Un)fortunately, OSS-Fuzz discovered a few (not yet fixed) issues in `A2` that will appear fixed from tomorrow on, however, in reality they are still real issues. I would love to simply reassign these issues to the new target `A2`. I know, I can add these issues to the public corpus but I would love to avoid that since the issues are not yet resolved.

Are there any options to deal with something like that? :)

**Comment by inferno-chromium** [comment]
There is "Re-upload testcase" button testcase report page. Once you new target is in, you can reupload using that new target name, give the same issue number as that testcase, and then it will get associated with the issue. older testcase will get auto-closed due to non-existent fuzz target, but new one will continue to track the fix.

**Comment by cherusker** [comment]
Bonkers, thanks 😃
