### ISSUE TITLE
Fuzzing of memory limitation and malloc fails

### ISSUE THREAD

**Issue by Pro** [google/oss-fuzz#1675]
We have extensive checking if `malloc` returned a valid memory block in our project (https://github.com/google/oss-fuzz/tree/master/projects/open62541).
In general, if a malloc fails, the method returns an error state and based on that the parent method executes a different path. It would be very nice if we also can fuzz those fail paths.

Is it somehow possible to also fuzz malloc fails, i.e. by iteratively increasing the available memory on the same corpus?

In general it would be nice if the fuzzer could do this automatically by **running the same fuzzer input with different memory size**

Another way I can think of:
Implementing a custom memory manager.
Since we are using a `#define UA_malloc(X) malloc(X)` (and UA_free correspondingly) we could change that define, use the first few bytes of the fuzzer input as memory size for the manager and count how many bytes have been allocated (on free decrease the value correspondingly). Then return NULL if we are higher than the memory size. 

Would this make sense or would it make it harder for the fuzzer to find better coverage paths?

**Comment by kcc** [comment]
We don't have a ready-to-use solution. 
We had similar requests in the past, so we'll probably implement something eventually, but no promises.  

What you probably can do, manually, is to run the fuzzer with different values of `ulimit -v`,
but only w/o asan (since asan is incompatible with `ulimit -v`

> Implementing a custom memory manager.

If you control all your calls to malloc, this might work. 

> use the first few bytes of the fuzzer input as memory size 

Yes, except that this will invalidate your existing corpus.

**Comment by Pro** [comment]
I now created a memory manager which we use to simulate limited RAM by wrapping malloc, free, realloc, and calloc usages in our code.
See: https://github.com/open62541/open62541/pull/2188

We are taking the last four bytes (32-bit number) of the fuzzer input, and these bytes represent the available memory.

With this the fuzzer can control memory limitation and is hopefully able to find more coverage for the out of memory checking paths which were not reached before.

Anyways it would be nice to have a corresponding feature directly from oss-fuzz, and I guess that will also be more performant.

**Comment by ebraminio** [comment]
Turned out we had https://github.com/harfbuzz/harfbuzz/issues/2489 https://github.com/harfbuzz/harfbuzz/issues/2493 https://github.com/harfbuzz/harfbuzz/issues/2495 https://github.com/harfbuzz/harfbuzz/issues/2501 a number of issues could be discovered by this, it would be nice this get another look as I am sure other projects can benefit from it instead making every project goes for an internal effort. Thanks!

**Comment by ebraminio** [comment]
Applied https://github.com/harfbuzz/harfbuzz/pull/2566/files for harfbuzz, maybe useful for other project also.
