### ISSUE TITLE
glib stack frames are ignored

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1685]
We have a thing we do for testcase duplication was to ignore /glib/ stack frames for crash state (uninteresting for most projects). this does not apply to glib project. need to think more in context of oss-fuzz. for glib project, all crashes have one line crash state of that fuzz_target.c file.

@pdknsk as fyi.

Our current ignore list looks like, needs rethought. I wonder what is going with llvm project.

    # File paths.
    ' base/callback',
    '/AOSP-toolchain/',
    '/bindings/ToV8.h',
    '/gcc/',
    '/glib/',
    '/glibc-',
    '/jemalloc/',
    '/libc++abi/',
    '/libc/',
    '/llvm-build/',
    '/minkernel/crts/',
    '/sanitizer_common/',
    '/vc/include/',
    '/vctools/crt/',
    '/win_toolchain/',
    'libc++/',

**Comment by pdknsk** [comment]
Thanks for the information. When I read your comment, I wasn't quite sure what the effect of this in practice, but now I've been told by the maintainers that a bug I had found locally wasn't reported. So I'm wondering if there's an ETA for this issue.

**Comment by pdknsk** [comment]
I think I understand now. Because a `fuzz_bookmark` bug may also reproduce with `fuzz_markup`, oss-fuzz only tries to report either, and stumbles for the reason you mentioned. Is that right? If so, `fuzz_markup` may need to be removed temporarily.

I'm a bit unsure of that target anyway, as `GBookMark` is basically a super-set of `GMarkup`. As the latter target parses incrementally, I thought it may reveal different bugs because of that.

**Comment by inferno-chromium** [comment]
I am removing this hack altogether, i think those stack frames should be useful in all cases.

**Comment by pdknsk** [comment]
Alright it was false alarm, the bug was reported. So there is probably no urgency here.

**Comment by inferno-chromium** [comment]
Current state is horrible, we report 1 bug per vulnerability class since only fuzz target name e.g. fuzz_bookmark.c in crash state. Fix is in production now. it should use stack frames now to deduplicate, just like everything else. /glib/ is no longer an ignore stack frame.
