### ISSUE TITLE
running out of space in $OUT ?

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#1705]
LibreOffice builds have been failing for a while with...

Step #12: cp: error writing '/workspace/out/undefined/qpwfuzzer': No space left on device

I (hopefully temporarily) trimmed down the number of fuzzers we build from to 46 to 18 and my local du for the default asan build is 8G which is below the mentioned 10G in https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md but it still seems to be running out of space. What is my size limit there ?

Since https://github.com/google/oss-fuzz/issues/1188 "we now only copy a particular fuzz target binary and their needed dependencies" I'd hoped that there was no real buildtime $OUT size limit, just individual fuzz-target limit as each is transported individually around

**Comment by Dor1s** [comment]
:(

That message (https://github.com/google/oss-fuzz/issues/1188#issuecomment-368038596) was about extracting fuzz targets when running them. Not related to the builder.

Let me see if I can do anything quick to solve that.

**Comment by Dor1s** [comment]
It's especially weird since it's happening during UBSan build, which is likely the smallest one amongst others. I suspect that we have some artifacts from the previous builds (e.g. object files) and they take too much space.

We do cleanup the out folder once the build is done: https://github.com/google/oss-fuzz/blob/master/infra/gcb/build.py#L305

So I'm wondering whether something like `make clean` in `build.sh` would help.

**Comment by caolanm** [comment]
make clean added

**Comment by Dor1s** [comment]
Looks like yesterday's build has succeeded? And I see another one running for a while already, should be finished soon.

**Comment by caolanm** [comment]
yup, looking positive

**Comment by inferno-chromium** [comment]
green build, closing.
