### ISSUE TITLE
Guidance on stats interpretation

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#1720]
AFL and libFuzzer emit stats, which are tabulated per fuzz test today. Each stat has a helpful tool tip and there are performance guides (I think for AFL). Still, I think what would be super helpful is to have a single wiki-style guide to interpreting, triaging and prioritizing the actionable steps that the stats provide in totality. Opening this issue to track. CC @Dor1s

**Comment by Dor1s** [comment]
Thanks for filing this. Looks like we should have some sort of a mailing list or another discussion forum.

In the meantime, let me CC other active users. People, please share your thoughts on what you would like to see on the fuzzer stats page.

@alex @kjlubick @caolanm @dtardon @rockdaboot @reaperhulk @catenacyber @pdknsk @rouault @nmav @titanous @kcwu @Pro @guidovranken @cherusker @LebedevRI @jfoote @dlemstra @bilboed @franziskuskiefer @minafarid @evverx 

Thanks and sorry for the spam :)

**Comment by minafarid** [comment]
Also, in the coverage report, the coloring of the covered/non-covered lines is very confusing. It is better to highlight all of the lines that are covered/non-covered/partially-covered with their colors, instead of just coloring one line.

**Comment by catenacyber** [comment]
+1 for coverage versus corpus

**Comment by rockdaboot** [comment]
Excluding files / directories from code coverage report, configurable. E.g. the coverage of gnulib files (source code library) is completely not interesting. Or code built but just for testing.

**Comment by kcwu** [comment]
Some projects have more than one fuzzer. It would be great if you could provide a combined coverage across those fuzzers. It may help the authors to know they need even more fuzzers.

**Comment by Dor1s** [comment]
Thanks a lot for your replies!

> Also, in the coverage report, the coloring of the covered/non-covered lines is very confusing. It is better to highlight all of the lines that are covered/non-covered/partially-covered with their colors, instead of just coloring one line.

@minafarid, have you tried generating coverage report locally using https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md ? It provides much better user experience. I'm close to enabling that on OSS-Fuzz and replacing sancov. For an example, you can also browse https://chromium-coverage.appspot.com/

> Excluding files / directories from code coverage report, configurable. E.g. the coverage of gnulib files (source code library) is completely not interesting. Or code built just for testing.

@rockdaboot, I've filed https://github.com/google/oss-fuzz/issues/1726 for that. Should be easy to add, as the tooling already supports this.

> Some projects have more than one fuzzer. It would be great if you could provide a combined coverage across those fuzzers. It may help the authors to know they need even more fuzzers.

@kcwu, we'll soon be providing aggregate per project coverage reports, so that will be addressed.

**Comment by cherusker** [comment]
I'm a bit late to this thread but I like a lot of what's being said already:

1. first and foremost I'd LOVE to exclude files/dirs/projects from the coverage that is being shown online. E.g. we use `libarchive` to feed multiple files to fuzzers but I don't care about their coverage. Just a quick note, kinda offtopic: cannot wait for the online cov report to come back since building the report offline takes quite while - specifically if you just quickly want to check if once specific function is finally being fuzzed (by a specific fuzzer) or not.

2. change of coverage over time is super interesting (not every day but specifically when you release a new fuzzer or introduce bigger changes).

3. some in-depth explanation of the columns in the overview would be nice since I seem to understand most of them however, I usually see somewhat different numbers offline ... that would clear some doubt that I have about them ;)

4. also nice: the date of the build that the stats are based on. Having had some issues recently with succeeding the build stage, it would be nice to quickly check if a new build/commit is already part of the stats (or not).

5. personally, `avg_exec_per_sec` could be listed way to the left. It's one of the more important stats of our fuzzers at the moment since we're dealing with some performance issues and checking this specific value gives me some idea of how the target is generally doing.

Just a few quick thoughts, I might come back to this thread if I think of something while working with the interface :)

**Comment by pdknsk** [comment]
> For an example, you can also browse https://chromium-coverage.appspot.com/

Looks very good. What I'm missing is an option to search for files or paths.

**Comment by franziskuskiefer** [comment]
> change of coverage over time is super interesting

I think this one would be very nice to have on the stats page. It's something that's pretty hard to keep track of. A small graph or a simple +/- % would be very helpful.
I'd even go further and skip the `*_cov` columns and instead have only a graph that shows both, current level and change over time.

Looking at the current stats page the `all_crashes` and `known_crashes` columns are not that interesting imho. For a stable fuzzer only the `new_crashes` column is really interesting.

An overall metric (like combined code coverage) would be great as well. That could be compared to other projects. Something like coverity does with defect density.
![image](https://user-images.githubusercontent.com/890105/44326193-297f7c00-a45b-11e8-8961-c24368bfe153.png)
