### ISSUE TITLE
Fixed issue will not get cleared

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1732]
We have this [one issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9869) that has been fixed already but OSS-Fuzz refuses to accept its fix. I have the feeling this issue gets ignored by  ClusterFuzz somehow. How should I proceed - `Re-upload testcase ☁️`?

**Comment by inferno-chromium** [comment]
[2018-08-19 07:02:02 UTC] oss-fuzz-linux-zone3-host-b7z1-15: Progression task started: r201808190655.
[2018-08-19 07:02:06 UTC] oss-fuzz-linux-zone3-host-b7z1-15: Progression task finished.

Maybe wait another day to see if the fix gets uptaken. this build was done last night, and we do builds once a day. Please close this bug if the issue is closed.

**Comment by cherusker** [comment]
I just figured out where the issue lies: [the `minimized` and the `unminimized` testcases are semantically different](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9869#c11)! While the `minimized` testcase got fixed, the `unminimized` testcase still fails. Do such differences happen regularly & should we generally add both versions to the regression corpora (I suppose)?

**Comment by inferno-chromium** [comment]
we only test with minimized testcase when determining whether a bug is fixed or not. since that is considered less flaky than original minimized testcase.

**Comment by cherusker** [comment]
Thanks for the update, I'll keep that in mind (and also update our regression suite)!
