### ISSUE TITLE
NEW_FUNC not resolved in logs

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1735]
A minor cosmetic issue. [Apparently](https://github.com/google/oss-fuzz/issues/1462#issuecomment-410749947) it affects many projects.
```
NEW_FUNC[1/1]: 0x7fcdbc7c17a0  (/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_firefox_6180546f5e5f1d75138bf6cea3784693af7a2aa9/revisions/firefox/libxul.so+0x6d2f7a0)
```
I have no idea how the machinery works, but I guess that `llvm-symbolizer` is not in `PATH`.

**Comment by inferno-chromium** [comment]
That comment is not related to this.

To explain the process:
There are 2 ways to symbolize:
1. Online - where you set LLVM_SYMBOLIZER_PATH / define external_symbolizer_path=<path to llvm-symbolizer> in ASAN_OPTIONS and set symbolize=1 in ASAN_OPTIONS.
2. Offline -  where you set symbolize=0 in ASAN_OPTIONS and then symbolize later using llvm-symbolizer. We do it this way since it allows us to control symbolization process. Also, we can symbolize custom stacks like ones from lets say a chrome debug failure crash (non-sanitizer one).

In this case, "NEW_FUNC[1/1]:" at front is not a recognized format for symbolization. Where is this coming from ? We need it in "#[0-9]+ {address} (path-to-binary+{address})" format which is analogous to what sanitizers produce. also, can you point to testcase where this is happening or log location.

**Comment by pdknsk** [comment]
> That comment is not related to this.

It's in the third paragraph.

I think there is a bit of misunderstand here though. You mean symbolizing the reports (for bugs), which is working correctly. I meant the announcements of `libFuzzer` whenever it stumbles upon new functions. Most people will either not read those logs or not care, which is why I classified it as minor cosmetic.

```
#360	NEW    cov: 1973 ft: 6982 corp: 157/165Kb lim: 4 exec/s: 0 rss: 346Mb L: 240/27135 MS: 2 ChangeASCIIInt-EraseBytes-
	NEW_FUNC[1/1]: 0x7f17067a78c0  (/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_firefox_6180546f5e5f1d75138bf6cea3784693af7a2aa9/revisions/firefox/libxul.so+0x6ccc8c0)
#362	NEW    cov: 1976 ft: 6985 corp: 158/165Kb lim: 4 exec/s: 0 rss: 348Mb L: 22/27135 MS: 2 EraseBytes-ChangeBinInt-
```

**Comment by pdknsk** [comment]
I was just curious how the fuzzer is progressing and noticed. Please close the issue if you want. If someone else also notices, they can find an explanation now.

**Comment by Dor1s** [comment]
Yeah, I think it's been added nearly a year ago and back then we agreed that we didn't need to do any special processing on ClusterFuzz side.
