### ISSUE TITLE
testing on aarch64 with qemu

### ISSUE THREAD

**Issue by sebpop** [google/oss-fuzz#1754]
I would like to start testing projects/zlib-ng on aarch64.
I was thinking that it would be possible to run the fuzzers on top of qemu-arm64.
Has somebody done that for another project?

**Comment by kcc** [comment]
We currently don't provide a way to fuzz on aarch64,
but we are looking at it, and you may be able to help.
 
Our first step, is not to run, but to build the fuzz targets for aarch64. 
I haven't tried this yet... We'll get to it, but contributions are welcome! :) 
There are two basic approaches: use the native toolchain on an aarch64 machine or use a cross compiler on x86_64. From our infra perspective it is much more desirable to use cross compilation since we may not be able to scale up the builders on aarch64 any time soon. 
Could you please try and report back? 
Ideally, this should be a flag to `infra/helper.py` to specify the target architecture. 

Once we have a build, we'll need to figure out how to run fuzz targets at scale. 
Right now I am not aware of a really good cloud service that provides fast enough aarch64 cores for reasonable price, but things change quickly. 
We have some good local aarch64 cores and I was going to fuzz something on them in ~ Sept. 
`zlib-ng` is as good as any, I can run it as a one-off experiment for a couple of weeks on a few cores.  

@morehouse FYI

We didn't look at the qemu option at all, I'm afraid it is economically impractical. Do you think otherwise? 

Just curious, why do you want to fuzz on aarch64? 
is that because you have aarch64 assembly, or C code under `#ifdef aarch64`, or you expect some logic to be different on arm (why?), or ... what?

**Comment by sebpop** [comment]
Yes, zlib-ng uses intrinsics and inline assembly which is very different from x86 to aarch64.
Let me try the cross aarch64 compilation.  I will send you a pull request.  Thanks for the guidelines!

**Comment by sebpop** [comment]
> We didn't look at the qemu option at all, I'm afraid it is economically impractical

TravisCI for zlib-ng is running aarch64 and arm validation on top of qemu. It requires the following packages `apt install qemu gcc-aarch64-linux-gnu libc-dev-arm64-cross` and after cross compile it runs programs like this: `qemu-aarch64 -L /usr/aarch64-linux-gnu  program_exe`.
I'm thinking that we could do something similar to run the fuzzers cross-compiled for aarch64.

**Comment by kcc** [comment]
What is the slowdown? fuzzing is CPU-intensive... 

BTW, are you using the fuzzed corpus in CI (as described [here](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#regression-testing))?
If so, you can get ~90% of benefit for aarch64 just from that.

**Comment by sebpop** [comment]
running on qemu is ~50x slower:
```
$ cd zlib-ng
$ export CC=aarch64-linux-gnu-gcc
$ export CHOST=aarch64-linux-gnu                                                                                                                                                                 
$ ./configure --warn --zlib-compat                                                                                                                                                               
$ make clean                                                                                                                                                                                     
$ make -j8 all
$ perf stat qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./compress_fuzzer *.*
      10105.107358      task-clock (msec)         #    1.000 CPUs utilized          
                17      context-switches          #    0.002 K/sec                  
                 1      cpu-migrations            #    0.000 K/sec                  
             2,631      page-faults               #    0.260 K/sec                  
    44,344,493,129      cycles                    #    4.388 GHz                    
   <not supported>      stalled-cycles-frontend  
   <not supported>      stalled-cycles-backend   
   105,622,765,558      instructions              #    2.38  insns per cycle        
    23,386,069,015      branches                  # 2314.282 M/sec                  
       384,746,370      branch-misses             #    1.65% of all branches        

      10.105694765 seconds time elapsed
```
```
$ cd zlib-ng
$ export CC=gcc
$ ./configure --warn --zlib-compat
$ make clean
$ make -j8 all
$ perf stat ./compress_fuzzer *.*
        214.698234      task-clock (msec)         #    0.999 CPUs utilized          
                 0      context-switches          #    0.000 K/sec                  
                 0      cpu-migrations            #    0.000 K/sec                  
             3,405      page-faults               #    0.016 M/sec                  
       935,651,509      cycles                    #    4.358 GHz                    
   <not supported>      stalled-cycles-frontend  
   <not supported>      stalled-cycles-backend   
     1,877,106,069      instructions              #    2.01  insns per cycle        
       409,003,434      branches                  # 1905.015 M/sec                  
        10,467,097      branch-misses             #    2.56% of all branches        

       0.214858553 seconds time elapsed
```

**Comment by kcc** [comment]
50x is better than I expected, but still pretty bad... It's probably going to be too expensive to run fuzzing at appropriate scale. But once we have the build part solved we may at least try.

**Comment by vielmetti** [comment]
@sebpop @kcc - If there is continued interest in testing on aarch64 on native hardware (not emulated) let me know, there are resources from the @worksonarm project that I manage.

**Comment by sebpop** [comment]
Hi @vielmetti 
I would like to see the oss-fuzzers running on native aarch64 32 and 64 bit.  I think that would have a positive impact on the open source projects with oss-fuzzers on ARM processors.
Let me know how I can help ;-)

**Comment by jonathanmetzman** [comment]
If anyone wants to contribute here, I think a writeup/walkthrough on running libFuzzer on QEMU emulating ARM would help a lot.
Then we can hookup ClusterFuzz to use this process for fuzzing and do something similar to i386 for cross compilation on the build side (though I'd be surprised if it works as well as compiling for i386 in the x64 image).

**Comment by jonathanmetzman** [comment]
I've made progress on this. tl;dr is UBSAN fuzzing can probably supported for very simple projects very easily. But I need to 
 weigh the benefits of supporting using the method I implemented, cross-compilation + QEMU.

In #4591 I was able to get cross-compilation (builds) working for some simple projects. One of the main reasons I went with cross compilation is because I don't have an ARM machine. I was hoping we could use qemu on ClusterFuzz and support fuzzing on ARM hardware Github actions through CIFuzz.

But I'm not sure I will merge #4591 
At this point cross-builds of OSS-Fuzz projects for aarch64 is more difficult than for i386 (e.g. I had linker issues building the relatively simple sqlite3 project). If I can get it to about the same level of difficulty for users without increasing maintenance burden much, I think cross-builds would be nice to have since it will be easier for users than requiring ARM hardware to use ARM.
But a big problem with cross-building is many build systems test for features by building and running binaries. 
This is a problem because QEMU and ASAN are incompatible and will probably never work together. So even if we have ARM hardware for fuzzing ASANified binaries (which we only have in CIFuzz, not ClusterFuzz at this point) cross-compilation of ASAN targets may not be worth supporting.

@kcc points out we can use memory-tagging with QEMU which will provide some of the benefits of ASAN and some additional ones as well (finding bugs in assembly code). But I'm not sure if this is worth the effort. It's probably smarter to wait until/if we have ARM hardware.

The alternative to cross-builds is publishing ARM docker images and doing compilation on ARM. This will probably "just work" much better for devs really serious about ARM (who presumably have ARM devices). But since Google Cloud doesn't offer ARM we don't have the infra to do this. And if Google Cloud did offer ARM we wouldn't need QEMU at all.

**Comment by guidovranken** [comment]
Just my two cents. Crypto and bignum libraries often have assembly language optimizations for specific architectures, like ARM and these are sometimes the source of correctness bugs (sometimes memory bugs too).

To me being able to build the OSS-Fuzz Cryptofuzz project for ARM _at all_ is much more important than doing so with sanitizers and fuzzing (coverage instrumentation).

Ideally it would be possible to enable a setting in `project.yaml` such that OSS-Fuzz compiles the project for ARM once a day, and runs it against the latest corpus, without actual fuzzing. Since the existing corpora are very rich, I'd expect most ARM-specific correctness bugs to fall out automatically from this.

I have ARM hardware so the option involving ARM Docker images would be a great alternative to have.

**Comment by kcc** [comment]
Re "QEMU and ASAN are incompatible ". 
Sorry, I was not specific enough. 
Only the user mode QEMU is affected. 
In the full system mode ASAN should work fine.
