### ISSUE TITLE
Enhancement: integration with continuous integration

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#1788]
I'm wondering to which extent oss-fuzz could be extended to be run on pull requests submitted to a project already integrated with oss-fuzz. This would be useful to off-load the burden of producing robust code from the maintainers of a project to the casual contributors who add code / technical debt to it.

**Comment by jonathanmetzman** [comment]
I like this idea, but I think it is a long way off because of the amount of work it would take to implement.
We don't even do something like this for Chrome.
Internally, we have floated the idea of a solution for targeting recently changed code, but this is not even in the planning stages yet.

Also, I think there is an inherent limitation in this idea: how do you know when you are done fuzzing patched code? The longer we fuzz, the less usable it becomes for CI. In practice I think this scheme would be useful anyway.

I'm interested in hearing what other OSS-Fuzz maintainers think and if other projects would find something 
like this useful. I personally think this is a good idea but shouldn't be a high priority for us right now.

**Comment by alex** [comment]
Do you want it to really run the fuzzer and search for new paths on PRs, or just run the existing corpus/set of crashers?

**Comment by rouault** [comment]
> Do you want it to really run the fuzzer and search for new paths on PRs, or just run the existing corpus/set of crashers?

I guess both. In my cases, it is just it is a bit frustrating to merge a PR that adds new code, and the following day oss-fuzz finds an issue in it, but the casual contributor might already have gone away. Or even if not, he doesn't directly has access to oss-fuzz not being a core contributor, so if you want him to fix the issue you have to create your own ticket with the data. So in practice, you generally have to figure out how to fix the issue yourself.

But I'm aware this is challenging to do fuzzing in a PR context. I don't have a perfect solution. I guess projects could decide the maximum amount of time they want to allow for the fuzzing of the PR.

**Comment by evverx** [comment]
It looks like https://github.com/google/oss-fuzz/issues/2006, I've just opened, is kind of related to this issue. Although the script there can't be used when PRs are opened (it takes too long to finish), it's useful if there're cron jobs run once or twice a day. This way nobody needs to wait for 3 days to find out that, for example, the build has just been broken.

I also tried a variation of that script without the docker machinery and just with ASan, which speeds up it considerably, but at the time downloading the corpora for some reason wasn't stable enough so I decided not to turn it on.

**Comment by evverx** [comment]
Just to sum up https://github.com/google/oss-fuzz/issues/2525 (which is a duplicate of this issue), it was suggested that [Try server](https://www.chromium.org/developers/testing/try-server-usage/design) could be used to run fuzz targets against corpora OSS-Fuzz accumulates.

**Comment by inferno-chromium** [comment]
https://google.github.io/oss-fuzz/getting-started/continuous-integration/
