### ISSUE TITLE
libwebp: Can't read local file only on oss-fuzz servers

### ISSUE THREAD

**Issue by YannisGuyon** [google/oss-fuzz#1819]
I recently added a new target: [fuzz_webp_enc_dec](https://github.com/google/oss-fuzz/pull/1803)
It doesn't work [when run from oss-fuzz servers](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10349).

The target aborts when it can't read a local file:
`Step #5: cannot open input file 'libwebp-test-data/grid.ppm'`

The files are copied to their folder in [`projects/libwebp/build.sh:80`](https://github.com/google/oss-fuzz/blob/master/projects/libwebp/build.sh#L80):
`cp $SRC/libwebp-test-data/*.ppm $OUT/libwebp-test-data/`
I can see in the [log](https://oss-fuzz-build-logs.storage.googleapis.com/log-5fe9b018-e701-4157-815a-74d7fefc11f5.txt) that cp is done on the correct files:
`Step #4: + cp /src/libwebp-test-data/grid.ppm /src/libwebp-test-data/lossless_color_transform.ppm /src/libwebp-test-data/peak.ppm /workspace/out/address/libwebp-test-data/`

I can execute the following without a crash on my side:
`git clone https://github.com/google/oss-fuzz.git`
`cd oss-fuzz`
`python infra/helper.py pull_images`
`python infra/helper.py build_image libwebp`
`python infra/helper.py build_fuzzers --sanitizer address libwebp`
`python infra/helper.py run_fuzzer libwebp fuzz_webp_enc_dec`
The `reproduce` command did not abort either on my machine.

I don't know how to reproduce this problem. Can you help me? Thanks.

**Comment by Dor1s** [comment]
The issue is that directory structure on fuzzing infrastructure is different from the local image provided via helper.py. Please see https://github.com/google/oss-fuzz/blob/8eeffa627f937040aaf8ba1b7d93f43f77d74fb9/docs/fuzzer_environment.md#current-working-directory

Since the files you've added are constant files, it's strongly recommended to declare them as constants arrays / strings. See https://cs.chromium.org/chromium/src/third_party/boringssl/src/fuzz/ssl_ctx_api.cc?g=0&l=32 for example.
