### ISSUE TITLE
Unable to reproduce memory leak in libpcap

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#1909]
Issue is https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10928

I have been running the following commands 
```
python infra/helper.py pull_images
python infra/helper.py build_image libpcap
python infra/helper.py build_fuzzers --sanitizer address libpcap
python infra/helper.py reproduce libpcap fuzz_filter clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816.dms
```

with `clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816.dms` the downloaded reproducer case 
What did I miss ?

@guyharris I am tagging you here as you tried to reproduce this as well

**Comment by Dor1s** [comment]
Please see issue #1899.

**Comment by guyharris** [comment]
I was only able to "reproduce" it by:

1. setting the minimum parser stack size (`YYINITDEPTH`) to a *very* low value (2), so that it was almost guaranteed to need to increase the pushdown stack;

1. using a sufficiently syntactically complicated filter that included a syntax error at the end (`(ip and tcp port 73) or (ip6 and udp port 666) and syntaxerror`);

so that it had to grow the parser stack and threw a syntax error (any error detected by the parser and code generator, rather than the optimizer, would suffice).

I also put in printfs after `YYSTACK_ALLOC` calls, reporting the addresses allocated, and before `YYSTACK_FREE` calls, reporting the addresses freed, because I wasn't trusting ASan to find the problem.
