### ISSUE TITLE
libidn2: 'python' command is missing (though python3 installed)

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#1958]
The python shebang `#!/usr/bin/python` doesn't work any more. Python3 is installed, but not linked via /usr/bin/python. There is a build error since this morning.

**Comment by rockdaboot** [comment]
I changed libdin2 upstream to check for `python` - if missing the bootstrapping falls back to a slower mechanism (using shell stuff).

So in general a working `python` command would be nice. Can't believe that libidn2 is the only project to fall over this.

**Comment by oliverchang** [comment]
I went through the other projects which are failing, but there is only 1 other project which failed because of this.

I'm not sure if making python3 default to python is correct behaviour in ubuntu 16.04 either. So to keep our base image lean (rather than say installing python2 as well), I say we install python2 in the project images that need them.
