### ISSUE TITLE
Issue 10940 link should be reopened

### ISSUE THREAD

**Issue by guyharris** [google/oss-fuzz#1969]
It was closed, but that was just because it was testing libpcap with an incorrect filter that contained an error (an "octal" number containing a non-octal digit - "08"), and I added checks to libpcap to catch that, so, instead of looping in the optimizer, it rejected the test filter.

If you replace "08" with "8", the filter is syntactically valid, and still causes an optimizer loop.  I'm not sure what the right way to get it opened - with a different test case - is.

**Comment by inferno-chromium** [comment]
You can upload modified testcase to https://oss-fuzz.com/upload-testcase, and then in next 2 days it should get auto-filed (or you can click file bug button once ClusterFuzz confirms that it reproduces, that will create a new bug). it does not make sense to open current bug since underlying testcase is no longer reproducible.
