### ISSUE TITLE
Way to download all reproducer cases from a project

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#1989]
Is there already such a way to download all reproducer cases from a project ?
Or should I click on the 22 links for capstone project ?
So, I will be able to integrate these cases for regression testing ;-)

**Comment by kcc** [comment]
If you want to use the previously-crashed inputs for regression testing, 
our recommendation is to use the entire corpus generated by fuzzing
(you can get that from the GCS bucket),
as opposed to select inputs that caused crashes in the past. 
This is going to be both stronger and simpler solution. 

Typically, once you have a crash-y input and the bug is fixed,
some form of that crash-y input ends up being in the full corpus.

**Comment by jonathanmetzman** [comment]
One way to get recent crash variants is the .testcase files in the log bucket. But they expire after two weeks or a similar amount of time.

**Comment by evverx** [comment]
> If you want to use the previously-crashed inputs for regression testing,
our recommendation is to use the entire corpus generated by fuzzing
(you can get that from the GCS bucket),
as opposed to select inputs that caused crashes in the past.

I have a weird bash script that downloads all the corpora via a patched version of `infra/helper.py`, which exposes `download_corpus`, and then bind-mounts them so that fuzzers can find them. If this is a recommended way of regression testing, maybe, it would make sense to do it via `helper.py regression <project>` natively. What do you think?

> Typically, once you have a crash-y input and the bug is fixed,
some form of that crash-y input ends up being in the full corpus.

It doesn't seem to help reviewers to be sure that commits supposedly fixing bugs really fix them, which makes CI is a little less useful than it could be.

**Comment by kcc** [comment]
Sure. Having the exact crashy inputs in reg tests is useful. 
In the code we control we try to enforce the rule that any fix must be accompanied with such an input.

**Comment by evverx** [comment]
And sorry for hijacking the issue. I'll open another issue about `helper.py regression <project>`.

**Comment by catenacyber** [comment]
> What exactly would you like to get? Only crash inputs? Or crash inputs + some metadata (e.g. bug id, bug type, anything else)?

For me, that would be only crash inputs.
But if there were inputs with metadata, I guess I will do with it to extract the inputs only

> Do you want it to be accessible manually or published anywhere, so that it could be automatically pulled in by CI or anyone who needs it?

Yes, that would be for use by a CI

@kcc thanks for the recommendation to use the entire corpus.
I will do that, but I would like to emphasize the previous crash inputs

**Comment by jonathanmetzman** [comment]
I think these days we store all testcases we reported as bugs in the corpus backup. So you should be able to do this by downloading that for each target.
