### ISSUE TITLE
incorrectly grouped crashes do not get issues filed

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#201]
Example: https://clusterfuzz-external.appspot.com/v2/testcases?q=group%3A6360473654001664

Issue 281 was filed for one of them, that was fixed, but now there are two other issues for which issues are not filed automatically (and I don't appear to have permission to create issues).

**Comment by alex** [comment]
Ok, so two issues were just filed. I guess it just takes an extra day?

**Comment by inferno-chromium** [comment]
Couple of things

1- In current scenario, if some testcases of group are fixed, then we wait extra 2 days before filing the others. 1 day is our current time interval of fixed testcases checking, so this is just to ensure we don't refile same issues again. On Chromium side, we had multiple build types which can get updated at slightly different intervals, so 2 days was best workaround. We plan to shorten that soon.
2- In this case, these should not be grouped. The bug was adding calloc in crash state (we ignore any asan frames, but this got missed), which is now removed, now crash state won't look same. Since crash state are different, new bugs were instantly filed.
3- We still need to check two things, so will keep open
a) Why you were not able to create issue ?
b) If you can remove group mapping for testcase.

**Comment by inferno-chromium** [comment]
Regarding 3), will chat with @tanin47, i know the auth issue but we need to fix at a couple of places, so will happen on Monday. After that, you can do a whole bunch of things like file issues, update existing issue, etc.

**Comment by alex** [comment]
For 3(a), next time I have a chance I'll try to create an issue and capture the exact error message.

**Comment by inferno-chromium** [comment]
I will file seperate issue for auth problem with issue creation, but this is in @tanin47 queue. This bug is fixed, closing.
