### ISSUE TITLE
CF should display the VCS revision of the fuzzer it is running 

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#205]
Simply displaying srcmap might suffice.

**Comment by inferno-chromium** [comment]
Where, which page ?

**Comment by mikea** [comment]
Anywhere. On the status page? Right now it is not clear which version CF is running at all.

**Comment by inferno-chromium** [comment]
We need to do two things. Marty, putting this in your queue, but some pieces Oliver can help with as well.

1. Merge bots and tasks page into one page, polymerise and expose it on OSS-Fuzz. probably combine ActiveTask and HeartBeat objects into BotMetadata. And in BotMetadata, we can add things like overridden fuzzer name, build revision (see revisions.getRealRevision).
2. Have some ProjectMetadata object that regularly puts things like build revision, known crash count since last day, new crash count since last day and shows on oss-fuzz homepage in project section - https://clusterfuzz-external.appspot.com/v2?noredirect=1

**Comment by inferno-chromium** [comment]
@tanin47 as fyi, since he can give the numbers of known and new crash count from his new code.

**Comment by inferno-chromium** [comment]
Putting this in Tanin's and Oliver's queue since this info will come from crash stats land and Tanin is writing all this new code.
