### ISSUE TITLE
mercurial coverage build broken because of missing /corpus/xdiff_fuzzer.zip?

### ISSUE THREAD

**Issue by durin42** [google/oss-fuzz#2076]
See https://oss-fuzz-build-logs.storage.googleapis.com/log-ecc3384e-9aad-44e4-ae67-286e8551188c.txt for example - I've gone through the reproducing steps and I can't figure out why things are sad about this zip - I don't provide a corpus for the xdiff fuzzer, and listing the GCS buckets shows some stuff, but I think this might be environmental somehow in oss-fuzz? Is there anything else I should try on my end?

**Comment by Dor1s** [comment]
Hm, that's indeed weird, I see corpus backup available in GCS. Let me try to reproduce.

**Comment by Dor1s** [comment]
Actually no, for some reason we don't have corpus backups for that fuzz target since Dec 26th. I've just copied the most recent backup manually to unblock the coverage job (also triggered it manually), but the root cause is likely that `xdiff_fuzzer` has a lot of slow units in the corpus (files that take a while to be processed by the fuzzer, but don't time out): https://oss-fuzz.com/performance-report/libFuzzer_mercurial_xdiff_fuzzer/libfuzzer_asan_mercurial/latest

So, when ClusterFuzz does corpus pruning job, it likely cannot finish minimizing the corpus for `xdiff_fuzzer` under the given time budget, and we end up without having a minimized backup.

On our end, I can try minimizing it once manually (as I suspect now the corpus grew even further, so there is no way it would get resolved automatically).

On your end, please look into those slow units, why are they happening? Is the target too slow? Maybe the inputs are too long? If the latter is the reason, could you please restrict max input length for that fuzz target? (see https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#custom-libfuzzer-options-for-clusterfuzz)

If you could improve the fuzzer, I might not even need to minimize the corpus myself, but I'll do it anyway since I have the setup ready for that.

**Comment by durin42** [comment]
Yeah, I can easily restrict the size of the input. This particular fuzzer is a diff library, so worst case performance (without looking closely) is probably quadratic on input size. Looks like the default size limit is about 1mib, so maybe I should try restricting it to 50kib, which I'd expect to be plenty to tease out enough coverage.

**Comment by durin42** [comment]
https://phab.mercurial-scm.org/D5525 is out - it looks like this is the preferred approach over setting `max_len` in an options file?

**Comment by Dor1s** [comment]
Yep, that looks great! Thanks!

**Comment by Dor1s** [comment]
Alright, my corpus backup fix has also worked out. Now the coverage job is blocked on the issue that Python sources are missing. Is in necessary for you to check them out into `/`? I think it should just work if we check it out into `$SRC` instead. I'm testing that locally right now.

**Comment by Dor1s** [comment]
I thought the following patch would fix the remaining issues:

```diff
diff --git a/projects/mercurial/Dockerfile b/projects/mercurial/Dockerfile
index 890c5237..09b52209 100644
--- a/projects/mercurial/Dockerfile
+++ b/projects/mercurial/Dockerfile
@@ -18,7 +18,7 @@ FROM gcr.io/oss-fuzz-base/base-builder
 MAINTAINER security@mercurial-scm.org
 RUN apt-get update && apt-get install -y make autoconf automake libtool \
   python-dev mercurial curl
-RUN cd / && curl https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz | tar xzf -
+RUN cd $SRC && curl https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tgz | tar xzf -
 RUN hg clone https://www.mercurial-scm.org/repo/hg mercurial
 WORKDIR mercurial
 COPY build.sh $SRC/
diff --git a/projects/mercurial/build.sh b/projects/mercurial/build.sh
index 58d0670d..28ace9a4 100755
--- a/projects/mercurial/build.sh
+++ b/projects/mercurial/build.sh
@@ -15,7 +15,7 @@
 #
 ################################################################################
 
-pushd /Python-2.7.15/
+pushd $SRC/Python-2.7.15/
 ls
 patch -p1 <<'EOF'
 Index: v2_7_unstable/Python/pymath.c
@@ -50,4 +50,5 @@ popd
 
 cd contrib/fuzz
 export PYLDFLAGS=$(echo $CFLAGS | xargs -n 1 echo | egrep -- '-fsanitize=(memory|address)')
+make clean
 make oss-fuzz
```

But apparently some of the underlying scripts rely on the `/Python-2.7.15/` path:

```
/bin/sh: 1: cd: can't cd to /Python-2.7.15/
/bin/sh: 1: ./configure: not found
Makefile:80: recipe for target '/out/sanpy/bin/python' failed
make: *** [/out/sanpy/bin/python] Error 127
Fuzzers build failed.
```

if you could fix those, I'm quite confident we'd get the coverage reports.

**Comment by durin42** [comment]
Ah, yeah we can move the Python install. I think we'll have to do it in two phases, since the Python is built as part of the `Makefile` in the hg repo, but I can whip up something. Thanks for looking at this!

**Comment by durin42** [comment]
Actually, I can do it all in a single change here. Sending a PR.
