### ISSUE TITLE
giflib coverage-build failure

### ISSUE THREAD

**Issue by viniul** [google/oss-fuzz#2087]
CC @Dor1s, @bshastry, #2062

I am currently debugging the giflib coverage build failure:
`python infra/helper.py build_fuzzers --sanitizer=coverage giflib`
which popped up shortly after the project got accepted into oss-fuzz.

When running:
`python infra/helper.py build_fuzzers --sanitizer=coverage giflib`

I get:

```

cp: cannot stat '/src/honggfuzz/hfuzz_cc/hfuzz-clang': No such file or directory
cp: cannot stat '/src/honggfuzz/hfuzz_cc/hfuzz-clang++': No such file or directory
cp: cannot stat '/src/honggfuzz/hfuzz_cc/hfuzz-g++': No such file or directory
cp: cannot stat '/src/honggfuzz/hfuzz_cc/hfuzz-gcc': No such file or directory

```
It's non-trivial for me to see where the `cp` instructions are coming from, but I suspect it comes from some internal oss-fuzz logic and not from the `build.sh` script.

Is this an issue with the giflib harness or with oss-fuzz scripts?

**Comment by Dor1s** [comment]
I don't think those error messages can cause the build to fail, those are ignored as per https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L84:

```
    # Some directories have broken symlinks (e.g. honggfuzz), ignore the errors.
    $COPY_SOURCES_CMD || true
```

Though it's not the first time I see they confuse people, I'll suppress them.

As for the giflib, the real problem is a lack of corpus backups:

```
 Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner I 
 Step #5: [/corpus/dgif_target.zip] I 
 Step #5:   End-of-central-directory signature not found.  Either this file is not I 
 Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the I 
 Step #5:   latter case the central directory and zipfile comment will be found on I 
 Step #5:   the last disk(s) of this archive. I 
 Step #5: unzip:  cannot find zipfile directory in one of /corpus/dgif_target.zip or I 
 Step #5:         /corpus/dgif_target.zip.zip, and cannot find /corpus/dgif_target.zip.ZIP, period. I 
 Finished Step #5 I 
 ERROR I 
 ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: exit status 9 I 
```

Corpus backups are created by ClusterFuzz on a daily basis. Checking the fuzzer stats for giflib, I don't see any: https://oss-fuzz.com/fuzzer-stats/by-fuzzer/date-start/2019-01-07/date-end/2019-01-13/fuzzer/libFuzzer/job/libfuzzer_asan_giflib


//CC current sheriff @jonathanmetzman and @oliverchang just in case something's wrong with the infra (the builds look good for the past 7 days)

**Comment by Dor1s** [comment]
`/manage-vms` task seems to be failing, not sure for how long, but I suspect that's why there is a similar issue in #2085.

**Comment by Dor1s** [comment]
13b6571e2bf5abdfd9767aa5e6d1620272e28828 should fix those confusing errors from `cp`.

Regarding the infra misbehavior, we'll investigate and fix it. Sorry for the inconvenience.

**Comment by Dor1s** [comment]
The coverage build succeeded and here is a report: https://storage.googleapis.com/oss-fuzz-coverage/giflib/reports/20190116/linux/report.html
