### ISSUE TITLE
Verifying stack overflow issues is unreliable

### ISSUE THREAD

**Issue by nwellnhof** [google/oss-fuzz#2130]
There are a few stack overflow issues in libxml2 that are repeatedly marked as fixed and later reported again, although the offending code hasn't been changed. I think this happens because oss-fuzz occasionally upgrades to newer compiler versions which might result in small changes to stack layout. If a function is recompiled and uses slightly less stack memory, a test case that used to overflow the stack might stop doing so.

I think this could be fixed by using a slightly smaller stack when trying to verify whether a stack overflow issue was fixed.

**Comment by Dor1s** [comment]
@nwellnhof thanks for reporting this! Your suggestion totally makes sense and it feels to me that we have discussed it some time ago with the team, but ended up deciding that such flaky edge cases aren't happening too often in order to apply more strict conditions when reproducing a crash.

There is one more downside if we do what you propose. Such change might affect other crashes. Let's say we have a buffer overflow which uses the stack quite heavily and can become a stack-overflow if we reduce the stack limit a bit. In that case we could try to apply this logic for stack- overflow crashes only, but that would make the implementation even worse.

I'm leaving this open for further discussion, but am not optimistic about us making the change (can be totally wrong though).
