### ISSUE TITLE
Question about ignoring leaks

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2143]
Hello,

If one adds `detect_leaks = 0` to a target's fuzzer options that previously was not configured so, are previously filed memory leak bugs closed? Or do they remain open and moving forward only non-memory-leak bugs are reported?

Thank you.

**Comment by inferno-chromium** [comment]
yes it will close previous bugs since it runs every open testcase with new build everyday. newer builds will have fuzz_target.options file causing it to enforce detect_leaks=0 and the bugs getting closed. in fuzzing, it is important to remove blocker bugs first. it is hard to paper over leaks as they make fuzzing very inefficient and will lead to oom quickly.
