### ISSUE TITLE
Date fuzzing began

### ISSUE THREAD

**Issue by elizabethdinella** [google/oss-fuzz#2207]
Is the sha of the program when the fuzzing began recorded anywhere? And if so, is it public? 
The meaning of SHAs in the regression range is not clear. Could you please clarify? Thanks!

**Comment by alex** [comment]
The regression range values are commit identifiers in the repo -- commit shas for git (for svn it's the counter, etc.)

**Comment by elizabethdinella** [comment]
Yes, but what do these SHAs mean in terms of when fuzzing began? Which commit is the state of the source code that the bug was found in

**Comment by alex** [comment]
Do you want the revision it was found in, or the earliest revision that OSS-Fuzz knows it reproduces in (or the most recent version it's known to reproduce in)?

The regression range is the earliest version the bug was found to reproduce in.

The last tested revision (or fixed revision) is the most recent version it's known to reproduce in.

The revision it was originally found it isn't tracked very clearly, but you can see it in the stack trace area as "original stacktrace on {revision}".

**Comment by Dor1s** [comment]
Thanks, @alex. You can also see the revision where a crash was found in the METADATA section of a testcase details page, there will be a line like:

```
[timestamp] bot-name: Fuzz task : Fuzzer fuzz_target_name generated testcase crashed in 123 seconds (rREVISION).
```

But that is indeed not super helpful, the regression range is the most important one, as it shows when the regression was introduced.

If you're curious about when OSS-Fuzz started to fuzz a particular project, you can go to the builds bucket and see all the builds, including the earliest one: e.g. for botan project it will be there: https://pantheon.corp.google.com/storage/browser/clusterfuzz-builds/botan/

**Comment by elizabethdinella** [comment]
"The regression range is the earliest version the bug was found to reproduce in."

Does this mean the bug is reproducable in every commit in the range?

**Comment by alex** [comment]
No -- oss-fuzz does not build every single commit of a repository, it builds once a day. So it knows that a crash was introduced _somewhere_ in the range, but doesn't know where, since it can't test very single commit.

**Comment by elizabethdinella** [comment]
@alex ah, okay! Thanks for the clarification!

**Comment by alex** [comment]
No problem
