### ISSUE TITLE
NULL issue?

### ISSUE THREAD

**Issue by smalyshev** [google/oss-fuzz#2244]
Got a report like this:
```
Issue 13783: php/php-fuzz-mbstring: NULL
```

Inside:
```
Crash Type: Stack-overflow
Crash Address: 0x7ffdcdd58ff8
Crash State:
  NULL
Sanitizer: address (ASAN)
```

Is it normal to get nulls in issue reports? I get that it's a stack overflow but NULLs look like a bug.

**Comment by inferno-chromium** [comment]
Yes if we don't get a stack, then we can't derive the crash state. In this case, instead of empty string, we pick NULL.

==1==ERROR: AddressSanitizer: stack-overflow on address 0x7ffdcdd58ff8 (pc 0x000000530a11 bp 0x7ffdcdd59000 sp 0x7ffdcdd59000 T0)
--
  | SCARINESS: 10 (stack-overflow)
  | <empty stack>
  | SUMMARY: AddressSanitizer: stack-overflow
  | ==1==ABORTING
