### ISSUE TITLE
oss-fuzz.com access without Google account

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2261]
Is it correct that oss-fuzz.com cannot be accessed without a Google account?

This requirement is a hurdle to using oss-fuzz for some people. One maintainer within the bignum-fuzzer project had to create a Gmail account for accessing oss-fuzz, and it appears to be problematic for LAME developers wanting access to the LAME fuzzer: https://sourceforge.net/p/lame/mailman/lame-dev/?viewmonth=201903

Having a Google account myself, I cannot test if and to which extent access to the fuzzing dashboard at oss-fuzz.com is blocked, but this is my understanding from reports from others:

- Non-Google accounts can be added to the ```project.yaml``` CC's and they will receive e-mails about crashes
- Non-Google accounts cannot download the crashing input or have access to other resources hosted on oss-fuzz.com

Can the requirement for having a Google account be lifted? If not, is there any way non-Google accounts can have access to the crashing input?

**Comment by inferno-chromium** [comment]
We don't need a google email, but need a google account to authenticate which can be associated of any existing non-google email address. oss-fuzz.com system needs access validation, so we found having a google account to be a good way to do this given that we are running on appengine. We are open to ideas to doing this without a google account and any one can look at our https://github.com/google/clusterfuzz code to propose feature/changes/PRs to do this.

**Comment by pdknsk** [comment]
If you're interested, there was a bit of discussion on a possible alternative [here](https://github.com/google/oss-fuzz/issues/1916).

**Comment by pauldreik** [comment]
Hi, a related issue and I can't really find an answer in the documentation, hence posting here. Which email address should I use to login to oss-fuzz.com?
If I use my regular google account it says
>You (email=myname@gmail.com) are not authorized to access this page!
Does the google account have to have it's primary email address equal to one of the addresses mentioned in the project.yaml file? If so, I'm stuck since it is not possible to use "-" in the mail address.
What I am trying to do is to log in and view the report I got via email. This is regarding the newly added libtorrent project: https://github.com/google/oss-fuzz/blob/master/projects/libtorrent/project.yaml
I can change the address, but I don't want to make a pull request until I know it's the right thing to do.
Thanks,
Paul

**Comment by inferno-chromium** [comment]
@pauldreik - The google account does not need to be in the primary email address. You can add the google account in the `auto_ccs:` field and leave the main one in primary as-is. You still need to submit PR for the auto_cc addition :)

**Comment by pauldreik** [comment]
Thanks for the quick reply! Unfortunately it now says:
> You (email=pauldreikossfuzz@gmail.com) are not authorized to access this page!

**Comment by inferno-chromium** [comment]
Please wait 30 min, there is a cron that runs and adds perms automatically.
