### ISSUE TITLE
Running fuzzers on non-x64 systems

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2295]
Does oss-fuzz ever run the fuzzers on non-x64 systems like ARM or 32 bit x86?

For the various differential crypto fuzzers (bignum, EC and the upcoming (hopefully) cryptofuzz) this would be useful because the underlying libraries (OpenSSL and derivatives most notably) invoke custom assembly code tailored to a specific arch (and sometimes even specific CPU flags).

If not, will you support fuzzer targets within the differential fuzzing projects compiled with ```-m32```? If it doesn't work with sanitizers, I could strip away the sanitizer flags from CFLAGS and compile with coverage instrumentation only.

If any of this is not possible, you might want to consider running the latest corpus for a fuzzer on a different arch as a periodical event (like once a day), if that is possible for you. I've tried to do this with QEMU on x64 Linux but it's very slow (it takes hours to compile OpenSSL with sanitizers on emulated MIPS for example).

In theory it is possible to implement support for other archs at the fuzzer level via [Unicorn](https://github.com/unicorn-engine/unicorn) / QEMU hackery but running on real hardware would be much nicer.

Running on other architectures might also be useful for pure C/C++ (no assembly) applications, as some might assume a certain endianness.

**Comment by jonathanmetzman** [comment]
>Does oss-fuzz ever run the fuzzers on non-x64 systems like ARM or 32 bit x86?

No, but they've been on our wishlist for a while.

>For the various differential crypto fuzzers (bignum, EC and the upcoming (hopefully) cryptofuzz) this would be useful because the underlying libraries (OpenSSL and derivatives most notably) invoke custom assembly code tailored to a specific arch (and sometimes even specific CPU flags).

It think it's also pretty useful for finding memory corruption in pure C/C++ (ie: non-ASM) code. We've started fuzzing x86 builds in Chrome and it seems to find [quite a few bugs.](https://bugs.chromium.org/p/chromium/issues/list?can=1&q=description%3Ax86_libfuzzer_chrome_asan%2Cx86_libfuzzer_chrome_asan_debug+type%3Dbug-security+-status%3Aduplicate%2Cwontfix) (most are nonpublic). It's not entirely clear which bugs could reproduce on x64 and just happened to be found by our x86 builds. But there are some clear x86-only cases. I have some guesses as to why this is (`size_t`/pointer size differences, different IR produced by clang for different archs), but most of these are just theories.

We've wanted to support x86 and ARM (see #1754) in OSS-Fuzz but haven't gotten the chance to do so yet. x86 has mostly been a lack of time. ARM is blocked on getting hardware and/or QEMU support (but is more interesting).

I think we are hoping to do x86 in the fall. But if someone made the OSS-Fuzz side changes I think it would be easy for us to support in CF (and thus OSS-Fuzz the service).
I think these changes would include:
  - Modifying the build system to produce an x86 version of libFuzzer (note that this should probably wait until #2164 and would require an LLVM patch to build x86 libFuzzer (I can do this).
  - Modifying our python scripts to build x86 ASAN builds.

I think if you created another project and you targeted x86 and linked against an x86 libFuzzer you build yourself, x86 would probably just work. But we'd probably prefer a less one-off solution.

>If any of this is not possible, you might want to consider running the latest corpus for a fuzzer on a different arch as a periodical event (like once a day), if that is possible for you.

Yeah I agree a QEMU solution this should depend on running the fuzzer on the corpus and not so much on fuzzing though maybe a small amount of fuzzing would help.

>I've tried to do this with QEMU on x64 Linux but it's very slow (it takes hours to compile OpenSSL with sanitizers on emulated MIPS for example).

Were you not cross-compiling? I think OSS-Fuzz has support for cross compiling for ARM already.

**Comment by guidovranken** [comment]
Thanks for your extensive answer.

I will see if I can contribute to those tasks for x86 support in OSS-fuzz when I have time.

Bignum and Cryptofuzz are good targets to experiment with this and I will try to enable x86 support in them.

Yeah I should cross-compile instead. I was building the entire thing in a QEMU VM but cross-compiling and only running the binary in QEMU makes much more sense, thanks.

Do you ever experiment with different optimization flags by the way? ```infra/helper.py``` always seems to compile with ```-O1```, is this the case for all builds?

There are situations where both no optimizations and high optimizations can distinctly catch bugs.

Eg. ```-O0 -fsanitize=address``` can catch:

```c
   /* Return value ignored, so -O3 optimizes this away */
   /* Assume 's' is invalid/not null terminated */
   (void)strlen(s);
```

and with (high) optimization levels you can catch funky stuff like this [buffer overflow in OpenSSH](https://marc.info/?l=openbsd-cvs&m=147508042316009&w=2):

```c
#include <stdlib.h>
#include <stdio.h>
void
mm_memvalid(void *address, size_t size)
{
    void *end = (char *)address + size;

    if (end < address) {
        printf("mm_memvalid: end < address: %p < %p\n", end, address);
    }
}

int main(int argc, char** argv)
{
    char* x = (char*)0xC0000000;
    char* endptr;
    long l;

    if ( argc < 2 ) { return 0; }

    l = strtol(argv[1], &endptr, 16);
    if ( l < 0 ) { return 0; }
    mm_memvalid(x, l);

    return 0;
}
```

```shell
$ clang -m32 mm_memvalid.c ; ./a.out 0xFFFFFFFF
mm_memvalid: end < address: 0x3fffffff < 0xc0000000
$ clang -O1 -m32 mm_memvalid.c; ./a.out 0xFFFFFFFF
$
```

(not a perfect example for my argument since the threshold here is ```-O1```, not ```-O3```, but I'd wager ```-O3``` across oss-fuzz projects will find a bunch of bugs that ```-O1``` can't catch).

I've also noticed some cases of infinite recursion that crash with ```-O0``` but not with ```-O3```.

**Comment by jonathanmetzman** [comment]
>Do you ever experiment with different optimization flags by the way? 

This has also been on my todo list. I suspect "fuzzing" the options used to build a target (including new archs) is one of the most underrated low hanging fruit for finding more bugs. 

>infra/helper.py always seems to compile with -O1, is this the case for all builds?

Yep. Even in our chrome fuzzer builds. 
Our Windows builds of chrome fuzzers is the only exception to this that I know of.
There we use `/O2`. And in that case I have seen [some bugs](https://bugs.chromium.org/p/chromium/issues/detail?id=894934#c7) that I think were revealed by the different optimization level.

We use -O1 everywhere based on the theory that it is a good balance between more program edges (thus better for cov fuzzing) and program speed (also important for cov fuzzing). I'm a bit skeptical of this though. I think tests of this theory have inconclusive results (cc @kcc who did them with @morehouse 
and should know more about bugs showing up because of different optimization levels).

>There are situations where both no optimizations and high optimizations can distinctly catch bugs.

I've wanted to experiment with this for a while. Throwing different compilation flags at a binary and shaking out more bugs seems like a nice application of one the key ideas behind fuzzing, that randomness can be used to find bugs. It probably would be a bad idea to change the optimization level  for existing jobs since it would seriously mess up regression ranges and even cause some bugs to close prematurely.

My grand idea for this was to replace our current model with one that is more integrated with the build system. Currently we upload builds to a bucket and the build system is treated like a black box.
The new model would allow CF to build at a certain commit with specific optimization flags. This model could probably find more bugs and get more precise regression ranges (ie: find the exact commit that introduced a bug). It would of course be a lot of effort to create and would probably make integration with OSS-Fuzz too hard to be worthwhile.

A more realistic alternative is having "minor" jobs that are run once or a few times per revision and only get built infrequently (ie: during daily builds oss-fuzz builds one of {a.m,ub}san/-O{0,2,3}/{x86,x64}). These will have bad regression ranges (I think this acceptable). Closing bugs will be another challenge since it may be a while before a new build is done (maybe build infra can be told to do a specific build).

**Comment by jonathanmetzman** [comment]
I've started the process of enabling x86 builds by making a patch to add support for x86 in libFuzzer:
https://reviews.llvm.org/D61070

**Comment by guidovranken** [comment]
Awesome! Looking forward to using it in my oss-fuzz projects.

**Comment by jonathanmetzman** [comment]
With https://github.com/google/oss-fuzz/pull/2347 landed local builds should work. Still need to get support for official builds and running builds on ClusterFuzz.

**Comment by evverx** [comment]
@jonathanmetzman in case you're gathering feedback, I tried to build `systemd` with `--architecture i386` and it failed with
```sh
FAILED: src/shared/libsystemd-shared-242.so ^M
clang  -o src/shared/libsystemd-shared-242.so 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev.c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev-device.c.o' 'src/shared/5af
aae1@@systemd-shared-242@sha/.._libudev_libudev-enumerate.c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev-hwdb.c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev-list.
c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev-monitor.c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._libudev_libudev-queue.c.o' 'src/shared/5afaae1@@systemd-shared-242@sha/.._li
budev_libudev-util.c.o' -L/usr/lib/clang/9.0.0/lib/linux -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libsystemd-shared-242.so -Wl,--whole-archive src/shared/libsystemd-shared-242.a src/bas
ic/libbasic.a src/basic/libbasic-gcrypt.a src/libsystemd/libsystemd_static.a src/journal/libjournal-client.a -Wl,--no-whole-archive -Wl,-z,relro -Wl,-z,now -m32 -O1 -fno-omit-frame-pointer -gline-tables-o
nly -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -shared -Wl,--version-script=/src/systemd/src/shared/libshared.sym -lrt -L/li
b64 -lcap /usr/lib/x86_64-linux-gnu/libmount.so -L/lib64 -lcap -L/lib64 -lcap -lm -Wl,--end-group -pthread -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu ^M
/usr/bin/ld: cannot find -lcap^M
/usr/lib/x86_64-linux-gnu/libmount.so: error adding symbols: File in wrong format^M
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)^M
^M[305/550] Generating load-fragment-gperf-nulstr.c with a meson_exe.py custom command.^[[K^M[306/550] Generating load-fragment-gperf.c with a custom command.^[[K^M
ninja: build stopped: subcommand failed.^M
```
I haven't looked at it closely yet (and it could be it should be fixed on the systemd side) but I hope it's kind of helpful anyway.

**Comment by jonathanmetzman** [comment]
Thanks. Where does libmount.so come from? I assume an apt package that isn't being installed for i386.
I don't expect i386 to work out of the box for all projects, just projects that don't use any binary deps in their build process. I expect that many projects will not be able to take advantage of i386 support.

**Comment by evverx** [comment]
@jonathanmetzman that's correct. `libmount` is installed via `apt-get` along with a couple of other dependencies we can't turn off at the moment (though most features relying on external code are turned off when the fuzzers are built so maybe it's possible to make libmount, libcap and so on optional as a last resort or build them manually (which we've been trying to avoid :-)).

**Comment by evverx** [comment]
@jonathanmetzman I got past `libmount` and `libcap` by turning them off (with popsicle sticks, duct tape and a little glue for) but hit `ld` complaining a lot that
```
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerUtil.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerUtilLinux.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerUtilPosix.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerCrossOver.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDataFlowTrace.o)' is incompatible with i386 output
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `append':
/usr/local/bin/../include/c++/v1/string:2547: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)'
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `__libcpp_allocate':
/usr/local/bin/../include/c++/v1/new:238: undefined reference to `operator new(unsigned long)'
```
Looks like it has something to do with `libFuzzingEngine` we still link against and I'll try to switch to `-fsanitize=fuzzer` to see how it goes but I'm wondering if it's expected.

On an unrelated note, given that in our case less code is covered by the fuzzers on i386 will there be  separate coverage reports for different architectures?

**Comment by evverx** [comment]
With `-fsanitize=fuzzer` I ran into
```
FAILED: fuzz-link-parser
clang  -o fuzz-link-parser 'fuzz-link-parser@exe/src_udev_net_fuzz-link-parser.c.o' -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -Wl,--start-group src/udev/libudev-core.a src/shared/libsystemd-shared-242.so src/udev/libudev_static.a src/udev/libudev-basic.a src/libsystemd-network/libsystemd-network.a -Wl,--end-group -fsanitize=fuzzer -pthread '-Wl,-rpath,$ORIGIN/src/udev:$ORIGIN/src/shared:$ORIGIN/src/libsystemd-network' -Wl,-rpath-link,/work/build/src/udev:/work/build/src/shared:/work/build/src/libsystemd-network
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5.4.0/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/5.4.0/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
I think I'll take a break and keep experimenting on Monday :-)

**Comment by jonathanmetzman** [comment]
>With --sanitizer=undefined, something weird happens (which I haven't figured out yet unfortunately)

AFAIK we aren't going to do UBSAN builds on i386.

**Comment by jonathanmetzman** [comment]
@guidovranken have you run fuzzers in QEMU before? I've had some trouble with sanitizers and QEMU in the past, just wanted to confirm it is possible.

**Comment by evverx** [comment]
> AFAIK we aren't going to do UBSAN builds on i386.

@jonathanmetzman I'm pretty sure even without UBSan ASan is going to be fruitful and keep everyone busy for a while :-)

Regarding that issue, looks like it was discussed back in 2013 in http://lists.llvm.org/pipermail/cfe-dev/2013-January/027633.html and apparently nothing has changed since then.

**Comment by rouault** [comment]
Any news on having oss-fuzz deal with 32 bit (i386 would be fine enough) binaries ? I've just been reported with a libtiff 32-bit specific vulnerability that someone discovered by their own means. i386 is probably of little interest by itself nowadays, but that would be a good way to uncover most issues affecting ARM 32bit as well.

**Comment by inferno-chromium** [comment]
@rouault - it should work now, @jonathanmetzman plans to document it in the next week or so. see https://github.com/google/oss-fuzz/blob/master/projects/skcms/project.yaml#L12 for example.

**Comment by rouault** [comment]
@inferno-chromium Thanks for the hint. I've submitted https://github.com/google/oss-fuzz/pull/2677 to add i386 support for GDAL. Tested locally. One issue I had, not related to oss-fuzz infrastructure, but to Ubuntu multi-arch is that if I installed for example libsqlite3-dev:i386 and libsqilte3-dev:amd64 in the Dockerfile that would fail due to a packaging issue where they both overwrite the same file. That could be overriden, but there was also confusion in GDAL build system and manually built dependency, when dev packages of the 2 architectures were installed, particularly if using pkg-config.
So I've ended up moving in build.sh the installation of {FOO}-dev:$ARCH packages to install just the set relevant to the current architecture.

**Comment by evverx** [comment]
@rouault I'm wondering whether you're planning to run regression tests in "i386" mode on Travis CI or AppVeyor. As far as I know, they don't provide real i386 VMs so it seems it should be necessary to replicate the part of "./infra/helper.py" and the underlying docker images dealing with `--architecture=i386` manually there. On the other hand, if you have a bunch of 32-bit VMs (as I do for example) you don't even need to juggle the ":i386" and ":amd64" packages because the fuzzers can be built and run in the "real" environments without any kludges.

**Comment by evverx** [comment]
Having taken a look at #2677, I've just realized that it takes more than an hour to build the fuzzers so my question about running regression tests when PRs are open obviously doesn't make sense. Sorry about that. Though I'd be interested to find out how other projects using "i386" generally handle that.

**Comment by inferno-chromium** [comment]
Sending an email to travis folks to see if we can get exception for longer timeout. With smaller projects, that limit does work since currently i386 jobs is only added for ASan. If we cant work with Travis, will need to see how we can switch to other solutions like Azure (contributions welcome!, might need to plan).

i386 builds are still generated and run on x86_64 bots, it just makes things easier to manage (32-bit vms will be too much work to bootstrap, maintenance and would need significant refactoring on clusterfuzz for job scheduling, different docker images, etc). This i386 offering is to increase coverage for OSS folks and is not intended to be the focused offering.

**Comment by evverx** [comment]
> With smaller projects, that limit does work since currently i386 jobs is only added for ASan.

Just to clarify, I didn't mean Travis CI used by the OSS-Fuzz project to make sure projects can be built with `infra/helper.py`. What I was trying to figure out is how the projects using "i386" run regression tests on their side along with their unit tests and so on.

> i386 builds are still generated and run on x86_64 bots, it just makes things easier to manage (32-bit vms will be too much work to bootstrap, maintenance and would need significant refactoring on clusterfuzz for job scheduling, different docker images, etc).

I understand the trade-offs and I generally agree if OSS-Fuzz is the only way for some projects to run their fuzzers or anything else for that matter automatically on i386 they should probably do it.

**Comment by randy408** [comment]
Will i386 be enabled for all projects or should I make a PR to enable it? libspng would benefit from it, it has overflow checks that only make sense on 32-bit.

**Comment by jonathanmetzman** [comment]
> Will i386 be enabled for all projects or should I make a PR to enable it? libspng would benefit from it, it has overflow checks that only make sense on 32-bit.

PR is definitely welcome. It definitely wont be mass-enabled for *everything* since many projects would require specific changes (like installing different deps) for this to work.
I'm tempted to enable it on every project where it just works, but I'm a bit worried some projects may be unhappy about getting i386 bugs.

**Comment by inferno-chromium** [comment]
arm is tracked in https://github.com/google/oss-fuzz/issues/1754, i386 support is there.

**Comment by jonathanmetzman** [comment]
I've added some details on progress we made on ARM in #1754.
