### ISSUE TITLE
Report sanitizer configuration in testcases & bug reports

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#233]
Testcases and issues should report the sanitizer configuration. Ideally both as:
* short name as in config (e.g. `undefined`) 
* precise flag values (flags change over time, we will eventually support custom configurations)

**Comment by inferno-chromium** [comment]
Example string "Sanitizer: address (ASAN)" will now be both on testcase report and on filed bug (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=384). 

We don't have information on build flags, i suggest we put these on wiki than in bug ? @kcc - wdyt ?

**Comment by mikea** [comment]
@inferno-chromium where does this information currently come from? Can we pass it through srcmap.json? (we can rename it into buildinfo.json).

The reason I'd like to see this hooked up all the way through is custom sanitizers configurations (e.g. for ubsan)

**Comment by inferno-chromium** [comment]
Currently memory tool name is derived from job name (hacky, but works on both clusterfuzz-internal and oss-fuzz since we follow a strict job name convention).

Reopened, lets discuss in detail in the weekly meeting. I think srcmap.json/buildinfo.json should work fine, we need to fix that for source link in stacktrace as well.
