### ISSUE TITLE
Enable undefined sanitizer by default

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#234]
@kcc @inferno-chromium do you think we want this or should we continue enabling undefined sanitizer project-by-project?

**Comment by kcc** [comment]
Hard to say. Some projects may run away screaming if we start spamming them with int overflows. 
E.g. FreeType has [lots of those](https://savannah.nongnu.org/bugs/?func=detailitem&item_id=46149). 

Is it possible to enable ubsan by default for every project, but somehow limit the number of ubsan-ish reports filed at one time per project (per target)?

**Comment by inferno-chromium** [comment]
We can enforce a limit, but it has to be manually enforced in job type (using MAX_STORED_CRASHES env variable, we were thinking to remove it, but maybe we will keep that env variable around, @tanin47 fyi). 

Given our 50 project list, it is hard to enable one by one. Our testcase deduplication algorithm will be put to good test, but we do combine similar looking stacks together. If things go out of control, we can always delete a job type. Basically lets just make sure we have a strategy to disable this per project.

**Comment by alex** [comment]
👍  on enabling it by default, it will find bugs, and individual projects can turn it off if they don't like it. More secure results should be the default :-)

**Comment by randombit** [comment]
Could there be some way of enabling some/most UBsan options on a project specific basis, or a fuzzer specific basis? I ask because Botan's BER decoder triggers `enum` conversion UBSan errors (https://github.com/randombit/botan/issues/751), but I'd take every other UBSan including signed overflow. And for that matter I'd be interested in any enum conversions happening outside of ber_dec.cpp

I am already planning on rewriting this ASN.1 sub-lib completely in the next year or so, so this is a short term problem, but I would hate to be spammed with many duplicate bugs in the mean time.

Or maybe the deduplicator will handle everything fine, it seems pretty good. I suppose the answer is turn it on and find out. :)
