### ISSUE TITLE
add s2n to OSS-Fuzz

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#238]
s2n already uses libFuzzer: https://github.com/awslabs/s2n/tree/master/tests/fuzz
so it should be pretty easy to add s2n to OSS-Fuzz. 

@raycoll, @alexw91, @colmmacc,
please check https://github.com/google/oss-fuzz if you are interested. 
We already fuzz other crypto libs (openssl, boringssl, botan, gnutls, nss) and we have cross-pollination 
of inputs between different targets -- so OSS-Fuzz has a chance to add value on top of your own fuzzing process.

**Comment by alexw91** [comment]
Sorry for the delay. I've been working off and on to get this approved from the AWS side.

Couple of Questions:
What are the format and details included in the email? Is there a specific prefix in the subject line that we can expect and monitor?

In the event of oss-fuzz finding an issue, are the step to reproduce (error lines, stack trace, input, fuzz test name, etc) included in the email sent by oss-fuzz? Or is it just a link to log in to see the details?

It seems that the `auto-ccs` parameter of the `project.yml` file requires that emails must be associated with a Google Account. If the steps to reproduce are already included in the email, it seems that there is a preference by the aws-security team to simply re-use their existing process of receiving a PGP encrypted email at aws-security@amazon.com where the key defined at [https://aws.amazon.com/security/aws-pgp-public-key/](https://aws.amazon.com/security/aws-pgp-public-key/). 

Would it be possible to relax the requirement of "must be associated with a Google Account" to "must be associated with a Google account or have a PGP key configured"?

raycoll, colmmacc, and myself would probably still set up and link our personal Google accounts so that we can log in and see all the details, but the aws-security team would like to re-use their existing process if possible so that they are still aware of ongoing issues.

**Comment by inferno-chromium** [comment]
-What are the format and details included in the email? Is there a specific prefix in the subject line that we can expect and monitor?

The email is just a notification with title like "Issue 736 in oss-fuzz: ffmpeg: Integer-overflow in get_amv" indicating crash type and top crash frame (important).

-In the event of oss-fuzz finding an issue, are the steps to reproduce (error lines, stack trace, fuzz input, fuzz test name, etc) included in the email sent by oss-fuzz? Or is it just a link to log in to see the details?

These are links like https://oss-fuzz.com/testcase?key=5580263943831552 which contain the testcase, detailed stacktrace, etc. This needed to be logged on using a google account since it is running on appeninge. 

-It seems that the auto_ccs parameter of the project.yml file requires that emails must be associated with a Google Account. If the steps to reproduce are already included in the email, it seems that there is a preference by the aws-security team to simply re-use their existing process of receiving a PGP encrypted email at aws-security@amazon.com where the key is defined at https://aws.amazon.com/security/aws-pgp-public-key/.

aws-security@amazon.com might get notification, but for logging into clusterfuzz and seeing testcase, stacktrace, it needs a google login.

**Comment by kcc** [comment]
The email notifications are more-or-less exact copies of what's in the bug tracker, you can see most of the fixed bugs [here](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status:Fixed,Verified%20Type:Bug,Bug-Security%20-component:Infra%20&sort=-id&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary)

To download the reproducer one will need to click on a link which will require authentication. 
We currently don't attach the reproducer inputs to e-mails, and we are reluctant to implement it
(extra added complexity)

**Comment by inferno-chromium** [comment]
tracked in https://github.com/google/oss-fuzz/issues/402.

@alexw91 - did you get a chance to take a look.

**Comment by alexw91** [comment]
Yes, this is something that I plan on doing in the next month or two. There's just other things that I wanted to get to first, mainly creating more Fuzz Tests for s2n (https://github.com/awslabs/s2n/issues/378) before adding s2n to OSS-Fuzz.
