### ISSUE TITLE
Optimization idea for targets that are stuck

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2437]
Just a random thought I've got (might be not innovative),

If we run a fuzz target that barely discovers any new signal (e.g. thousands of iterations are needed to reach something new), we can try to check the coverage in batches:

```
- for i in [0..N]:
  - mutate input
  - execute input
  - save input
- check the coverage
- if there is anything new:
  - reset the coverage
  - re-run those N inputs once again and save the ones that trigger something new
- dismiss all N inputs
- reset the coverage
- start again
```

Let's say N is 100 and we discover a new signal once for every 1,000 executions. That means we'd be checking the coverage 200 times instead of 1,000 for every new signal.

@kcc @jonathanmetzman WDYT?

Coverage counters might not work well with this, I guess. But I don't see any other issues. Might also marginally help with unstable coverage (e.g. if the batch gave us some signal, but none of the inputs reproduced it, we just avoid such inputs).

**Comment by jonathanmetzman** [comment]
I've thought of something like this as well but I didn't really think it provided much benefit. However, I didn't think of the instability benefits it provides, so I think for this reason it is worth considering. Another difference was I thought of doing something like binary search to find the new signal inputs for more iterations. But this is definitely easier to reason about, implement, and it definitely seems more optimal (particularly when instability is taken into account).

I guess the value of this solution depends heavily on getting N right for the signal probability. I think this equation can be solved for the optimal N:
```
Let X be execution time (avg)
Let Y be iteration time
Let Z be probability of new signal
Let A be number of executions on avg to get new signal (=1/Z)
A*X + A/N*Y + N*(X+Y) < A*(X+Y)
```

Another possible solution for the problem of large arrays is treating the coverage map like a tree. This can be done on the function level for example. So rather than iterate through the entire coverage map we can iterate through the function coverage map see which functions are covered and then iterate through the edges in that function.

**Comment by jonathanmetzman** [comment]
[This paper](https://arxiv.org/pdf/1812.11875.pdf) discusses using interrupts and binary rewriting to selectively trace through the coverage map. I haven't gotten the chance to read through it entirely, only skimmed it and saw [the talk](https://www.youtube.com/watch?v=2Rg8wtccCNA). I find it surprising though since it focuses on AFL which I thought didn't have this problem because the coverage map is a fixed size.
