### ISSUE TITLE
mechanism to manage bug disclosure ?

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#244]
The Bug Disclosure Guidelines says disclosure rules are: "90-day deadline. After notifying project authors, we will open reported issues in 90 days, or 7 days after the fix is released."

"release" in the context of oss-fuzz is the commit that fixes the problem, so 7 days after the commit is pushed to the master branch that oss-fuzz pulls from then the issue goes public. So I guess the rules are better expressed as "or 7 days after oss-fuzz detects that the issue is fixed".

Is there any mechanism to give more control over the schedule of opening reported issue to the project ? Specifically I'd like to keep the fixed libreoffice Bug-Security issues private until the fixes are backported to our stable branch and appear in the next formal release (typically every month) and open in a block at that point.

**Comment by kcc** [comment]
>  So I guess the rules are better expressed as "or 7 days after oss-fuzz detects that the issue is fixed".

Yes. Anyone objects to this change in the docs? 

> Is there any mechanism to give more control over the schedule of opening reported issue to the project

Not on our side. We are reluctant to have per-project differences in the policy.
However, with some minor inconvenience, you may do it on your side: 
* Instead of fuzzing the master, simply fuzz a special branch (change Dockerfile to get the branch code).
* push fixes to the master once you have them
* merge master into the special branch once you are ready for the bugs to become public (in 7 days)

Of course, this will require some extra work on your side and may introduce inefficiencies on ours 
(existing bugs hide other bugs)
 
And BTW, I don't really believe there is a reason to do this.
Once a patch is made public it is often obvious what was the bug it fixed (I know, this is debatable)

**Comment by kcc** [comment]
And, by the way, once the bug becomes public the buggy input still remains private.
