### ISSUE TITLE
[LPM fuzzer] How to limit proto fuzzer input size?

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2473]
Hello,

For non proto fuzzers, one can do it with a straightforward `if` condition

```
extern "C" LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
   if (size > MAX_INPUT_LEN)
       return 0;
   ...
```

But the proto fuzzer macro does not expose `size`. Can I do this instead or are there more robust ways to limit proto input size?

```
DEFINE_PROTO_FUZZER(ProtoBufMessageDef const& input)
{
    if (input.ByteSizeLong() > MAX_PROTO_INPUT_LEN)
        return;
    ...
}
```

Reference: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.ByteSizeLong.details

**Comment by jonathanmetzman** [comment]
I don't see why you couldn't do this.
Actually max_len in the `.options` file may work in this scenario because LPM fuzzers should probably not be used with AFL, though some are :-(
Another option is to be more fine grained about what to allow, if certain constructs cause perf issues, I did this [here](https://cs.chromium.org/chromium/src/testing/libfuzzer/proto/skia_image_filter_proto_converter.cc?sq=package:chromium&g=0&l=198), though using proto for this approach may be worse than fixing the targeted program.

**Comment by Dor1s** [comment]
Should we add ` if (input.ByteSizeLong() > MAX_PROTO_INPUT_LEN)` to the documentation?

**Comment by bshastry** [comment]
> Should we add if (input.ByteSizeLong() > MAX_PROTO_INPUT_LEN) to the documentation?

I vote for this proposal :-)

**Comment by bshastry** [comment]
> Another option is to be more fine grained about what to allow, if certain constructs cause perf issues, I did this here, though using proto for this approach may be worse than fixing the targeted program.

Yeah, I've been thinking the same. This is a broad generalization: Perf issues flagged by fuzzer are a problem that developers don't seem to care too much about somehow.

**Comment by jonathanmetzman** [comment]
@bshastry Could you file this issue in the LPM repo? We don't have any docs on LPM in OSS-Fuzz so I don't think it makes sense to put this here.
