### ISSUE TITLE
Add libFuzzer minimizer support

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#250]
Minimizer command line, add extra flags to current command (e.g. python  /mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/launcher.py /mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzer-testcases/fuzz-3-gnutls_pkcs7_parser_fuzzer gnutls_pkcs7_parser_fuzzer at end)

-minimize_crash=1 -max_total_time={expiry_time} -exact_artifact_path={minimized_file_path}

After minimization is done, you need to regenerate stacktrace without these flags since minimizer output is too noisy.

**Comment by mbarbella** [comment]
Sorry for the delay on this. This should mostly work now. There were some issues with test cases that started hitting timeouts during minimization, but it doesn't seem too frequent and we should still be able to handle most of these cases. Will keep an eye on it over the next few days and fix bugs or file new ones if there's anything that would have to be handled on the libFuzzer side.

**Comment by kcc** [comment]
I am also interested in seeing cases where minimization is not very successful

**Comment by inferno-chromium** [comment]
I am seeing timeout cases, e.g. with https://oss-fuzz.com/v2/testcase-detail/5718711778410496, so in those cases, we need to just fallback to using unminimized testcase as minimized version, rather than marking bug as unreproducible which will happen after keep recreating minimize task

**Comment by inferno-chromium** [comment]
Seeing issues with https://oss-fuzz.com/v2/testcase-detail/5184759229579264 as well. Need to test with more testcases before enabling globally.

**Comment by oliverchang** [comment]
We're having some issues with integrating this on CF. We have a timeout for the minimization, and expect the result in exact_artifact_prefix, but libFuzzer writes to exact_artifact_prefix only when it's no longer able to minimize any further regardless of how long many iterations it takes?

@kcc Do you think it makes sense for libFuzzer's minimization to write the current minimized file to -exact_artifact_path at end of each iteration instead of only at the very end?

**Comment by kcc** [comment]
I think this makes sense. (Not sure if I can get to it very soon though; will try)

**Comment by oliverchang** [comment]
Thanks! No rush, just wanted to make sure it's in your queue :)

**Comment by kcc** [comment]
Actually, that was pretty easy. Done.

**Comment by oliverchang** [comment]
I think we're in decent shape here now.

Looking at our logs of failures from the past couple of days,

- There was a case of indirect-leak becoming direct-leak during minimization (crash state remained the same). We mark it as failure because the crash type changed here.
- Bad testcase: https://oss-fuzz.com/v2/testcase-detail/5133955487498240 which didn't get processed properly when it was found
- gRPC which had broken build for a couple of days and didn't have the libFuzzer engine updates. This seems to be working now e.g. https://oss-fuzz.com/v2/testcase-detail/5417405008314368
- Crashes which couldn't be reproduced by libFuzzer while trying to minimize. e.g. https://oss-fuzz.com/v2/testcase-detail/5828472368791552 which was fixed already.
- OOMs (and probably timeouts) that were on the fence. This is #314

**Comment by oliverchang** [comment]
I ironed out some remaining issues with the crash param comparison, timeouts and UBSan (we needed to override external_symbolizer_path because we provided the wrong one by default). 

The remaining issues seem legitimate (or #314) or real flake. I think we can close this now and track improvements in future bugs.
