### ISSUE TITLE
New fuzzing targets aren't properly added?

### ISSUE THREAD

**Issue by alexhultman** [google/oss-fuzz#2521]
Hello,

Sorry to post but I haven't seen my coverage increase or seen any statistics from the new fuzzing target I added two days ago.

Looking in the build log of uwebsockets its easy to see that 5 targets are built:

```
Step #14: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #14: INFO: performing bad build checks for /workspace/out/memory/MockedHelloWorld.
Step #14: INFO: performing bad build checks for /workspace/out/memory/MockedEchoServer.
Step #14: INFO: performing bad build checks for /workspace/out/memory/Http.
Step #14: INFO: performing bad build checks for /workspace/out/memory/WebSocket.
Step #14: INFO: performing bad build checks for /workspace/out/memory/PerMessageDeflate.
Step #14: 5 fuzzers total, 0 seem to be broken (0%).
```

Yet the statistics only list the 4 original targets I merged in the very first PR:

```
libFuzzer_uwebsockets_Http
libFuzzer_uwebsockets_MockedHelloWorld
libFuzzer_uwebsockets_PerMessageDeflate
libFuzzer_uwebsockets_WebSocket
```

Am I being too impatient or is there something not triggering? My coverage should go way up with the new MockedEchoServer.

How can I see what fuzz targets are actually being run?

**Comment by inferno-chromium** [comment]
Since your build was created last night, then we need today's full day run to get the stats. It should be visible tomorrow on https://oss-fuzz.com/fuzzer-stats/by-fuzzer/date-start/2019-06-10/date-end/2019-06-17/fuzzer/libFuzzer/job/libfuzzer_asan_uwebsockets
To see current logs - see gsutil ls gs://uwebsockets-logs.clusterfuzz-external.appspot.com/libFuzzer_uwebsockets_MockedEchoServer/
