### ISSUE TITLE
Cryptofuzz might need more memory than 2GB

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2551]
There are currently 2 out-of-memory crashes listed at https://oss-fuzz.com/testcases?project=cryptofuzz&open=yes

I don't think these are bugs in any of the libraries but rather the byproduct of embedding and running many libraries, a large corpus and possibly sanitizer overhead.

I don't know how common Cryptofuzz OOMs are. If it is impeding progress, can we bump up the RSS limit to 3 or 4GB?

**Comment by jonathanmetzman** [comment]
>There are currently 2 out-of-memory crashes listed at https://oss-fuzz.com/testcases?project=cryptofuzz&open=yes

I only see one.

>embedding and running many libraries, 

I don't think this is an important factor since the peak rss of this fuzzer right after starting is 42 Mb according to the stacktrace.

>a large corpus and possibly sanitizer overhead.

I don't think corpus is a big factor here either since the size of the corpus right before the OOM is 4453Kb.

>I don't know how common Cryptofuzz OOMs are.

This is answered by the [stats page](https://oss-fuzz.com/fuzzer-stats/by-fuzzer/fuzzer/libFuzzer/job/libfuzzer_ubsan_cryptofuzz).

According to that page, libFuzzer_cryptofuzz_cryptofuzz-openssl is the only cryptofuzz fuzzer with a non-zero oom_percent: 1.2, meaning it OOMs on 1.2% of runs. Not great, but not terrible either. The fuzzing_time_percent of this fuzzer is 43.6, meaning it spends less than half the time it is supposed to fuzzing because it has to quit fuzzing early. That is probably because it is crashing a lot, regular_crash_percent is 62.3.

So I think fixing the non-oom crashes is more important for the fuzzer.
I don't think we can bump up the rss_limit because of machine limitations (they don't have much RAM). However, if this concerns you, maybe considered setting fork=1 for the fuzzer, since fuzzing will continue after OOM in fork mode.

**Comment by jonathanmetzman** [comment]
WDYT @guidovranken ? Anything for us to do here or fine to close?

**Comment by guidovranken** [comment]
Thank you Jonathan. We'll leave it like this for now. I'll play with it locally and see if I can detect any unreasonable allocations by any of the libraries.
