### ISSUE TITLE
Memory corruption in the fuzzer? (bug 16099 on project mpg123)

### ISSUE THREAD

**Issue by sobukus** [google/oss-fuzz#2635]
I want to draw attention to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16099 . I fail to understand how the code under test shall trigger the behaviour diagnosed there. Can we rule out a malfunction of the fuzzer there? Some externally triggered memory corruption?

It may be related that I previously already had trouble reproducing testcases with my own code.  Maybe I am understanding something wrong, but I had to read the test input at some byte offset to reproduce the parsing that I saw in the oss-fuzz test run (see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16009). Is the fuzzer also fuzzing a position in the testcase byte stream? That does not look sensible to me. The read_fuzzer / decode_fuzzer for mpg123 seem simple enough … and ASan would catch memory corruption caused there, right?

**Comment by Dor1s** [comment]
Didn't look too closely, but from a quick glance I'd bet on use of uninitialized memory. MSan should've reported it then though...

**Comment by sobukus** [comment]
The fuzzers are rather minimal … prepare temp file or just the data, give that to my lib. Any error there should be really obviously been caught early by sanitizers.

Can you confirm that the testcase data that I download is supposed to be identical to what LLVMFuzzerTestOneInput gets, with offset zero? So far, I did just reproduce using my own libmpg123-using programs (the mpg123 binary itself, usually) and GCC with the sanitizers it supports. I did not yet get into using clang at all, and also don't fancy juggling with Docker while it should be a simple manner of feeding trigger input to a parser in a reproducible manner.

So I have to wonder if the fuzzer infrastructure does something more complicated than just feeding the testcase (after messing with the data before). And of course, if there is a bug that causes corruption of the fuzzing process.

**Comment by inferno-chromium** [comment]
Let me explain you the process.

We run the fuzzer for an hour and it generates log output. if it finds a bug, it crashes and gives path to a testcase. We then try to reproduce using the testcase to get the same stack. If we succeed, we keep the testcase and show this new minimized log from the repro run. this is called a fully reproducible testcase. If we fail, we dont report the bug, we wait till we can say this happens quite a lot and frequently. in that case, since the bug never repros with the the testcase given by fuzzer, we keep the original log from fuzzing. the testcase generated by fuzzer might even be related to this unreproducible crash. so we ask to try with testcase first. if it feels unrelated, just run the fuzzer itself for an hour (without testcase) to see if you can cause this crash. otherwise for unreproducible crash, we say just ignore and wait for a reproducible testcase to come through in some time.

**Comment by sobukus** [comment]
OK, so we file this under weird glitch (say, cosmic radiation) and move on.
