### ISSUE TITLE
Question: Can we use O_TMPFILE in the fuzz targets?

### ISSUE THREAD

**Issue by nsajko** [google/oss-fuzz#2678]
I want to fuzz some C functions from https://github.com/9fans/plan9port that take a file descriptor as input instead of a pointer to a buffer.

I think the simplest way of doing that is by writing the buffer provided to LLVMFuzzerTestOneInput into a file accessed something like this: `int fd = open("/tmp", O_TMPFILE | O_RDWR | O_EXCL);` (or maybe better use `"."` instead of `"/tmp"`?) Would it be OK to do that? I do not know if oss-fuzz only fuzzes on Ubuntu (Linux) or will you suddenly start  fuzzing on some other Unixlike system, too.

**Comment by cmeister2** [comment]
In the curl fuzzer we use `socketpair`, which might be a good solution for you as well. https://github.com/curl/curl-fuzzer/blob/2d3d4983a13461cb991d5974c8db44246f05d1a8/curl_fuzzer_callback.cc#L72

**Comment by inferno-chromium** [comment]
https://google.github.io/oss-fuzz/furthur-reading/fuzzer-environment/

/tmp is the only allowed temporary file location, please remember to cleanup as otherwise thousands of mutations would fill up disk space. please don't use "." as it is build dir and we cant cleanup there (only happens when new revision comes, which is once a day).

Also, check the socketpair solution by @cmeister2 , that is more preferred. as file i/o is too slow.
