### ISSUE TITLE
Configuring run time for individual fuzz targets

### ISSUE THREAD

**Issue by asraa** [google/oss-fuzz#2684]
Envoy has a number of smaller fuzz targets that test basic utilities (hashing algorithms, buffer and string manipulation libraries) as well as larger more complex fuzz targets. Some of the former are stable and we blacklist them from fuzzing on OSS-Fuzz, but other small utility fuzzers are from third party dependencies that we'd still like to fuzz (in case there are changes to those dependencies upstream) but not put as much run time in to compared to the larger fuzzers.

Would there be a way to specify fractions of compute time to individual fuzzers in our project.yaml files? Even at a course granularity, like low, med, high. 

Thanks!

**Comment by inferno-chromium** [comment]
We don't have this level of granular controls at this time. We auto-decrease weights of fuzzers when their coverage stops growing, so smaller fuzzers that are saturated get lower weight automatically. I am filing a bug for ClusterFuzz infra code to handle this. It would be nice to automate this, rather than relying on manual stuff. Do you really prefer specifying the low/med/high manually ? We can look at program edges to know how simple or complex a target is.
