### ISSUE TITLE
Question: may we upgrade glibc in Dockerfile and how is it supposed to be done?

### ISSUE THREAD

**Issue by nsajko** [google/oss-fuzz#2711]
I want to use memfd_create for fuzzing plan9port, which requires a newer glibc than Xenial has, so locally my Docker build fails. Are we allowed to upgrade just libc, kernel, dash and a few packages to disco/cosmic/bionic from xenial, or can we maybe do a whole system upgrade to a new release?

**Comment by nsajko** [comment]
Related question: why do you guys just not upgrade to Bionic Beaver, it is an LTS just like Xenial?

**Comment by nsajko** [comment]
Related question: why is there a sad face here: https://github.com/google/oss-fuzz/issues/1271#issuecomment-379827851

**Comment by jonathanmetzman** [comment]
> I want to use memfd_create for fuzzing plan9port, which requires a newer glibc than Xenial has, so locally my Docker build fails. Are we allowed to upgrade just libc, kernel, dash and a few packages to disco/cosmic/bionic from xenial

If you can get it to build using helper.py's `build_fuzzers` and then run using `run_fuzzer` and it passes `check_build`, then it should work on OSS-Fuzz/ClusterFuzz.

>how is it supposed to be done?

I don't really know, but if you can figure it out and get it working I doubt any of us will stop you =)

>or can we maybe do a whole system upgrade to a new release?

I'd rather you didn't do this since it sorta seems wasteful to do a whole distro upgrade every day.

>Related question: why do you guys just not upgrade to Bionic Beaver, it is an LTS just like Xenial?

@oliverchang probably knows the answer to this. But I think one of the main reasons we are on Xenial is because it is the distro MSAN supports best. I suspect if you upgrade glibc msan won't work for you (not the end of the world as ASAN is far more important).

>Related question: why is there a sad face here

Don't know, maybe @Dor1s was commiserating with the contributor? I'm fine with modifying the source list. Up to you I guess unless Max has a reason why not that I missed.

**Comment by Dor1s** [comment]
Yeah, I was disappointed that building some projects is so complicated that certain very specific versions of dependencies are required and people have to find different workarounds to produce a build.

**Comment by nsajko** [comment]
Ended up using `syscall(SYS_memfd_create, ...);`

**Comment by jonathanmetzman** [comment]
Glad it worked for you
