### ISSUE TITLE
Unreproducible i386 ASAN crashes -- bug in i386 ASAN?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2746]
As you might have noticed, i386 fuzzers frequently produce unreproducible crashes.

My theory is that something goes wrong when the fuzzer runs out of memory.

Of all the fuzzers in Cryptofuzz, the only one that keeps producing these strange crashes on i386 is the OpenSSL fuzzer.
OpenSSL is also the only library with a memory leak problem, today fixed in https://github.com/openssl/openssl/commit/c1d56231ef6385b557ec72eec508e55ea26ca8b0

The flac and rapidjson fuzzers also produce these i386 crashes, and both have leak or OOM problems as well.

It could be a bug in ASAN? What do you think?

**Comment by jonathanmetzman** [comment]
Interesting theory. i386 isn't exactly the most important platform to ASAN devs so if there is a bug I'm not sure how easy it will be to get fixed.
Based on fuzzing_time_percentage from these projects, I don't think this bug is harming fuzzing, it's probably just causing soome OOMs to get misreported (as you said).

I'm not sure if we will try to solve this beyond telling CF to ignore these crashes. I don't have the cycles to look into this until next week or the week after unfortunately.

**Comment by oliverchang** [comment]
Bumping this again. Is there a regex/exclusion rule we can add to the CF side to avoid filing these? @jonathanmetzman

**Comment by guidovranken** [comment]
> Bumping this again. Is there a regex/exclusion rule we can add to the CF side to avoid filing these? @jonathanmetzman

That would really be nice, I have a [ton of crypto libraries](https://github.com/google/oss-fuzz/blob/b748536b39d76c69926536af70c13846a6a68ae6/projects/cryptofuzz/Dockerfile#L27-L55) that are not fuzzed on i386 currently, and that could really benefit from it.

**Comment by oliverchang** [comment]
@jonathanmetzman Is there a common pattern to these crashes? We can easily add them to our exclusion list if so.

**Comment by jonathanmetzman** [comment]
I can try to figure this out, but I dont know if there's a pattern.
I think it might crashing inside of malloc/asan code.
