### ISSUE TITLE
Some questions regarding the OSS Fuzz project and rewards for contributors

### ISSUE THREAD

**Issue by nsajko** [google/oss-fuzz#2855]
Firstly I would like to say that I would ask this on the https://groups.google.com/forum/#!forum/oss-fuzz-outreach mailing list, which seems like  a more appropriate place, except that I am not being accepted to that list for like a month, so I guess the list is not actually used?

Questions:

* Do rewards given by Google only apply to a single change list or pull request or commit or patch? I am hoping that more than one such patch-like thing can be the basis for a single reward, otherwise unnecessarily large pull requests would be incentivized by the rewards program (and such pull requests would also be unfeasible to get merged into a project for anyone but the maintainers of the project anyway). This question does not apply just to OSS Fuzz, but to the rest of the Google Patch Rewards, too.

* Who (what person) actually gets the OSS Fuzz integration rewards? Usually it is written that the "project" itself is rewarded, does that mean only the main maintainer gets the reward? Or does whoever actually wrote fuzz targets and integrated them with the project and oss-fuzz get rewarded? I learned of oss-fuzz after plan9port (a project I am otherwise interested in) was chosen for acception to oss-fuzz, but I am not a maintainer to any projects chosen by Google for oss-fuzz. Since I was waiting for an opportunity to contribute to plan9port anyway, I made this https://github.com/9fans/plan9port/pull/283 pull for plan9port with this  https://github.com/9fans/plan9port/pull/283/commits/01ab67afc2373ad29ad9b3ef595db2d469f84725 main commit. Those fix a lot of issues found by the sanitizers (to make the fuzzing possible and worthwhile), add fuzz targets (there were no fuzz targets previously), sort of integrate the fuzz targets into the peculiar and old plan9port build system, and also contain the ossfuzz integration (which is truly almost minimal). I am interested if I am eligible for eventually being rewarded by oss-fuzz for my work here. Further, I would like to integrate more projects chosen by Googlers into oss-fuzz, but probably only if I am eligible for the rewards. Would that be possible for, for example: openslide, ubp, basis_universal or astc-encoder; on the condition that the respective maintainers accept my patches, of course?

* Since the plan9port pull request is quite a large one and some time may pass before it gets reviewed or looked at, I would like to ask if there is some intermediate step that would be prudent to take with the view of plan9port eventually getting accepted to oss-fuzz? Maybe some of you would like to take a look at the fuzzer (target)s? If so, they are currently in PLAN9PORT_ROOT/testing/fuzzTargets , where both directories are newly added by the pull request.

**Comment by jonathanmetzman** [comment]
Really sorry for the super long delay in answering this.

> Firstly I would like to say that I would ask this on the https://groups.google.com/forum/#!forum/oss-fuzz-outreach mailing list, which seems like a more appropriate place, except that I am not being accepted to that list for like a month, so I guess the list is not actually used?

I don't really run that list, but I can't seem to find your email their. If you were saying you tried to join but couldn't, then I think that makes sense. That list is not for non-Googlers to join, it's a mailing list for contacting people who do the outreach to invite projects to OSS-Fuzz.

> 
> Questions:
> 
> * Do rewards given by Google only apply to a single change list or pull request or commit or patch? I am hoping that more than one such patch-like thing can be the basis for a single reward, otherwise unnecessarily large pull requests would be incentivized by the rewards program (and such pull requests would also be unfeasible to get merged into a project for anyone but the maintainers of the project anyway). This question does not apply just to OSS Fuzz, but to the rest of the Google Patch Rewards, too.

I don't know about the patch rewards part since I don't run that program. 
For OSS-Fuzz though it doesn't matter. We don't care if the PRs/patches are giant or split up individually. For us it's more about impact (and effort somewhat).

> * Who (what person) actually gets the OSS Fuzz integration rewards? Usually it is written that the "project" itself is rewarded, does that mean only the main maintainer gets the reward? Or does whoever actually wrote fuzz targets and integrated them with the project and oss-fuzz get rewarded? I learned of oss-fuzz after plan9port (a project I am otherwise interested in) was chosen for acception to oss-fuzz, but I am not a maintainer to any projects chosen by Google for oss-fuzz. Since I was waiting for an opportunity to contribute to plan9port anyway, I made this [9fans/plan9port#283](https://github.com/9fans/plan9port/pull/283) pull for plan9port with this  [9fans/plan9port@01ab67a]

Usually we give it to the person who wrote the fuzzers and submits the rewards request. Oftentimes this is a project maintainer but sometimes it is not.

(https://github.com/9fans/plan9port/commit/01ab67afc2373ad29ad9b3ef595db2d469f84725) main commit. Those fix a lot of issues found by the sanitizers (to make the fuzzing possible and worthwhile), add fuzz targets (there were no fuzz targets previously), sort of integrate the fuzz targets into the peculiar and old plan9port build system, and also contain the ossfuzz integration (which is truly almost minimal). I am interested if I am eligible for eventually being rewarded by oss-fuzz for my work here. Further, I would like to integrate more projects chosen by Googlers into oss-fuzz, but probably only if I am eligible for the rewards. Would that be possible for, for example: openslide, ubp, basis_universal or astc-encoder; on the condition that the respective maintainers accept my patches, of course?

Umm...I don't want to get it into whether specific projects get accepted or not in advance. Can you pick one at a time to ask us about. We have a process where we discuss projects internally and with the person proposing it to determine if it is widely used enough, critical enough etc. I don't want to DoS this process.

> * Since the plan9port pull request is quite a large one and some time may pass before it gets reviewed or looked at, I would like to ask if there is some intermediate step that would be prudent to take with the view of plan9port eventually getting accepted to oss-fuzz? Maybe some of you would like to take a look at the fuzzer (target)s? If so, they are currently in PLAN9PORT_ROOT/testing/fuzzTargets , where both directories are newly added by the pull request.

You can file an issue and ask us if we'd accept the project.
Often what people do is they will give us a PR containing only the project.yaml for a project they want to integrate. If we don't accept the project, they don't waste time integrating it.
