### ISSUE TITLE
What does "coverage failing" mean?

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#2902]
I noticed the OSS-Fuzz badge for Botan had switched to "coverage failing". But if I check the report for today

https://storage.googleapis.com/oss-fuzz-coverage/botan/reports/20190927/linux/report.html

it reports a slightly *higher* coverage than the day before

https://storage.googleapis.com/oss-fuzz-coverage/botan/reports/20190926/linux/report.html

so I don't understand what coverage failing means in this context.

**Comment by guidovranken** [comment]
@jonathanmetzman @Dor1s  I think all (?) coverage builds are failing.

@randombit OSS-Fuzz has two build procedures, one if building the fuzzers, and the other one is building binaries to measure the coverage based on the current code and corpus. Under the tab 'Coverage Builds' you can see that the Botan coverage build is failing: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

https://storage.googleapis.com/oss-fuzz-coverage/botan/reports/20190928/linux/report.html should already exist, but it doesn't because the build fails. This is most likely an OSS-Fuzz problem, not a problem with Botan.

**Comment by Dor1s** [comment]
> @jonathanmetzman @Dor1s I think all (?) coverage builds are failing.

Wow, must be my change from yesterday. Thanks for reporting, I'll revert and re-run the coverage job run now, while we have only 1 consequent failure.

**Comment by randombit** [comment]
Thanks @guidovranken for pointing me to the coverage build log, I had missed that tab.

And thank you @Dor1s for fast resolution.

**Comment by Dor1s** [comment]
Coverage builds started to recover now. Thanks again for reporting this.

@guidovranken is right, the badge "coverage | failing" means that coverage build is broken.

Leaving this issue open for @jonathanmetzman in case he can think of any better wording / help message for this badge. Feel free to close.

**Comment by Dor1s** [comment]
Re-opening to figure out a better wording. I'm proposing `coverage | breakage`

**Comment by Dor1s** [comment]
"failing" appears to be a common convention when describing a build status, so we're leaving the current wording for now, but thanks for the feedback! If any more people get confused, we'll revisit this.
