### ISSUE TITLE
Question: cooperating fuzzers

### ISSUE THREAD

**Issue by pauldreik** [google/oss-fuzz#2916]
Hi!

I have written a custom mutator for the existing curl fuzzers. I wonder if there is any way to let an existing fuzzer and the new custom mutator variant share the same corpus?
When I fuzz locally, I let the two variants work on the same output dir, so they can share their results with each other. 
Just adding it next to the old one, will make for duplicated efforts and duplicated bugs reported.

Paul

**Comment by jonathanmetzman** [comment]
We don't have any way to consistently do this automatically.
Corpus pollination might make this randomly happen but I would expect this to be pretty rare.

**Comment by pauldreik** [comment]
Perhaps it would be possible to let the user organize the fuzzers into groups, which are meant to share corpus?

Corpus pollination sounds interesting, could you please elaborate on it? How does it work, who does it and when?

**Comment by MarcoFalke** [comment]
> Corpus pollination sounds interesting, could you please elaborate on it? How does it work, who does it and when?

According to the previous reply, OSS-Fuzz might do this randomly.

If you want to do this yourself, you can manually copy inputs from one target to the other. If you only want to pick inputs that increase coverage/features, you can use libFuzzer with the `-merge=1` option to copy inputs from one folder to another.

See also https://github.com/google/fuzzing/blob/master/docs/glossary.md#cross-pollination

**Comment by jonathanmetzman** [comment]
>Corpus pollination sounds interesting, could you please elaborate on it? How does it work, who does it and when?

Ha sorry for the extremely late reply. Basically ClusterFuzz when pruning a corpus will randomly pick another fuzzer's corpus (the 90-day old public backup corpus really) and add it to the one being pruned. In most cases I assume the effect will be slightly slowing down pruning since it's done randomly.
We've discussed adding some component that learns which corpora to use for pollination and allowing users to specify manually but I don't think this will be added for a while since neither is such a priority.
