### ISSUE TITLE
CI integration guidelines

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2937]
Hello,

Do you have any guidelines for incorporating fuzzing in CI? I am mostly thinking about how to download the latest corpora from oss-fuzz without authentication in a CI environment or how other people do it right now.

Thank you.

**Comment by evverx** [comment]
> how to download the latest corpora from oss-fuzz without authentication in a CI environment

Unless I'm mistaken, this would make the disclosure policy OSS-Fuzz enforces with Monorail less useful because anybody could download the latest corpora containing testcases for bugs that have been fixed but haven't been made public yet and run the fuzzers against them to see what pops up.

> how other people do it right now

The systemd project uses three different fuzzing services (including OSS-Fuzz) one of which makes it relatively easy to integrate fuzzing into the "pull requests" workflow: https://fuzzit.dev/2019/06/20/continuous-fuzzing-systemd-case-study/ but I believe it would be great if OSS-Fuzz could somehow catch up with other fuzzing services as we discussed in https://github.com/google/oss-fuzz/issues/2858#issuecomment-533358109.

I'd also like to point out that this topic appears to have come up somewhat often lately (which I hope could help to prioritize it). My understanding that it's not implemented because the chromium workflow is different and this kind of testing isn't particularly helpful there but it seems most of the projects integrated into OSS-Fuzz are different from Chromium :-)

**Comment by jonathanmetzman** [comment]
Duplicate of #1788
As @evverx I'm still working on this (as mentioned in #2858). I can't say exactly when it will be ready but I'm hoping you won't have to wait too long.

> > how to download the latest corpora from oss-fuzz without authentication in a CI environment
> 
> Unless I'm mistaken, this would make the disclosure policy OSS-Fuzz enforces with Monorail less useful because anybody could download the latest corpora containing testcases for bugs that have been fixed but haven't been made public yet and run the fuzzers against them to see what pops up.
> 

Right, we're planning a way of working around this issue.

> > how other people do it right now
> 
> The systemd project uses three different fuzzing services (including OSS-Fuzz) one of which makes it relatively easy to integrate fuzzing into the "pull requests" workflow: https://fuzzit.dev/2019/06/20/continuous-fuzzing-systemd-case-study/ but I believe it would be great if OSS-Fuzz could somehow catch up with other fuzzing services as we discussed in [#2858 (comment)](https://github.com/google/oss-fuzz/issues/2858#issuecomment-533358109).
> 
> I'd also like to point out that this topic appears to have come up somewhat often lately (which I hope could help to prioritize it). My understanding that it's not implemented because the chromium workflow is different and this kind of testing isn't particularly helpful there but it seems most of the projects integrated into OSS-Fuzz are different from Chromium :-)

This is something I'm incrementally working on, I have a proof of concept already but the reason we haven't released anything yet is because we want it to be painless to use since a flaky/slow/etc. CI check will be very unpleasant. We're also trying to make sure it will require little to no configuration from existing OSS-Fuzz projects to use.

**Comment by evverx** [comment]
That's definitely great news! Thank you!

I'm not sure if it helps but if it was possible to couple the automatic discovery of fuzz targets (which is already implemented by looking at what is in $OUT/ as far as I know) with fuzzing them for some time (as opposed to just running against the corpora that have been accumulated so far) (possibly taking into account testcases included in PRs mostly to make sure the PRs really fix the bugs they are supposed to fix by merging the "global" and "local" corpora) it would make the integration as smooth as it could possibly be especially when new fuzz targets are added. That would have made my life much easier in, for example, https://github.com/systemd/systemd/pull/13357#issuecomment-522764839 :-)
