### ISSUE TITLE
Automatically file bug reports from oss-fuzz

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#2985]
Hi all,

Do you know a way to put the oss-fuzz reports into another (project-specific) bug tracker ?
Should we parse the emails ? Is there an API ?
Has any project already done something similar ?

Cheers,

cc @nickclifton asking for binutils project http://sourceware.org/bugzilla/

**Comment by inferno-chromium** [comment]
There is monorail api you can try at
https://chromium.googlesource.com/infra/infra/+/master/appengine/monorail/doc/api.md
Can't remember a project that can done this automatically. We can't file directly in a particular tracker since we want people to access in one place in our tracker, also we can't program / manually do creds, etc for other trackers.

**Comment by jonathanmetzman** [comment]
I'm not sure the API is open to the public

**Comment by rockdaboot** [comment]
@inferno-chromium Is there a way to use `gsutil` to download all issues e.g. as JSON file ? Similar to downloading all the corpora.

**Comment by inferno-chromium** [comment]
@rockdaboot - not currently through monorail, but can explain the feature request here or a new bug, and we can see how we can prioritize this. Is this an important feature for you ?

**Comment by rockdaboot** [comment]
@inferno-chromium Please see #3027

**Comment by jonathanmetzman** [comment]
Let's consolidate requests for API: #3925
