### ISSUE TITLE
osquery coverage build is failing, saying the zipfile is corrupted

### ISSUE THREAD

**Issue by tomrittervg** [google/oss-fuzz#3001]
The osquery coverage build is failing with the following error:

```
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/osqueryfuzz-sqlquery.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/osqueryfuzz-sqlquery.zip or
Step #5:         /corpus/osqueryfuzz-sqlquery.zip.zip, and cannot find /corpus/osqueryfuzz-sqlquery.zip.ZIP, period.
Finished Step #5
```

I don't understand why this might happen - the zipfile is made with `zip -j` like other projects I've seen. [Source](https://github.com/tomrittervg/osquery/blob/master/tools/harnesses/osqueryfuzz_sqlquery_corpus.sh#L100)

I reproduced the coverage build and confirmed the zipfile is a regular zipfile and extracts fine.

**Comment by Dor1s** [comment]
Looks like the latest coverage job succeeded:https://storage.googleapis.com/oss-fuzz-coverage/osquery/reports/20191102/linux/report.html

From the error it seems like you've added a new fuzz target (or renamed an existing one), that's why the minimized corpus archive didn't exist for some time (up to 24hrs). Usually, the job will recover silently (as we don't file a bug for a broken build until we hit two failures in a row), but this might've been an unlucky case (could be another breakages in one of the two times, or even some flakiness on the build bot), that's how the bug got filed and created the confusion. Sorry about that.
