### ISSUE TITLE
32-bit UBSAN builds?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#3002]
👋 

One of the most common reasons for a buffer overflow to exist on 32-bit, but not 64-bit, is an integer overflow. Therefore it'd be helpful to have 32-bit UBSAN builds.

I don't think it'd be necessary for these to be always running, it'd be enough for them to be available for a) manual uploads, b) showing up in the "TESTCASE ANALYSIS ON OTHER JOBS" section.

**Comment by jonathanmetzman** [comment]
>I don't think it'd be necessary for these to be always running, it'd be enough for them to be available for a) manual uploads, b) showing up in the "TESTCASE ANALYSIS ON OTHER JOBS" section.

I don't think this would be so easy to support with our current infra. We'd also have to waste cycles building 32 bit ubsan daily to do this.

I've been thinking (just an idea, no concrete plans) about experimenting with a wildcard job/build that would just cycle through builds that might have unique bugs but would probably not be worth building daily, such as this, or different optimization levels, etc. The job wouldn't have regression ranges and closing issues would be slower than normal, but I like the idea of "fuzzing" build configs to shake out obscure bugs.

**Comment by jonathanmetzman** [comment]
Another thing we might be able to do to sort of support this is turn on the UBSAN checks for integer overflows in the 32 bit ASAN builds but this might cause more trouble than it is worth.

**Comment by inferno-chromium** [comment]
Need to think more on scaling the build process to account for more configs and more customizability. Not high-priority right now, but we have this in mind.

**Comment by evverx** [comment]
> I don't think this would be so easy to support with our current infra

@jonathanmetzman I'm wondering what else apart from the issue mentioned in https://github.com/google/oss-fuzz/issues/2295#issuecomment-495009702 can get in the way?

> Need to think more on scaling the build process to account for more configs and more customizability.

@inferno-chromium at some point (I guess after a lot of new projects had been added and the 32-bit mode had been introduced) it started to look like OSS-Fuzz kind of reached some limit in terms of its capability to fuzz continuously. For example, it keeps missing issues like https://github.com/systemd/systemd/issues/13938 (which was found by continuous fuzzing using only 1 CPU 24 hours a day as opposed to about 3.3 hours the statistics tab on oss-fuzz.com says). I'm wondering if maybe it would be possible to scale what is currently available first before trying to cover more configs.

**Comment by oliverchang** [comment]
> at some point (I guess after a lot of new projects had been added and the 32-bit mode had been introduced) it started to look like OSS-Fuzz kind of reached some limit in terms of its capability to fuzz continuously. For example, it keeps missing issues like systemd/systemd#13938 (which was found by continuous fuzzing using only 1 CPU 24 hours a day as opposed to about 3.3 hours the statistics tab on oss-fuzz.com says). I'm wondering if maybe it would be possible to scale what is currently available first before trying to cover more configs.

Thanks for bringing up this issue. I've upped the CPU weighting for systemd so you should see an increase in fuzzing time there.

In any case this FR doesn't suggest running these new builds continuously, and I agree that we shouldn't be doing that.

**Comment by evverx** [comment]
@oliverchang thank you!

> In any case this FR doesn't suggest running these new builds continuously, and I agree that we shouldn't be doing that.

I think it would make it harder (for me at least) to tag a new release (assuming issues discovered by UBsan on i386 are important enough) because I wouldn't know how long I would have to wait to be more or less sure the code was fuzzed enough to catch most shallow issues. My understanding is that `systemd` is not the only project using this "wait and hope for the best" strategy. For example, according to https://github.com/google/oss-fuzz/pull/2996#issuecomment-548470110
> Usually, we are working directly on develop and keep the fuzzer running a little before making a release.

**Comment by evverx** [comment]
@oliverchang I've just taken a look at the statistics once more and it appears the fuzzer mentioned in https://github.com/systemd/systemd/issues/13938 has been running for almost 23 hours (which is great. Thank you again!). On the other hand, according to https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-09-30&date_end=2019-11-05&fuzzer=libFuzzer_systemd_fuzz-netdev-parser&job=libfuzzer_asan_systemd&project=systemd, that fuzzer stopped on October 27 and hasn't been active since then (it's also probably worth mentioning the 2-6 day gaps in October). So it appears my "wait and hope for the best approach" was based on the wrong assumption (that by waiting for, say, 5 days (depending on the projects and changes made), I can be sure the code has been fuzzed for at least 5 days (using at least 1CPU)). If in general OSS-Fuzz isn't supposed to fuzz continuously, it of course wouldn't make sense to treat issues discovered by UBsan on i386 differently so I'm going to take my last comment back :-)

**Comment by jonathanmetzman** [comment]
I don't think we will have time to do this.
