### ISSUE TITLE
opening & closing timeout/OOMs for libxml2_xml_regexp_compile_fuzzer

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#314]
CF keeps opening and closing timeout and OOM bugs for libxml2_xml_regexp_compile_fuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=libxml2_xml_regexp_compile_fuzzer&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids

I suspect that this is because there are cases that trigger both OOM and timeout and CF 
considers that if something OOM-ed it did not timeout (and vise versa).

**Comment by kcc** [comment]
similar problem appears with just timeouts (we may open, close, then reopen) timeout bugs
if they are on the fence. E.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=491#c1

**Comment by Dor1s** [comment]
In Chromium we've simply disabled that fuzzer until the bugs get fixed. Sadly, it has been done a while ago, but bugs are still live.

**Comment by inferno-chromium** [comment]
Max, can you take a look at this. There are many timeout bugs that get marked as fixed and later recreated, like ffmpeg and libreoffice targets. Can you please discuss fix this on ClusterFuzz end (discuss fix with Oliver).

**Comment by Dor1s** [comment]
Hm, I looked at those testcases and it seems there is no bug on CF side. These are valid timeouts that take about ~25 seconds on our bots. e.g. libass_fuzzer:
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=462
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=491
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=513

Time spent on my desktop (ms):
* 15455
* 16995
* 15381
* 15058
* 15150
* 15776

Assuming that I use `-timeout=16` locally I can either reproduce this or not reproduce. Since CPU on bots is not that good as on my desktop, they process such units in about 25 seconds.

Other than that, it might be unintended fixes or other flakiness in a target itself. For example, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=797 takes 2ms on fresh revision, but on revision used on 10th of March `wmffuzzer` really hangs on this input:
* Executed ./797 in 55814 ms
* Executed ./797 in 55706 ms


To address the first issue, we may use a smaller `-timeout=` value when we're trying to reproduce the testcase. Though it doesn't seem to be a good solution to me. Maybe we should move in the opposite direction: increase `-timeout` value? I believe that bigger timeout limit would lead to more reliable reproducers (e.g. infinite loops or something). As for slow units ( > 10 seconds but less than `-timeout`), we can report them separately when performance analysis shows that a target suffers from them.

@oliverchang what do you think?

**Comment by Dor1s** [comment]
To be more precise regarding reports based on performance analysis results: we cannot do it right now, but  I'm planning to implement it soon, once I switch the analysis to use BigQuery for better flexibility.

**Comment by Dor1s** [comment]
I've took another look at the following issues (randomly selected):

1) [OOM 976](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=976)
It doesn't reproduce on a ToT, but does reproduce on the revision when the bug has been found.

2) [Timeout 969](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=969)
The same.

3) [Timeout 955](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=955)
The same.


I still believe that flaky timeouts / OOMs are either actually valid issues or some edge cases like an example in https://github.com/google/oss-fuzz/issues/314#issuecomment-288512567.

**Comment by oliverchang** [comment]
Sorry, completely missed your earlier replies.

Reducing timeout when we're doing fixed testing actually sounds OK to me. Even if we increase the timeout and report slow units via performance analyzer, it's not very clear that it would help in all cases and the flakiness issue will still be there if they're on the fence right?

To address the issue of timeouts becoming OOMs and vice versa, maybe we can add some logic to consider these 2 the same for the purposes of fixed testing.

**Comment by inferno-chromium** [comment]
Please prioritize debugging this more and fixing, i see a ton of timeouts testcases across projects closed every day which hurts our metrics.

**Comment by Dor1s** [comment]
I'm looking into this.

**Comment by Dor1s** [comment]
Manually going through recently closed issues:
* [1205](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1205), dlplibs: looks valid, it does timeout on the affected build and does not on the ToT
* [1200](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1200), wireshark: valid
* [1195](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1195), dlplibs: valid


Going further...

**Comment by Dor1s** [comment]
Well, I have the following hypothesis. Since we are using ToT revision and many projects may not have a proper CI / testing infrastructure, it feels that quite often some buggy code goes into the master branch, but then it gets fixed / removed pretty quickly as well. This is just an assumption, but I'll try to find some evidence.

**Comment by Dor1s** [comment]
Looks like I've got at least one interesting case, it's for issue [1205](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1205)

There are ~5 CLs in a range between bug found and bug fixed. One of the CLs look suspicious: https://gerrit.libreoffice.org/gitweb?p=libzmf.git;a=blobdiff;f=src/lib/libzmf_utils.cpp;h=b11fff17188a5968221fd0ba4d7ae7c019379d8e;hp=00d86e6991d684b38e32cf6f64383705b09645ae;hb=cc1e8888f14e4c7bc6c46b18b8e458e25176b6b0;hpb=0dac28e590c2cefacf6a5a7186eaa51470f4bc11

It removes the code with two `while` loops doing some stuff with `double` values which (I guess) can be very small or even zeros. Running the fuzzer on `0dac28e` (before that CL):

```bash
root@5436f73622b9:/src/issues# /out/zmffuzzer -timeout=10 -print_final_stats=1 ./1205 
INFO: Seed: 3589548081
INFO: Loaded 1 modules (9398 guards): [0x2286b40, 0x228fe18), 
/out/zmffuzzer: Running 1 inputs 1 time(s) each.
Running: ./1205
ALARM: working on the last Unit for 11 seconds
       and the timeout value is 10 (use -timeout=N to change)
==80101== ERROR: libFuzzer: timeout after 11 seconds
    #0 0x4e5d43 in __sanitizer_print_stack_trace /src/llvm/projects/compiler-rt/lib/asan/asan_stack.cc:38
    #1 0x635fd2 in fuzzer::Fuzzer::AlarmCallback() /src/libfuzzer/FuzzerLoop.cpp:234:7
    #2 0x7f5a2860338f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
    #3 0x6789df  (/out/zmffuzzer+0x6789df)
    #4 0x57194c in libzmf::normalizeAngle(double) /src/libzmf/src/lib/libzmf_utils.cpp:292:3
    #5 0x571822 in libzmf::rad2deg(double) /src/libzmf/src/lib/libzmf_utils.cpp:268:10
    #6 0x567a51 in libzmf::(anonymous namespace)::FillWriter::operator()(libzmf::Gradient const&) /src/libzmf/src/lib/ZMFCollector.cpp:263:39
 <...>
```

Running the fuzzer on `cc1e888` (after that CL) does not produce a timeout.


However, the CL references another bug ([1195](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1195)) which has the same root cause. We don't see it since both issues [1195](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1195) and [1205](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1205) have been found using UBSan build and not ASan, i.e. we had no stacktrace.

Also, I don't think that we compare stacktraces of timeout crashes anyway. All of these leads us to the following issues:
1) different fuzzers may find timeout bugs with the same root cause (especially big projects, e.g. a bug in a single library can be triggered from different places)
2) we don't compare stacktraces for timeout bugs
3) even if we did 2, we have no stacktraces for timeouts found on UBSan builds

**Comment by Dor1s** [comment]
It seems that it won't be hard to implement `__sanitizer_print_stack_trace` in UBSan, I'll give it a shot. Other sanitizes already have this function (https://github.com/llvm-mirror/compiler-rt/search?utf8=%E2%9C%93&q=__sanitizer_print_stack_trace&type=). Having that in UBSan as well would allow us to compare stacktraces for different Timeout crashes and treat them in a generic way (as we do for other crashes except of OOMs).

**Comment by Dor1s** [comment]
Should be something like this: https://reviews.llvm.org/D32542

**Comment by Dor1s** [comment]
As discussed offline, I'm splitting this into the following bugs:
* #552 stack trace comparison for timeouts
* #553 deduplication for OOMs
* #554 potential race condition between RssLimitCallback and singe testcase execution
* #555 flaky timeouts with execution time close to `-timeout=` threshold


And closing this issue used for investigation.
