### ISSUE TITLE
Questions about ASAN_OPTIONS and corpus stats

### ISSUE THREAD

**Issue by thuanpv** [google/oss-fuzz#3215]
Hello,

I have some questions while experiencing Oss-Fuzz with the WavPack project.

First, the log files of libFuzzer instances show quite a lot of warning like this

` "==16==WARNING: AddressSanitizer failed to allocate 0xffffffffaa59aaa9 bytes" `

and I want to fix the allocation sites leading to these warnings. In order to do that, I want to force libFuzzer to crash instead of just showing the warning so that I can get the concrete input triggering the issue for debugging and fixing. The sanitizer option "allocator_may_return_null" seems to be designed for this purpose. According to this document (https://github.com/google/sanitizers/wiki/SanitizerCommonFlags), it states that "If false, the allocator will crash instead of returning 0 on out-of-memory". However, even though I have tried to clear the option by adding "allocator_may_return_null = 0" to fuzzer.options or by adding "ASAN_OPTIONS=allocator_may_return_null=0" into the build.sh, none of them works; I still get the warnings instead of expected crashes. It would be great if someone could give me a comment/suggestion on this. Maybe I should clear the option somewhere else?

Second, for the two most recent fuzzing runs (on Jan 8 and Jan 9), the dashboard shows an empty corpus (Corpus size = 0 B). What does this mean? Does this mean the corpus merging and minimization failed?

Thanks,

Thuan

**Comment by kcc** [comment]
Hi Thuan. 
fuzzer.options can not be used to set ASAN_OPTIONS. 
Similarly, setting ASAN_OPTIONS in build.sh will only affect what's happening during the build, 
not during fuzzing. 

infra/base-images/base-runner/Dockerfile sets `allocator_may_return_null=1` by default and you can't easily override it. 

Your best bet is to run fuzzing locally, w/o setting allocator_may_return_null=1. 
This error is most likely caused by an integer overflow leading to a negative malloc size value. 

I'll let others look into the empty corpus issue.

**Comment by thuanpv** [comment]
Hi Kostya,

Thanks for your explanation and suggestion. I will try to follow that.

Regarding the empty corpus size, it seems that the issue has been fixed. I see the non-empty data in the most recent runs so I close this issue.
