### ISSUE TITLE
xvid coverage build fails -- unzip error

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3224]
```
Step #5: [/corpus/fuzzer-decoder.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzzer-decoder.zip or
Step #5:         /corpus/fuzzer-decoder.zip.zip, and cannot find /corpus/fuzzer-decoder.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzzer-decoder. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

Since this project does not include a seed corpus, I think this is a bug on your side.

**Comment by Dor1s** [comment]
Seed corpus is not involved here, the error message mentions corpus backup: "This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully."

Looks like last time when corpus pruning task succeeded for this project was in early October (see the corpus size stats: https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-09-01&date_end=2020-01-12&fuzzer=libFuzzer_xvid_fuzzer-decoder&job=libfuzzer_asan_xvid&project=xvid)

**Comment by guidovranken** [comment]
Right. I've only now began to receive an e-mail from OSS-Fuzz about this.

What do we do about it?

**Comment by Dor1s** [comment]
It actually broke only three days ago. Do you happen to know if there were any new fuzz targets added?

**Comment by guidovranken** [comment]
No new targets added, and the xvid repository was last updated 2 weeks ago: http://websvn.xvid.org/cvs/viewvc.cgi/trunk/xvidcore/?view=log

**Comment by Dor1s** [comment]
Hm, the corpus backup bucket is empty `gs://xvid-backup.clusterfuzz-external.appspot.com`. Looks like the latest backup would've been ~103 days old today, and so it was deleted 3 days ago as per bucket lifecycle policy:

```
$ gsutil lifecycle get gs://xvid-backup.clusterfuzz-external.appspot.com
{"rule": [{"action": {"type": "Delete"}, "condition": {"age": 100}}]}
```

which means something is wrong with the target as it cannot successfully finish corpus pruning task for 100+ days in a row.

**Comment by guidovranken** [comment]
The problem still exists. I don't know what to do about it?

**Comment by Dor1s** [comment]
The corpus backup bucket is still empty, which means corpus pruning has never succeeded in the past 100+ and +21 days now.

I see that the fuzz target is quite slow. Could that be improved? Did you try minimizing the corpus locally?
