### ISSUE TITLE
Sanitizer minimized should not remove UBSAN_OPTIONS=silence_unsigned_overflow=1

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3227]
We use UBSan's unsigned-integer-overflow check in order to obtain additional feedback for a fuzzing engine (https://github.com/google/oss-fuzz/issues/910). Since the vast majority of projects are not interested in unsigned integer overflows (and it's not a UB), we silence any errors it detects by using `UBSAN_OPTIONS=silence_unsigned_overflow=1` on both fuzzing bots and OSS-Fuzz provided docker images.

However, when people try to reproduce UBSan crashes locally, sometimes they hit an unsigned integer overflow error and get confused, e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19679

This results in people disabling that extra instrumentation we've intentionally added, e.g. https://github.com/google/oss-fuzz/pull/3178 //cc @catenacyber @amodra

I'm not sure if documenting this will be sufficient, but that would be at least something to inform users better.

**Comment by catenacyber** [comment]
Well, the problem seemed to be that if the same stack trace contains both an unsigned integer overflow, and another real UBSAN bug (such as undefined shift), then fixing the latter did not close the issue (because of the former ?..)

That is what happened in  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19679 (see the history)
As I understand, the crash reproduced on clusterfuzz (not especially locally)

Am I getting correctly what happened ?

**Comment by Dor1s** [comment]
Oooh, I see where it's coming from... @inferno-chromium Looks like sanitizer flags minimizer has removed `silence_unsigned_overflow=1`, and it worked well to reproduce the actual bug. But once the bug was fixed, the lack of `silence_unsigned_overflow=1` made it look like there is an unsigned integer overflow failure, and that did not let CF to verify the bug fix.

Let me upload a patch to discuss.

**Comment by Dor1s** [comment]
Should be fixed by https://github.com/google/clusterfuzz/pull/1331. Thanks @catenacyber for bringing this up to our attention!
