### ISSUE TITLE
Missing logs from NSS with UBSan

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#337]
Looks like we don't have logs since 25th of January.

https://pantheon.corp.google.com/storage/browser/nss-logs.clusterfuzz-external.appspot.com/libFuzzer_nss_asn1_bmpstring_fuzzer/libfuzzer_ubsan_nss/?project=clusterfuzz-external&organizationId=433637338589

https://pantheon.corp.google.com/storage/browser/nss-logs.clusterfuzz-external.appspot.com/libFuzzer_nss_asn1_objectid_fuzzer/libfuzzer_ubsan_nss/?project=clusterfuzz-external&organizationId=433637338589

**Comment by Dor1s** [comment]
I wonder if that's related to 71b6b10. Though I see UBSan builds on Jenkins. //cc @ttaubert @mikea @inferno-chromium

**Comment by inferno-chromium** [comment]
Yes those fuzzers are gone, and new ones are added. Also, we will now run logs analysis and corpus pruning jobs for active fuzzers in last 1 day, so that takes care of this. I think fuzzer stats does over 7 days, so it will be fixed tmrw. right now if you slide forward the date by one day, it works

https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-fuzzer/2017-01-27/2017-02-01/fuzzer/libFuzzer/job/libfuzzer_ubsan_nss
