### ISSUE TITLE
What does "quarantine" in the ClusterFuzz UI exactly mean?

### ISSUE THREAD

**Issue by ttaubert** [google/oss-fuzz#342]
Hey, we're rather new to OSS-Fuzz/CF and wondered what exactly the quarantine column in the fuzzers table is, and why 3 of our 4 fuzzers have varying amounts of data held in there.

**Comment by Dor1s** [comment]
Good question! :) There is a short explanation if you put your mouse over the column name:
```
Size of quarantine (corpus for bad units).
```

Sometimes, _bad units_ appear in the corpus. Those are crash inputs, timeouts, OOMs, etc. If we leave such inputs in the corpus, the fuzzer won't really work, as it would be crashing when reading the corpus on every run. To avoid that, we remove _bad units_ from the corpus and put them to _quarantine_. Later, we try to restore inputs from the quarantine if they do not break the fuzzer anymore.

**Comment by ttaubert** [comment]
So, that means we should regularly take a look at the quarantined units and check them manually to see what's happening here, right?

How can we get access to those? The link in the CF UI that leads to the Google Cloud Platform tells me that I "[...] don't have permissions to perform the action on the selected resource".

**Comment by Dor1s** [comment]
I would say that fixing existing bugs is enough to avoid having units in the quarantine. If those quarantine units would generate unique crashes, they would get filed as separate bugs. Otherwise, they are just invariants of already known issues.

Lack of an access to them seems to be intended, but maybe we should change it. @inferno-chromium @oliverchang what do you think? I agree that it's not cool to show a link on the stats page, but don't give an access.

**Comment by inferno-chromium** [comment]
Well library developers should have access to both corpus and quarantine buckets. @oliverchang - this looks like a bug.

**Comment by oliverchang** [comment]
Hmm, we don't have per-project quarantine buckets. We can create per-project quarantine buckets, I'm not sure how useful this would actually be for people since we should be filing bugs for the issues in there.

**Comment by Dor1s** [comment]
Can we remove link from quarantine column to avoid confusion? Testcases in
there are duplicates of known bugs, so they are useless, imho.

--
Max
sent from phone

On Feb 2, 2017 6:23 PM, "Oliver Chang" <notifications@github.com> wrote:

Hmm, we don't have per-project quarantine buckets. We can create
per-project quarantine buckets, I'm not sure how useful this would actually
be for people since we should be filing bugs for the issues in there.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/google/oss-fuzz/issues/342#issuecomment-277022785>, or mute
the thread

**Comment by oliverchang** [comment]
Now that I think about it, is this column useful at all to devs? (we have quite a lot of columns, removing some might be nice).

Might be useful to us for debugging purposes, but I imagine if there's an issue with a lot of testcases being in the quarantine there would be plenty of other indicators (unstable builds, lots of bugs filed, very little number of actual corpus files etc)

**Comment by Dor1s** [comment]
I agree with you. It might be useful for admins, but does not make sense for projects maintainers...

**Comment by inferno-chromium** [comment]
Yes sure, we can get rid of this column.

**Comment by inferno-chromium** [comment]
The column is now removed.
