### ISSUE TITLE
[CIFuzz]: Improve likelihood of rediscovering crash on same PR

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#3420]
Similar to #3413 but a bit different (though the best solution for that issue probably fixes this).
I'm concerned that if CIFuzz finds a bug in a PR and someone tries fixing it, CIFuzz can turn green because it happens to not find the bug again, not because the bug is fixed, basically giving a false sense of security.
If CIFuzz had a way of downloading old crashes it could ensure that it won't turn green until the crash no longer reproduces. Leo suggested https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows but I don't love this because it seems fragile and is GitHub specific.

**Comment by inferno-chromium** [comment]
Feels like super minor enhancement, simplicity of not having it might be better.

**Comment by inferno-chromium** [comment]
@jonathanmetzman - is this really an issue, i see a hardcoded seed used on every run. confirmed in code (https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/fuzz_target.py#L37) and on ciffuzz run
http://cifuzz.appspot.com/run/zstd/163715660 (2020-07-09T20:05:17.0455140Z 2020-07-09 20:05:17,044 - root - INFO - Running command: docker run --rm --privileged --volumes-from b7f469aa98ff -e OUT=/github/workspace/out -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive gcr.io/oss-fuzz-base/base-runner bash -c run_fuzzer dictionary_stream_round_trip -seed=1337 -len_control=0 -max_total_time=46 /github/workspace/out/backup_corpus/dictionary_stream_round_trip). if not an issue, please close, otherwise, please tell what is needed to be done here.

**Comment by inferno-chromium** [comment]
maybe hardcoded seed is not enough since mutations can be different.

**Comment by jonathanmetzman** [comment]
>but I don't love this because it seems fragile and is GitHub specific.

The fragility is probably not a blocker, better to have this feature and fails sometimes than not have it all IMO. It probably isn't that fragile either.

>maybe hardcoded seed is not enough since mutations can be different.

It may not be enough because:
1. If a target changes between commits (and it almost certainly will), the determinism can get thrown out the window once the changed code is hit.
2. Fuzz targets could have actual nondeterminism, causing determinism done by the seed to get thrown out the window.
Less common possibilities:
3. CIFuzz downloads the latest public corpus so if a PR is open for more than day later runs might not start from the same corpus.
4. CIFuzz uses the latest clang/builder image, so if this changes during a PR we might not get the same determinism (libFuzzer itself could change, in addition to the compiled code changing).

It's probably worth exploring if this actually happens in practice though as I suspect it doesn't. I would guess in most cases CIFuzz will find the same bugs again as it is supposed to find shallow bugs.

Also, if we did this, we could get rid of the fixed seed which may mean we find more bugs.
I think it's not good if we find a bug on one commit in a PR but not on a later one. 
It might be good to find a bug on later commits in a PR that CIFuzz didn't find in earlier commits even though the bug was present there. It may cause some developer confusing by leading them to think the bug was introduced by the difference between the earlier and later commit, but that may be outweighed by benefit of finding more bugs. Need to think on this more.
