### ISSUE TITLE
[CIFuzz] Should we ignore timeouts and OOMs?

### ISSUE THREAD

**Issue by Leo-Neat** [google/oss-fuzz#3432]
@jonathanmetzman  and @Dor1s brought up the issue that CIFuzz should properly handle cases where a fuzz target is hung on a test case or runs into an OOM.

**Comment by Dor1s** [comment]
After more thinking and discussing, I kinda changed my mind and decided that we should report timeouts and OOM from CIFuzz. We can use more conservative limits (compared to OSS-Fuzz ones), but sill better let the developers know about it.

If we agree on that, we still should have an option to ignore those if the user prefers.

**Comment by jonathanmetzman** [comment]
probably needs some in person discussion because I don't think reporting timeouts/ooms is a good idea.

**Comment by Leo-Neat** [comment]
@jonathanmetzman Let me know if you have any good ideas or refrence on how to handle these cases.

**Comment by jonathanmetzman** [comment]
@evverx I saw you mentioned this in the PR but could you explain how it influenced your decision to use/not use CIFuzz. The question here is whether or not to report timeout and OOMs (my opinion is no). Do you feel strongly one way or another?

**Comment by jonathanmetzman** [comment]
It seems like we are also detecting leaks now (I saw this in OpenSSL I believe) and that wasn't supposed to be the case.

**Comment by evverx** [comment]
> @evverx I saw you mentioned this in the PR but could you explain how it influenced your decision to use/not use CIFuzz. The question here is whether or not to report timeout and OOMs (my opinion is no).

As far as I can remember, at the time I ran into a few infinite loops that were ignored because the CIFuzz jobs just timed out without reporting anything. I'm not sure how often this happens in general though.

> It seems like we are also detecting leaks now (I saw this in OpenSSL I believe) and that wasn't supposed to be the case.

I think it's great that CIFuzz can detect memory leaks. If this isn't desirable for some reason, I think it would be better to make this configurable (and catch them by default)

**Comment by jonathanmetzman** [comment]
> > @evverx I saw you mentioned this in the PR but could you explain how it influenced your decision to use/not use CIFuzz. The question here is whether or not to report timeout and OOMs (my opinion is no).
> 
> As far as I can remember, at the time I ran into a few infinite loops that were ignored because the CIFuzz jobs just timed out without reporting anything. I'm not sure how often this happens in general though.

Thanks for mentioning this, that sounds like it's a bug.

> 
> > It seems like we are also detecting leaks now (I saw this in OpenSSL I believe) and that wasn't supposed to be the case.
> 
> I think it's great that CIFuzz can detect memory leaks. If this isn't desirable for some reason, I think it would be better to make this configurable (and catch them by default)

Hmm...you're probably right. Initially when I designed CIFuzz I said we wouldn't report leaks because of performance!!!1! since `-detect_leaks=1` causes libFuzzer to rerun a lot of inputs to check for memory leaks. But I need to see if we actually get a lot more coverage by not doing this. Making leaks/timeouts/OOMs configurable is a good idea if we turn them off and is probably easy.
