### ISSUE TITLE
Coverage seems low since November

### ISSUE THREAD

**Issue by lpereira** [google/oss-fuzz#3499]
Hi --

After #3169, it seems that the fuzzing for Lwan never recovered.  (At least from my limited view of the situation.)

One of the fuzzers (request_fuzzer) does not seem to be generating any kind of coverage information, despite having a non-zero number in the tests_executable column.  The coverage used to be around 20%, but now it's not even available.

Coverage for other tests seem to be quite low, too.

I can't seem to select older dates from the date pickers to see historical figures, and look at old coverage reports. (Those are really nice to guide where the fuzzer might need help to reach.)

I also haven't received any crash notification for a while; I see that there are some unconfirmed/flaky cases in the "current crashes" sections, and the build seems to be green, so I'm not sure if this is because the fuzzers were not able to find new crashes or if it's related to the behavior described above.

Cheers,

**Comment by Dor1s** [comment]
Can you access https://oss-fuzz.com/testcases?open=yes&project=lwan ? There seem to be some unreproducible crashes. What's likely happening is that those crashes occur during fuzzing / consequent execution of testcases and that also breaks corpus pruning task. Because of the corpus pruning task being broken, there are no new corpus backups (needed for the stats and for the coverage) and the old backups got deleted after ~90 days.

**Comment by lpereira** [comment]
Thanks! I will take a look at what's happening.   Closing this issue for now as I don't know when I'll have the time to investigate those issues (which look quite odd).
