### ISSUE TITLE
The presubmit script enforces checks in unmodified parts of modified files

### ISSUE THREAD

**Issue by gilles-peskine-arm** [google/oss-fuzz#3557]
[`./infra/presubmit.py`](https://github.com/google/oss-fuzz/blob/0584ab45df8918df22c878dd9e9ebb98bda57316/infra/presubmit.py) (called from [Travis](https://github.com/google/oss-fuzz/blob/0584ab45df8918df22c878dd9e9ebb98bda57316/.travis.yml)) checks changed files only. However some of the checks fail on existing files. So a pull request may fail the CI if it happens to modify an existing file that doesn't pass the checks, even if the PR is unrelated to what is being checked.

Example: https://github.com/google/oss-fuzz/pull/3556 fails CI because [`projects/bignum-fuzzer/build.sh`](https://github.com/google/oss-fuzz/blob/0584ab45df8918df22c878dd9e9ebb98bda57316/projects/bignum-fuzzer/build.sh) is missing a license header. But that is a preexisting issue which is unrelated to the PR, and as a new contributor to the project I don't think I have any business messing with license headers in existing files.

I think all existing files should be fixed before enforcing a check.

**Comment by Dor1s** [comment]
> I think all existing files should be fixed before enforcing a check.

This is a totally fair point, but unfortunately we've added CI when the project was too large and fixing all files didn't seem reasonable for us to do. Moreover, files in project directories are essentially owned by people who work on those projects, not by OSS-Fuzz team. Because of that, the existing presubmit failures are being fixed in a lazy mode.

You aren't obliged to fix errors reported in the code you didn't modify, although that is generally a good style to leave things in a better state than you've found them.

//cc @jonathanmetzman to double check that there are no plans to lint and fix all the files in the repo. Please re-open if there are!
