### ISSUE TITLE
Build status for h2o

### ISSUE THREAD

**Issue by jfoote** [google/oss-fuzz#361]
Hello,

We've gotten a ubsan report for h2o and I see some coverage/stats on the internal dashboard, but the build doesn't appear on [the public status page](https://oss-fuzz-build-logs.storage.googleapis.com/status.html). I looked at what I think is the [latest build log](https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/h2o/latest.txt) and it appears an error occurred early in setting up the build environment. 

Is there anything we need to fix on our end? I'm looking forward to improving/expanding the integration but wanted to make sure we don't have any problems with the baseline version.

Thanks,
Jon

**Comment by inferno-chromium** [comment]
So, i do see latest builds created and used for fuzzing for both asan and ubsan configs. I think jenkins builder might not be liking the ton of logging from these fuzzers. Can you try disabling the logging spam, that might fix this (either disable that error message (recommended) or use close_fd_mask in .options file (not recommended since it disable all logging and we might not catch assertions, etc).

skipping frame (type:255)
....
....

**Comment by oliverchang** [comment]
it's a bug in the jenkins library we're using to generate these build log -- it expects utf-8 in the console output. i'll see if we can work around it.
