### ISSUE TITLE
Open issue when a coverage run fails/crashes

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#3851]
I have a fuzz target in Qt that calls the function QTextDocument().setMarkdown(). You can see in the links below that the call is covered. What's strange is that since April 13th the coverage numbers for the called code are at 0, see links below.
I don't see any change on our side that could have caused this. Might there be something wrong in the coverage numbers or do you have any advice for me on how to research this issue?

Before:
https://storage.googleapis.com/oss-fuzz-coverage/qt/reports/20200412/linux/src/qt/qtbase/tests/libfuzzer/gui/text/qtextdocument/setmarkdown/main.cpp.html
https://storage.googleapis.com/oss-fuzz-coverage/qt/reports/20200412/linux/src/qt/qtbase/src/gui/text/qtextdocument.cpp.html (line 3423)

After:
https://storage.googleapis.com/oss-fuzz-coverage/qt/reports/20200413/linux/src/qt/qtbase/tests/libfuzzer/gui/text/qtextdocument/setmarkdown/main.cpp.html
https://storage.googleapis.com/oss-fuzz-coverage/qt/reports/20200413/linux/src/qt/qtbase/src/gui/text/qtextdocument.cpp.html (line 3423)

**Comment by inferno-chromium** [comment]
Maybe check the corpus locally using infra/helper.py coverage command. Also, good to check fuzzer stats page to see if corpus size changed significantly or something around those dates. Were any new crashes filed around the dates, maybe those could be affecting corpus merge ?

**Comment by rlohning** [comment]
Hi,
thank you for your help and sorry for not replying for so long. I had to find the time to get to this again.

When I run "infra/helper.py coverage" locally, the coverage looks as expected in both cases: With the the downloaded corpus (default) as well as with a local one (--corpus-dir).

I don't understand yet how the corpus size or created crashes might make a difference in this case. It's a direct function call from the fuzz target's entry function (LLVMFuzzerTestOneInput) and the coverage report claims that function call was run 25.8k times. It also claims, though, that the called function's body was not even run once. Would you like to explain what I'm missing?

Nevertheless, I checked: At the said day, a flaky Null-dereference READ was found:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23112
That happens in the dtor of a static object, so after executing this function. Could that mess up the coverage data that badly?

**Comment by inferno-chromium** [comment]
Our code coverage expert @Dor1s is OOO and will be back late June, he can provide some debugging pointers when he is back.

**Comment by rlohning** [comment]
Now that the [flaky Null-dereference READ](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23112) is fixed, the coverage data looks right again, so my problem is solved. Thank you for your support.

My guess is that the coverage build crashed when recording the coverage for the affected test. Would it be feasible to notify users about such situations, e.g. open a separate issue for crashed coverage runs like for failed coverage builds? At least to me, it wasn't obvious that the coverage will be faulty due to that issue.

**Comment by Dor1s** [comment]
> That happens in the dtor of a static object, so after executing this function. Could that mess up the coverage data that badly?

yes, that sounds right. The coverage report generation tries to be as crash resistant as possible by leveraging libFuzzer's `-merge=1` option, but anyway the target program can mess things up and lose some parts of the coverage data if it crashes badly even on the minimized corpus backup.

I think the main point here is that "fuzz targets should not crash when running minimized corpus backup". It might not make much sense to report failures like this on our end just because:
A) if it's a real regression in the target program, a regular bug will be reported by ClusterFuzz anyway -- no need to duplicate it
B) if it's a flaky unstable crash, it's going to be hard to reproduce it and verify the fix automatically

Instead, I'd strongly encourage users to enable CIFuzz (https://google.github.io/oss-fuzz/getting-started/continuous-integration/) which leverages corpus backups and intends to shake out easy-to-find bugs in CI, even before a regression is committed to the repo.
