### ISSUE TITLE
zbar barcode scanner integration

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3863]
http://zbar.sourceforge.net/

This project is apparently dead but the code is probably used in a lot of software/devices.
Someone forked it: https://github.com/mchehab/zbar but at least Ubuntu still uses the sourceforge one as upstream.

I have a fuzzer + corpus ready and it's finding bugs.

Questions:

- Is this eligible for integration?
- Do you prefer the fork or the original, or both?
- Who should receive the bug reports. Maybe major Linux distribution maintainers?

**Comment by inferno-chromium** [comment]
Is the fork used in other places ?
We don't want to use the fork if it is not used. And if we can't update / fix bugs in main zbar library, that is also not good. This is a hard case, have you tried talking to @mchenhab or any of linux distro maintainers if they are ok with receiving and fixing reports. OSS-Fuzz integration needs to be maintained, so that would be a requirement from our side.

**Comment by guidovranken** [comment]
Thank you @inferno-chromium . I've decided not to follow through with this. I've asked around, but I'd end up dedicating more time forwarding bug reports and asking for fixes than writing the fuzzers. Closing this.
