### ISSUE TITLE
[S2OPC] Pending issue that seems fixed

### ISSUE THREAD

**Issue by brameret** [google/oss-fuzz#3936]
Hi,

The monorail issue [20853](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20853) stays "New" but it should not. We re-uploaded the testcase [here](https://oss-fuzz.com/testcase-detail/5754783565873152), and the log states "No crash occurred.".

The same problem happens with issue [20864](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20864) ([reproducer](https://oss-fuzz.com/testcase-detail/5701443125510144))

What can we do to mark these issues "Verified" ?

Thanks,

**Comment by inferno-chromium** [comment]
Fixed testing on stack overflow / oom cases can be flaky
You can see at end of testcase report page
```
[2020-03-03 16:41:27 UTC] oss-fuzz-linux-zone3-host-rwdc-7: Progression task started: r202002180429.
[2020-03-03 16:41:42 UTC] oss-fuzz-linux-zone3-host-rwdc-7: Progression task finished: Fixed testing errored out (min and max revisions are both 202002180429)
```
So, ClusterFuzz got confused since bisect failed. When stuff fails, we dont close bugs. I just closed it. I explicitly closed it. If this happens on more bugs, feel free to point us and we can investigate more.

**Comment by brameret** [comment]
Thanks for your help!
