### ISSUE TITLE
fix vptr vs no-rtti bug in the clang driver

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#406]
this will help us enable vptr for ffmpeg, harfbuzz, etc.

**Comment by kcc** [comment]
Yea... 
But it's actually unclear how and what to fix. 
Currently, ubsan/vptr and -fno-rtti are mutually exclusive because ubsan/vptr relies on rtt run-time. 
We can silently override -fno-rtti when vptr is given, but it may break more things (e.g. someone relies on not having rtti). Leaving to @mikea to look at, not urgent imho

**Comment by morehouse** [comment]
We should currently be disabling `vptr` silently at compile-time when `-fno-rtti` is present.  Is this not happening?

Or do those builds attempt to link C and C++ code using `clang` instead of `clang++`?  #713 has some discussion on this, and we ended up advising to link with `clang++` as the fix.

> We can silently override -fno-rtti when vptr is given

Why not just set `-frtti` in `CXXFLAGS` for the build?
