### ISSUE TITLE
[CIFuzz]: No build status and build logs for CIFuzz

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#4132]
This regressed 2-3 days back, maybe something changed with github actions format ? Any pointers to code where this is stored.
e.g. http://cifuzz.appspot.com/project/zstd
runs happen fine
https://github.com/facebook/zstd/runs/865061452
build page is empty - http://cifuzz.appspot.com/run/zstd/167896833
@jonathanmetzman - thoughts where i can look to debug this ?

**Comment by evverx** [comment]
I think it has something to do with https://github.com/facebook/zstd/pull/2242. It looks like http://cifuzz.appspot.com/ isn't compatible with a few CIFuzz jobs running in parallel.

**Comment by evverx** [comment]
Interestingly, to judge from http://cifuzz.appspot.com/project/systemd, it has never been triggered for the systemd repository.  All the links there lead to https://github.com/openSUSE/systemd/actions. Looks like it doesn't work at all when configs aren't "standard".

**Comment by jonathanmetzman** [comment]
I think the issue is the dashboard uses a lot of heuristics to find "official users" of CIFuzz since we don't have any phoning-home in CIFuzz. Instead the dashboard searches all github repositories for things that look like CIFuzz and tries to exclude things like copies of code (e.g. I think there are random repos that copy all of zstd source code).
Probably just need to tune these heuristics. I think I will get a chance to do this in 2 weeks.

**Comment by jonathanmetzman** [comment]
Eh. The dashboard is broken now though
