### ISSUE TITLE
Analyze why folks have to disable AFL due to slow to load tests (/timeout)

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#4201]
E.g. https://github.com/google/oss-fuzz/pull/4200

**Comment by alexhultman** [comment]
I hope this is applicable - I have 95% overall source code coverage with no issues whatsoever with libFuzzer (asan, msan, ubsan) with no timeouts at all - it's entirely clean with only zeroes in all columns.

But - with AFL I have timeouts of up to 60% of runs which is bizarre, and even really simple targets sometimes have timeouts.

Why is AFL timeouts not reported as bugs in the "All current crashes"? And is AFL timeouts a critical thing? Should I care about it? I am trying to locally reproduce the timeouts right now.

My goal is to have an ideal integration

**Comment by alexhultman** [comment]
I have this issue https://github.com/google/oss-fuzz/pull/4364

I have run AFL locally for more than an hour without triggering any hangs, so I cannot reproduce my 70% timeouts locally. They only happen with AFL on OSS-Fuzz it seems. I'm disabling AFL for now.

**Comment by inferno-chromium** [comment]
We will investigate this more in a week or two, but there is no harm in keeping AFL. AFL has lower timeout value, but i think we auto-adjust this.

**Comment by jonathanmetzman** [comment]
>I have run AFL locally for more than an hour without triggering any hangs, so I cannot reproduce my 70% timeouts locally. They only happen with AFL on OSS-Fuzz it seems. I'm disabling AFL for now.

Sorry for this, the user-experience with AFL can be bad in some projects.
To reiterate what Abhishek said, AFL uses a lower timeout than libFuzzer (maximum of 1 second). AFL is also pretty opinionated about what it accepts and (more than libFuzzer) will refuse to run if it thinks the user isn't holding it right (e.g. like with long timeouts or large testcases).
On ClusterFuzz we actually have code that tries to correct for some of these issues by rerunning AFL without inputs it doesn't like, we don't do this in CI though (yet).
Timeouts might be more common in CI than locally because of machine differences, so I can see how it's hard/impossible to debug.
Also, in some cases, reaching the 1 second timeout is a sign that there is something horribly wrong with the fuzzer's AFL integration (e.g. AFL forks the target process so threads can cause hangs). Because of this, and because the burden of getting AFL right might not be worth it, we'll often suggest disabling AFL when it doesn't work.
I can try to fix things up here and look into your fuzzer when I have more time (in a week or two probably).

**Comment by jonathanmetzman** [comment]
@alexhultman Sorry I misunderstood your project's issue with AFL since I though this issue was about timeouts in CI (which is a problem).
I think the issue you are seeing is that timeout_percent for uwebsockets with AFL is high (>50%) https://oss-fuzz.com/fuzzer-stats?project=uwebsockets&fuzzer=afl&job=afl_asan_uwebsockets&group_by=by-fuzzer ?

If I understand the stat correctly (tooltip says "Percent of fuzzing runs that had testcases timeout") then I think it can basically be ignored (and should be removed). I think the stat is reporting the percentage of 1.5 hour runs where AFL will see any hang at all. The stat is really only applicable to libFuzzer because hangs in AFL don't slowdown fuzzing for more than a second. So if this was the only problem you saw I'd suggest ignoring this and keeping AFL.
Apologies for the misunderstanding.

**Comment by alexhultman** [comment]
> I think the issue you are seeing is that timeout_percent for uwebsockets with AFL is high (>50%) https://oss-fuzz.com/fuzzer-stats?project=uwebsockets&fuzzer=afl&job=afl_asan_uwebsockets&group_by=by-fuzzer ?

Yes my timeouts are sometimes 70%, and even the most simple targets get timeouts with AFL.

**Comment by jonathanmetzman** [comment]
Lets' track this issue here: https://github.com/google/oss-fuzz/issues/5452
