### ISSUE TITLE
dozens of imagemagick bugs being marked flaky this morning

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#4256]
Decent chance this is a bug, so filing an issue

**Comment by inferno-chromium** [comment]
Only imagemagick project seems to be impacted, all bugs reference the same bad recent build 202008040618.

[2020-08-05 14:27:37 UTC] oss-fuzz-linux-zone3-host-b5kv-2: Progression task errored out: Known crash revision 202008040618 did not crash.
[2020-08-05 14:27:37 UTC] oss-fuzz-linux-zone3-host-b5kv-2: Progression task errored out: Testcase appears to be flaky.

**Comment by alex** [comment]
There are no commits in the last day that I would expect to destabalize anything: https://github.com/ImageMagick/ImageMagick/commits/master

**Comment by alex** [comment]
I assume OSS-Fuzz will eventually refind all of them 🤷

**Comment by inferno-chromium** [comment]
All of the mad marking was done by one bad host - oss-fuzz-linux-zone3-host-b5kv-2 [e.g. https://oss-fuzz.com/testcase-detail/5634994269061120] build 202008040618 is not bad, reuploading confirmed that, so something bad with host over time. @oliverchang in case you want to spend 5-10 min on this. otherwise i can wontfix the bug and see if this repeats.

**Comment by oliverchang** [comment]
Definitely want to see what happened here.

**Comment by oliverchang** [comment]
Looking at the logs I see some disk space issues -- I would guess this is what led to the strange behaviour. Also filed https://github.com/google/clusterfuzz/issues/1955 which would have prevented this, as somehow the repeated retrying got this past into an undesirable state. Closing this in favour of the CF bug.
