### ISSUE TITLE
[quic-go] zero code-coverage

### ISSUE THREAD

**Issue by marten-seemann** [google/oss-fuzz#4284]
It looks like fuzzing quic-go generates 0 coverage:
```
#333411352: cov: 0 ft: 665 corp: 105 exec/s 31906 oom/timeout/crash: 0/0/0 time: 5580s job: 104 dft_time: 0
```

I'm wondering if the fuzzer is hitting my code at all.

I've followed the instructions on https://google.github.io/oss-fuzz/advanced-topics/code-coverage/ to check what's going on locally.
```
python3 infra/helper.py build_fuzzers --sanitizer=coverage quic-go
```
builds my image successfully. However, running the coverage command generates the following error:
```
❯ python3 infra/helper.py coverage --no-corpus-download quic-go --fuzz-target header_fuzzer 
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e PROJECT=quic-go -e SANITIZER=coverage -e HTTP_PORT=8008 -e COVERAGE_EXTRA_ARGS= -p 8008:8008 -v /home/marten/src/oss-fuzz/build/corpus/quic-go:/corpus -v /home/marten/src/oss-fuzz/build/out/quic-go:/out -t gcr.io/oss-fuzz-base/base-runner coverage header_fuzzer
Running header_fuzzer
error: /out/dumps/*.profdata: No such file or directory
Failed to generate clang code coverage report.
```

Any idea how to proceed here?

**Comment by Dor1s** [comment]
Hi @marten-seemann 

There are two main applications / meanings of code coverage in OSS-Fuzz and fuzzing in general. Both meanings have the same nature (i.e. it is code coverage == code being executed as we run a program), but have slightly different applications:

1) code coverage feedback during fuzzing -- that's what is printed after `cov:` and `ft:` in libFuzzer's output. `cov:` stands for covered edges (https://clang.llvm.org/docs/SanitizerCoverage.html#edge-coverage) and `ft:` stands for "coverage features", i.e. some extended set of signals (for example, we can instrument comparison instructions additionally and record different signal from the same instruction depending on the actual values of the operands).

   In case of Go fuzzing in OSS-Fuzz, all coverage edges instrumented in the Go code, are being treated by libFuzzer as features (that's an implementation detail of how libFuzzer and Go are bridged together). That's why you see 0 coverage, but a growing number of coverage features.

2) Code coverage reports for visual inspection by a human. That's what documented at https://google.github.io/oss-fuzz/advanced-topics/code-coverage/ and what can be done by running `python3 infra/helper.py coverage ...` locally.

   That is currently supported for C/C++ only. I apologize for the inconvenience. We should make the helper script error out if the project's language is not supported, and also revisit the doc to make it explicit that it's C/C++ only as of now.

   We may eventually add support for other languages too, when we get more projects written in those and integrated with OSS-Fuzz.

   There is an open PR with experimental coverage report generation for Go target, you can try it out if you want to generate a report: https://github.com/google/oss-fuzz/pull/3142

**Comment by Dor1s** [comment]
I'll take care of these since I'm the next CF / OSS-Fuzz sheriff.
