### ISSUE TITLE
Bug not closed when testcase was marked as fixed

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#4305]
Bug is still open: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22294#c3
Test case has been fixed since May: https://oss-fuzz.com/testcase-detail/5675127391125504

Seems similar to #3964

**Comment by Dor1s** [comment]
Looks like it worked out after @inferno-chromium triggered progression task manually.

Still suspicious why it didn't happen automatically though.

I guess this wouldn't be easy to investigate, given that the testcase was Fixed in May, so I'm closing this one for now. Sorry for the trouble @terrelln and thanks for reporting this!

**Comment by Dor1s** [comment]
OTOH, one action item that comes to mind is to check all currently open issues in the bug tracker and then check their corresponding Monorail testcases. That way we can find more cases like this one.

**Comment by Dor1s** [comment]
Or even simpler, find all testcases that are fixed but their bugs are still open. Interestingly, I found 0 of these. Perhaps the issue may happen when something's wrong with the Monorail side of things, so that CF does attempt to verify the issue and records that the issue was closed, but somehow it doesn't actually happen.

**Comment by Dor1s** [comment]
//cc @oliverchang for other ideas

and closing again for now
