### ISSUE TITLE
Coverage report per fuzz target links to overall, shared coverage report

### ISSUE THREAD

**Issue by alexhultman** [google/oss-fuzz#4320]
If you click "fuzzer stats/coverage" under a fuzzer, say asan/libfuzzer, and look in the column cov_report. This column lists links to "Coverage" per fuzz target, but they all link to the same very "total" coverage report from what I can see. All links are the same.

I think this is a bug, or missing feature.

**Comment by Dor1s** [comment]
It's intentional. The main purpose of the coverage reports is to be useful for improving fuzz targets and increasing the overall coverage of the project. In that sense, having N separate reports for N fuzz targets isn't really useful, as all those reports may have both common and unique covered areas of code, and looking through them manually doesn't scale.

Another important point here is that generating reports for each individual fuzz target has some cost (given the number of fuzz targets we run), and it doesn't seem reasonable to generate thousands of reports per day if only one or a few of them (or zero?) are being looked at.

However, if you want to look at a coverage report for an individual fuzz target, you can generate it locally, please see https://google.github.io/oss-fuzz/advanced-topics/code-coverage/

As for the confusion in the UI, I agree, it's weird that a link in a fuzz target row is leading to a per project report. However, I think it's better than not having a link at all. If you have any suggestions for improving the UI, we would love to hear and discuss it!

**Comment by alexhultman** [comment]
Alright,

So, when the ideal integration states that fuzz targets should have 80+% coverage, that means for the whole project. Not every single fuzz target needs to have 80+%? I have some targets that are at like 20% but still provide new coverage to the overall project - my overall coverage is 90+% but like I said some targets are at way way below 80%.

**Comment by Dor1s** [comment]
> So, when the ideal integration states that fuzz targets should have 80+% coverage, that means for the whole project.

yes!

**Comment by alexhultman** [comment]
It might be obvious to you, and yes it makes a lot of sense. But think about it like this: Google would not want you to have a bunch of inefficient (as in low coverage percentages) fuzz targets running 24/7 consuming electricity for a tiny coverage percentage increase. So an ideal integration could very well have requirements that all fuzz targets should have high coverage percentages, individually, as well as overall. That would make sense, as well.

Anyways, thanks for explicitly clearing the ambiguity.

**Comment by Dor1s** [comment]
@alexhultman your point is totally correct, but often there are technical nuances that do not let us have fuzz targets that do not have unreachable code. That's why we can't really require that neither in OSS-Fuzz nor in our internal fuzzing systems (e.g. Chrome or Google internal).
