### ISSUE TITLE
SHA commit not linked properly to code

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4460]
When I fix a fuzzer bug, I add the SHA1 commit in https://bugs.chromium.org/p/oss-fuzz/issues
However, when I then click on the SHA, I get this error:

```
NOT_FOUND: Requested entity was not found.

[type.googleapis.com/google.rpc.LocalizedMessage]
locale: "en-US"
message: "Cannot parse URL as a Gitiles URL"

[type.googleapis.com/google.rpc.RequestInfo]
request_id: "79d384fec9bd4df086ed886464fd7581"
```

It would be handy to be able to click the SHA1 and see the fix

**Comment by inferno-chromium** [comment]
Monorail can't know which repository the bug belongs to. However, every fixed bug gets a comment like

ClusterFuzz testcase 5704411161296896 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_grok&range=202009180613:202009190602

So, you can click on that link and that will point to your repo.

**Comment by boxerab** [comment]
Thanks, @inferno-chromium !
