### ISSUE TITLE
How to update project in OSSFuzz

### ISSUE THREAD

**Issue by Kyrios0** [google/oss-fuzz#4505]
Recently, I am interested in the OSS-Fuzz. I have three questions. 

- 1. How to update project in OSS-Fuzz?
For example, if there's an update of nginx, when will the nginx in OSS-Fuzz be updated? Does then project maintainer needs to create a PR after the project is updated or OSS-Fuzz will automatically detect and update the project regularly?

- 2. Do the different versions of a project use the same corpus?
Are there some inherit options or the multiple versions of a project will be treated as completely independent binary targets?

- 3. How can I get public testcase report?
For example, I found a Deadline-Exceeded bug on the issue tracker: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4324. It has been opened to the public, but I still don't have access to its detailed report. Where can I get more information about this?

Could you please give me some guidance? Many thanks!

**Comment by jonathanmetzman** [comment]
>How to update project in OSS-Fuzz?

OSS-Fuzz rebuilds projects daily. So if in your project build you clone nginx's master branch, if the master branch gets updated the fuzzer gets updated.

>Do the different versions of a project use the same corpus?

What do you mean different versions of a project? Different fuzzers in a project?

>How can I get public testcase report?

I don't think we make the detailed report available. We do make the testcase that causes the crash public and we also make the git commit range in which the bug was introduced public, so you can reproduce the crash if you build the project within that range and use the provided testcase.

**Comment by Kyrios0** [comment]
Thank you for your reply!

> What do you mean different versions of a project? Different fuzzers in a project?

I mean different versions of a project. 
For example: On the first day, OSS-Fuzz fuzzed nginx v0.01 for 24 hours. On the second day, nginx was updated to v0.02. Will OSS-Fuzz treat nginx v0.02 as a new binary and starting fuzzing from 0?

**Comment by jonathanmetzman** [comment]
OSS-Fuzz projects almost always build from master so typically yes OSS-Fuzz will fuzz the new code as soon as it is available. 
It will not start fuzzing from 0 because it already has a corpus. It will continue from the corpus. Then once a day it will prune the corpus using the new binaries.

**Comment by zhiyunq** [comment]
@jonathanmetzman Interesting. It sounds to me that the project (e.g., ngnix) will be re-built by OSS-Fuzz on a daily basis. The corpus reuse part is somewhat vague. Whenever a project is rebuilt (say at the beginning of day n), OSS-Fuzz will always start fuzzing using the previous day's corpus (i.e., day n-1) or does it start from an empty corpus? According to what you described about the pruning, it sounds like it is the latter (as we are starting with a fresh built of a project on a new day). Am I right? 

In general, it seems a good idea to retain the previous day's corpus (at least partially) so that we can bootstrap the fuzzing more quickly on newer versions of the project (e.g., ngnix). Given that fuzzing is done daily, the number of code changes in the project may not be significant to warrant the invalidation of the seeds collected in the previous day(s).

**Comment by jonathanmetzman** [comment]
>OSS-Fuzz will always start fuzzing using the previous day's corpus (i.e., day n-1) or does it start from an empty corpus?

We only start from an empty corpus once, when the project is integrated. After that we have one corpus that is kept around forever. However once a day we prune testcases from that corpus, so if the code changes between builds some testcases can be deleted.


>In general, it seems a good idea to retain the previous day's corpus 


Definitely. We do this.

**Comment by Kyrios0** [comment]
@jonathanmetzman @zhiyunq Thanks, your answer solved my question!
