### ISSUE TITLE
Delay in filing issue?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#451]
https://oss-fuzz.com/v2/testcase-detail/6394161118838784 was found >24 hours ago, and an issue still hasn't been filed. It's not clear what's causing the delay.

**Comment by inferno-chromium** [comment]
Because same stack bug was closed ~30 hours ago - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=737. So, it waits for 48 hours before filing a new one with exact same stack. You can always manually file it if you need it faster, but this interval was kept to give enough time for new build to kick in and not continuously spam with same stack again and again. Do you think https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=737 is the same bug and CF closed it incorrectly or is this a new variant.

**Comment by alex** [comment]
No, this is really distinct, the same bug occurs twice in the same function.

Since this isn't an oss-fuzz bug, closing this.

**Comment by inferno-chromium** [comment]
Ok i manually created a new issue so you dont have to wait.
