### ISSUE TITLE
MSAN memcmp false positive ?

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#4538]
Inspired by 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26226

Reproducer program is
```
#include <string.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
    int a[5];
    int b[5];

    a[0] = 0;
    b[0] = 1;
    if (memcmp(a, b, sizeof(int)+1)) {
        printf("diff\n");
    }
    return 0;
}
```

Compiled with `clang++ -fsanitize=memory -fsanitize=fuzzer-no-link m.c`

Run issues
```
Uninitialized bytes in MemcmpInterceptorCommon at offset 4 inside [0x7ffe57d25350, 5)
==72412==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x44cbce in memcmp /src/llvm-project/compiler-rt/lib/msan/../sanitizer_common/sanitizer_common_interceptors.inc:873:10
    #1 0x49a3f7 in main (/src/a.out+0x49a3f7)
    #2 0x7f24b40ac83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #3 0x41c368 in _start (/src/a.out+0x41c368)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/llvm-project/compiler-rt/lib/msan/../sanitizer_common/sanitizer_common_interceptors.inc:873:10 in memcmp
Exiting
```

I understand that MSAN issues this warning because `memcmp` will try to read more than the uninitialized bytes at once.
But this cannot change the behavior of the program.
So, is this a false positive ?

**Comment by nelhage** [comment]
I came here prepared to argue this behavior was still UB. It seems clear that `memcmp` is *allowed* to read past the mismatch, since it is specified as "compares the first n characters," and nothing requires it to short-circuit. And furthermore, I have it in my mind as a truism that access to uninitialized variables of automatic storage duration is UB. 

However, after a while poring over a C spec (I'm using the n1548 draft because the actual specs aren't free, AIUI), I'm no longer convinced.

Annex J.2 does indeed declare that it is UB if

> The value of an object with automatic storage duration is used while it is indeterminate (6.2.4, 6.7.9, 6.8).

However, Annex J is informative only, so that can't be taken as ground truth on its own. 

Reading the referenced sections, we discover (§6.2.4) that variables of automatic storage duration are indeed "indeterminate" until initialized, and (§3.19.2) that an "indeterminate value" is "either an unspecified value or a trap representation." Making using of a trap value is generally UB, which explains where we get the rule summarized in the annex. Furthermore, `int` is indeed permitted to have bit representations that are trap values (§6.2.6.2), so it's quite clear that, e.g. accessing `a[2]` directly would be UB per spec.

HOWEVER, `memcmp` consumes its input as an array of `unsigned char`. Per §6.2.6.1p5:

> If the stored value of an object has [a trap] representation and is read by an lvalue expression that does not have character type, the behavior is undefined. 

That sentence seems to be the source of the rule that accessing trap representations is UB, and so it seems that _so long as you look at uninitialized memory through a character type_, you get back unspecified values, but are not UB.

(Additionally, per §6.2.6.2p1, `unsigned char` is also required to have a pure binary representation, with no padding bits or trap representations, which seems to provide further evidence that looking at memory as a sequence of `unsigned char` cannot UB).

And, if `memcopy` is specified to see this uninitialized memory as a sequence of unspecified but valid byte values, the reporter's argument holds that these byte values cannot effect the behavior of the program and it should therefore be defined.

(Of course, the question of whether we want to encourage this behavior and whether it's worth making a change to support it, are two different questions).

(Credit to @sfackler for pointing out that `memcpy` views memory as `unsigned char`, which cannot have a trap representation)

**Comment by catenacyber** [comment]
Thanks for this long answer

The question is indeed : do we want MSAN to allow this or to issue a warning ?

**Comment by jonathanmetzman** [comment]
Thanks fro this report!
However, we (OSS-Fuzz maintainers) don't fix things that are sanitizer bugs except in rare cases.
Could you file this instead in the [sanitizers repo](https://github.com/google/sanitizers/issues).

**Comment by jonathanmetzman** [comment]
CC @morehouse

**Comment by catenacyber** [comment]
Filed https://github.com/google/sanitizers/issues/1389
