### ISSUE TITLE
OSS-fuzz keeps trying to reproduce on old commit

### ISSUE THREAD

**Issue by nmoinvaz** [google/oss-fuzz#4618]
For several issues, it seems like OSS-Fuzz is using an older version of the C-Blosc2 repository. Am I correct in assuming that the commit being used is represented in the UI as:

![image](https://user-images.githubusercontent.com/1364432/98486553-d11b2d00-21d2-11eb-8126-e4b863a0fa94.png)
https://oss-fuzz.com/testcase-detail/6101295449767936

And another one:

![image](https://user-images.githubusercontent.com/1364432/98486584-fb6cea80-21d2-11eb-803b-71ad15d5107a.png)
https://oss-fuzz.com/testcase-detail/6527911908343808

I am not sure why OSS-Fuzz would be using old commits to rerun the tests. We do not have any build error issues for C-Blosc2 as far as I am aware. When I do "Redo Task", the metadata section does not appear to indicate what commit it was retried on:

![image](https://user-images.githubusercontent.com/1364432/98486615-366f1e00-21d3-11eb-9ef9-647f78a73eca.png)

I am having difficulty reproducing these at all in current commits. Any help would be appreciated. Thanks in advance!

**Comment by inferno-chromium** [comment]
It says "Reliably Reproduces: NO" which means that it is an unreproducible crash. Only reproducible crashes are retested everyday, whereas unreproducible ones are never tested again, but only closed based on looking at crash stats (like if that crash signature is not seen in last 14 days, then bug is closed. in those cases, no ui updates happen, so commit shows the time the bug was found).
