### ISSUE TITLE
[CIFuzz] MSAN test consistently failing with "No space left on device"

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#4879]
CIFuzz MSAN test is consistently failing with "No space left on device" on the zstd project. See https://github.com/facebook/zstd/pull/2438/checks?check_run_id=1592001475 for an example failure.

**Comment by jonathanmetzman** [comment]
Sorry I just noticed this, I'll try to fix this problem.

**Comment by jonathanmetzman** [comment]
Including logs (since GH actions disappear after 90(?) days).
[Uploading zstd-msan-disk-fill.txt…]()

**Comment by jonathanmetzman** [comment]
Some ideas for fixes:
1. Deleting corpora after fuzzing.
2. Deleting fuzzer + seed corpus after fuzzing.
3. Deleting docker images that are no longer needed (build_fuzzers, gcr.io/oss-fuzz-base/base-builder gcr.io/oss-fuzz/$PROJECT).

I'm going to try to reproduce this on github actions to see which of these offer the most worthwhile tradeoffs (I want to avoid solutions that slowdown the general case too much, since I haven't seen this issue come up before).

**Comment by jonathanmetzman** [comment]
@terrelln I noticed the failure on non-msan jobs.
https://github.com/facebook/zstd/runs/2063832893?check_suite_focus=true

I'm working on a fix right now. I think I can land it today.

**Comment by jonathanmetzman** [comment]
@terrelln I think we save enough diskspace now that MSAN should work again. Care to give it a try?

**Comment by MarcoFalke** [comment]
Can this be closed?
