### ISSUE TITLE
[CIFuzz] How do I bring in an external corpus?

### ISSUE THREAD

**Issue by evanmiller** [google/oss-fuzz#4928]
I'm trying to add CIFuzz to mdbtools but it's failing here:

https://github.com/mdbtools/mdbtools/runs/1591302880?check_suite_focus=true

For FLOSS reasons, mdbtools keeps its test files in a separate repo. The Docker file in OSS-Fuzz checks out the code into `mdbtools` and the test corpus into `mdbtools/test`.

However, it looks like the `test` subfolder is getting wiped out when CIFuzz checks out its own branch. I'd like to know the recommended way to get that test data to CIFuzz. Is there an existing setting for these situations? Should the Docker file be putting the corpus outside the source tree? Any advice appreciated.

**Comment by jonathanmetzman** [comment]
Sorry will look into this today.

**Comment by jonathanmetzman** [comment]
Sorry for the delay on this. I think I know the solution here.

> However, it looks like the `test` subfolder is getting wiped out when CIFuzz checks out its own branch. 


Yep, unfortunately it's simplest for CIFuzz to just nuke the directory so CIFuzz does that.

>Should the Docker file be putting the corpus outside the source tree? 

Yes exactly. For example, you could change mdbtools/test to mdbtools-test on [this line](https://github.com/google/oss-fuzz/blob/master/projects/mdbtools/Dockerfile#L21) which should solve your problem since the corpus repo won't get nuked with the source repo.
Let me know if this is unclear and feel free to reopen if this doesn't solve your issue.

**Comment by evanmiller** [comment]
@jonathanmetzman Thanks for the clarification. I have opened a PR moving the test files out of the way so that they will work with CIFuzz's assumptions.
