### ISSUE TITLE
Unable to reproduce bug found in ASM

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#5081]
Bug report is https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29967
Following the steps described in https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs
I do not manage to get the crash reproduced locally (as I usually do)

I think this is because the stack ends in some assembler 
```
==997622==ERROR: AddressSanitizer: SEGV on unknown address 0x607000020000 (pc 0x0000008c90d4 bp 0x0000008ca6c0 sp 0x7fffc46e8e40 T0)
--
  | ==997622==The signal is caused by a READ memory access.
  | SCARINESS: 20 (wild-addr-read)
  | #0 0x8c90d4 in anonymized2 /src/path/to/file.S:307
  | #1 0x7f0630 in  anonymized1 /src/path/to/file.c:186:10
```

Am I missing something ? (some ASAN_OPTIONS) ?

**Comment by jonathanmetzman** [comment]
Yeah to me it looks like this code isn't standard x86_64 code and is CPU specific. Not a good idea to fuzz this code in OSS-Fuzz because of this issue. Better to turn it off.
If you really want to repro, it might be worth trying to get a google cloud instance for this.
Let us know if you'd like a grace period extension on this.
