### ISSUE TITLE
New CIFuzz setup failing due to failure to zip seed corpus images

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#5291]
I've set up CIFuzz for my project:

https://github.com/google/oss-fuzz/tree/master/projects/grok
https://github.com/GrokImageCompression/grok/actions

Unfortunately, the seed corpus images that I clone (working correctly in ozz-fuzz) are not found in CIFuzz, so zipped corpus is not created and CIFuzz fails.
It looks like the two repos that are cloned in the oss-fuzz Dockerfile (one is for the code and one is for the seed corpus) are not available to the CIFuzz image, which does a second clone of the code and builds from there (but seed images are missing).

**Comment by jonathanmetzman** [comment]
Pasting my comment from https://github.com/google/oss-fuzz/issues/5272#issuecomment-790145292.

My first guess is this is easy to fix.
Basically, CIFuzz clobbers your source repo (because it needs to checkout something other than the default branch, it does a new clone of the repo (to avoid complexity with running code in multiple docker containers)). So if your build depends on a modification done to the repo directory (a modification that isn't in git history) CIFuzz breaks.
So if you change [this line](https://github.com/google/oss-fuzz/blob/master/projects/grok/Dockerfile#L21) to 
```
RUN git clone --depth 1 https://github.com/GrokImageCompression/grok-test-data.git grok-data
```
And this file: https://github.com/GrokImageCompression/grok/blob/master/tests/fuzzers/build_seed_corpus.sh#L1 to use grok-data, things should work.
Sorry, I really should document this (or maybe fix this behavior).

**Comment by boxerab** [comment]
Thanks :) I will make a PR with the oss-fuzz changes.

**Comment by jonathanmetzman** [comment]
No problem.
Just a quick note on debugging this. After your fix PR lands, wait 5-10 minutes before trying again to run CIFuzz. We need to rebuild the CIFuzz image using the new source code.

**Comment by boxerab** [comment]
Thanks, will do.  Here is my PR:

https://github.com/google/oss-fuzz/pull/5292

**Comment by boxerab** [comment]
Thanks again.
