### ISSUE TITLE
Make download link in CF report more stable.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#539]
Right now the download link includes the blob key. If we ever re-do minimize, that blob key is no longer associated with the testcase and can no longer be downloaded by external users.

We should make this link more stable.

**Comment by kcc** [comment]
An alternative to consider: attach the reproducer(s) as files to the bug report instead of giving a link. 
Since we now open the reproducers together with the bug, it may work well.
A side effect will be that just to reproduce the crash users won't need to login, i.e. CC-ing to mail lists 
will be more meaningful
(The link to the full CF page will sill be there)

**Comment by oliverchang** [comment]
Maybe, but it might be good maintenance-wise to keep behaviour the same as chromium land, where we definitely can't do this.

Do monorail issues include attachments in email notifications? I thought folks will still need to login to monorail to get any attachments.

**Comment by kcc** [comment]
>> same as chromium land

good point

**Comment by inferno-chromium** [comment]
I think we can just skip the blob part altogether

/download?testcase=X will pick minimized testcase if available, otherwise unminimized one.

**Comment by inferno-chromium** [comment]
Looking.

**Comment by inferno-chromium** [comment]
fixed.
