### ISSUE TITLE
Use standalone main in reproduce

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#55]
https://reviews.llvm.org/rL285135 adds standalone main
Reproduce command should link with that one instead of full libfuzzer.

**Comment by Dor1s** [comment]
That seems to be needed for issue #799. Not sure about reproducing with standalone target, but for coverage it definitely would be useful. For example, a test report for zlib contains more libFuzzer coverage data than stuff from zlib itself:

![image](https://user-images.githubusercontent.com/3372458/29837418-f14b1a90-8cac-11e7-8bb3-b9cd8fd64395.png)

Some fuzz targets have more than 32K units in corpus, but I think our Linux images can handle more,  so current implementation of https://github.com/llvm-mirror/compiler-rt/blob/master/lib/fuzzer/standalone/StandaloneFuzzTargetMain.c#L24 shouldn't fail for those.

**Comment by kcc** [comment]
We can also feed parts of the corpus to StandaloneFuzzTargetMain.c and then merge the results. 
Or enhance StandaloneFuzzTargetMain.c

**Comment by Dor1s** [comment]
I see the following benefits (all of them don't seem strong enough):
* faster and smaller coverage builds (i.e. with profiler instrumentation)
* reproducibility that is independent from libFuzzer revisions (e.g. imagine a bad revision that crashes or exits), standalone target is less fragile
* can be slightly better for debugging a single crash / issue

But I tend to Oliver's opinion that we don't really need this...

**Comment by oliverchang** [comment]
Thanks for outlining these.

> faster and smaller coverage builds (i.e. with profiler instrumentation)
I would imagine the bulk of the time it takes to generate coverage would come from actually running individual inputs? there shouldn't be much (time) overhead from libFuzzer driving this right?

> reproducibility that is independent from libFuzzer revisions (e.g. imagine a bad revision that crashes or exits), standalone target is less fragile
This complicates many things on CF end, and we would need it to support timeout and OOM detection.

Right now I'm not seeing the benefits :/ over the downsides:

- This adds 3 more builds to our build matrix.
- The standalone main has limitations: e.g. with the maximum number of units that it can run at a time because of commandline length limitations.

**Comment by Dor1s** [comment]
Yes, the overheard shouldn't be significant for most of the targets.

**Comment by Dor1s** [comment]
@kcc @inferno-chromium do you have any ideas why we might need a standalone build? I don't remember why Mike had created this issue in the first place...

**Comment by kcc** [comment]
a standalone build is easier to reason about for anyone who is not familiar with our tools. 
It's also much easier to reproduce bugs with it outside of our environment (especially if e.g. msan is involved). Since we already use different compiler flags to build for coverage, why not also link it against a different `main`? 

> standalone main has limitations:

Yes, I don't want to make this `main()` more complex because a) it will force us to write a non-portable code and b) it will complicate what needs to be very simple. 

But this complication is very easy to overcome. Suppose `C*` are the corpus dirs. 
All you need to do is:
```
find C* -type f | split -b $(expr $(getconf ARG_MAX) / 2)
for f in x??; do ./a.out $(cat xaa); done
# merge the profiles
```

**Comment by oliverchang** [comment]
> a standalone build is easier to reason about for anyone who is not familiar with our tools. It's also much easier to reproduce bugs with it outside of our environment (especially if e.g. msan is involved).

That should be part of the upstream build system right? The proposed changes here will require interacting with our tools anyway (docker/helper etc).

> Since we already use different compiler flags to build for coverage, why not also link it against a different main?

Why use a more limited main when we can just use libFuzzer's? :)

> But this complication is very easy to overcome.

This still seems unnecessarily complicated from an infra standpoint...

**Comment by kcc** [comment]
> That should be part of the upstream build system right?

Should, but we can't really enforce it. 

> Why use a more limited main when we can just use libFuzzer's? :)

Because it adds complexity :) 
E.g. you either should not instrument it, or you should filter out the results of instrumenting it.

**Comment by oliverchang** [comment]
> Should, but we can't really enforce it.

Right, I'm just saying that this benefit (easier to reason/reproduce outside of our environment) is only there if developers use this in their upstream build system. If we're using this in our own tooling/environment (as the proposed change is about), there is little benefit in this regard (that I see).

> Because it adds complexity :)

In the standalone main's current state I'm afraid we are just shifting complexity elsewhere.. (by doing the splitting and merging). Filtering out the libFuzzer parts on the other hand should be relatively simple.

**Comment by kcc** [comment]
ok. I don't insist. :)

**Comment by Dor1s** [comment]
Thanks for the discussion.

I agree that we have to aggregate / process coverage stats anyway, so removing libFuzzer-related coverage wouldn't be a problem.

I'm closing this issue and abandoning my PR.
