### ISSUE TITLE
libFuzzer's RssLimitCallback may miss some OOMs

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#554]
Initial issue from Chromium bug tracker: [715113](https://bugs.chromium.org/p/chromium/issues/detail?id=715113)

Summary: [RssLimitCallback](https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerDriver.cpp#249) is being executed in a separate thread once per second. Thus, there is a chance that it doesn't catch OOM when testing a single testcase.

I see two options:

1) Add an explicit call to `RssLimitCallback` in libFuzzer somewhere after processing a single testcase or before printing final status.

2) Ensure that we have enough retries on CF side.

Not sure what is more convenient. Other ideas are welcome.

**Comment by inferno-chromium** [comment]
Yes once after processing the testcase is definitely needed. @kcc - thoughts.

**Comment by kcc** [comment]
1. won't fully help because in some cases we will still die due to OOM *while* running a single test case
(which is the reason we have to check rss in a separate thread)

We may try the same trick as with timeouts. While fuzzing, use rss_limit_mb=2500 and then reproduce with rss_limit_mb=2000. Not sure if this is actually going to work :(
