### ISSUE TITLE
Add pkg-config to oss-fuzz base image

### ISSUE THREAD

**Issue by priyawadhwa** [google/oss-fuzz#5603]
The cosign fuzzing tests recently start failing with this error:

```
Step #4: Running go-fuzz -tags gofuzz -func FuzzGetPassword -o fuzz_getPassword.a github.com/sigstore/cosign/test
Step #4: # pkg-config --cflags  -- libpcsclite
Step #4: pkg-config: exec: "pkg-config": executable file not found in $PATH
Step #4: 2021/04/11 10:58:47 failed to build packages:exit status 2
```

Full log [here](https://oss-fuzz-build-logs.storage.googleapis.com/log-5c23b77a-88fe-4ea8-b0f4-715a6cbb5b5f.txt)

My guess is that pkg-config needs to be installed in the `gcr.io/oss-fuzz-base/base-builder` image, but let me know if I'm missing something!

**Comment by inferno-chromium** [comment]
for generic stuff, we add in base-builder image, otherwise it goes in dockerfile for the project. pkg-config seems generic enough, that it can go in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L24. can submit pr for that and also do a newline change in cosign build.sh for CI to trigger and verify.

**Comment by priyawadhwa** [comment]
Thanks! I just realized that some new changes in cosign might actually require a couple packages to be installed, so I'll probably add them directly to the Dockerfile for the cosign project.
