### ISSUE TITLE
[openjdk] Pre-integration questions

### ISSUE THREAD

**Issue by fmeum** [google/oss-fuzz#5757]
Jazzer has recently gained the ability to fuzz the Java standard library itself (at least the parts that Jazzer doesn't use itself). The standard library includes parsers for certificates and public keys, date and time, as well as various image formats.

Before I propose OSS-Fuzz integration to the OpenJDK developers, I would like to clarify how the integration would look like. I see two possible approaches:

1. Build OpenJDK from HEAD. This requires a bootstrap JDK in version 16 or 17, which would have to be installed from the official release binaries. 
2. Use a [nightly build](https://adoptopenjdk.net/nightly.html?variant=openjdk16&jvmVariant=hotspot).

Both approaches would require downloading and running binaries as part of the build process. Which of the two options would be preferable for OSS-Fuzz?

**Comment by jonathanmetzman** [comment]
> Jazzer has recently gained the ability to fuzz the Java standard library itself (at least the parts that Jazzer doesn't use itself). The standard library includes parsers for certificates and public keys, date and time, as well as various image formats.
> 
> Before I propose OSS-Fuzz integration to the OpenJDK developers, I would like to clarify how the integration would look like. I see two possible approaches:
> 
> 1. Build OpenJDK from HEAD. This requires a bootstrap JDK in version 16 or 17, which would have to be installed from the official release binaries.

We generally prefer this approach.

> 2. Use a [nightly build](https://adoptopenjdk.net/nightly.html?variant=openjdk16&jvmVariant=hotspot).
> 
> Both approaches would require downloading and running binaries as part of the build process. Which of the two options would be preferable for OSS-Fuzz?

Sorry, I think I gave the wrong impression before, let me clarify.
I don't want arbitrary binaries downloaded and executed in the base images because that is common infrastructure everyone relies on.
However, arbitrary binaries are fine in individual OSS-Fuzz project images. 
OSS-Fuzz infra that builds the images and executes the fuzzers is built to be secure against malicious projects.
So if a project is evil or hacked, it's not a concern for OSS-Fuzz as a whole.
Since I presume the openjdk maintainers trust their own binaries, I don't see a problem with this at all.
