### ISSUE TITLE
Fix signature for UBSan -fsanitize=null

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#582]

**Comment by inferno-chromium** [comment]
Reading most of the checks in http://llvm.org/svn/llvm-project/compiler-rt/trunk/test/ubsan/TestCases/TypeCheck/null.cpp, they actually look indeed like null ptr deference. 

case 'l':
    // CHECK-LOAD: null.cpp:[[@LINE+1]]:12: runtime error: load of null pointer of type 'int'
    return *p;
  case 's':
    // CHECK-STORE: null.cpp:[[@LINE+1]]:5: runtime error: store to null pointer of type 'int'
    *p = 1;
    break;
  case 'r':
    // CHECK-REFERENCE: null.cpp:[[@LINE+1]]:15: runtime error: reference binding to null pointer of type 'int'
    {int &r = *p;}
    break;
  case 'm':
    // CHECK-MEMBER: null.cpp:[[@LINE+1]]:15: runtime error: member access within null pointer of type 'S'
    return s->k;
  case 'f':
    // CHECK-MEMFUN: null.cpp:[[@LINE+1]]:15: runtime error: member call on null pointer of type 'S'
    return s->f();
  case 't':
    // CHECK-VCALL: null.cpp:[[@LINE+1]]:15: runtime error: member call on null pointer of type 'T'
    return t->v();
  case 'u':
    // CHECK-VCALL2: null.cpp:[[@LINE+1]]:15: runtime error: member call on null pointer of type 'U'
    return u->v();

@kcc - I am still torn on the idea of differentiating these from actual crashes (ASan ones). They do look like the same class of problems, even though some of them might not lead to crash.

**Comment by kcc** [comment]
Yea.. These are two fundamentally different types confused here under the same ubsan flag. 
* regular null derefs that would be reported as SEGV otherwise 
* potential null derefs that **may** cause an actual SEGV, **or may not**

Frankly, I don't know why ubsan needs to flag the real null derefs (they will crash anyway).
Unless we want to change the ubsan behavior somehow, we'll need to parse the error messages and 
treat some of them as "null dereference" and others as "potential null dereference". 
If we don't want to report "potential null dereference", we can just disable this ubsan feature.

**Comment by inferno-chromium** [comment]
Changed CF signature from Null-deference to Potential-null-dereference for parsing signature.
