### ISSUE TITLE
How to deal with target that uses special CPU instructions?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#5914]
The blst library in the bls-signatures OSS-Fuzz project uses special CPU instructions (I think [ADX instructions](https://en.wikipedia.org/wiki/Intel_ADX)) which are supported by some CPUs but not by others.

OSS-Fuzz/ClusterFuzz runs targets on random CPUs. In the case of bls-signatures, this results in frequent non-reproducible crashes, as you can see here: https://oss-fuzz.com/testcases?project=bls-signatures&open=yes

To make this stop, I can compile blst without assembly optimizations, but I don't want that because in the past an important bug was found in the assembly code of blst, and it is important that this code is run/fuzzed (despite assembly code not being instrumented).

Another solution is that I detect the host CPU capabilities at fuzzer startup, and return 0 from `LLVMFuzzerTestOneInput` if the requisite instructions aren't available. But I worry that this will cause problems because:

-  libFuzzer (and maybe other engines as well) perform REDUCE operations on the corpus files (unless the `-reduce_inputs=0` option is passed) which may cause it to destroy inputs if it finds those don't lead to new code coverage
- Corpus merge operations and code coverage report generation may not work as expected on systems without ADX capabilities

What are your thoughts on this?

**Comment by jonathanmetzman** [comment]
Well, what's the problem with unreproducible crashes?
Are they so annoying that we'd rather miss them because of this issue or is having these bugs as unreproducible acceptable but less optimal than having them repro consistently?
If it's the latter, then the status quo seems the least bad to me.
Compiling without assembly will make these bugs get missed entirely.
I don't think the CPU-detection part helps really. The bug still won't reproduce on some random CPUs and will thus still be labeled unreproducible right?

**Comment by guidovranken** [comment]
That makes sense. Let's keep it this way. Thanks.

**Comment by jonathanmetzman** [comment]
Sorry I can't be of more help, but I think CPU-specific instructions just violate too many assumptions of OSS-Fuzz to make work perfectly.
