### ISSUE TITLE
Coverage report files are inaccessible since today

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#5934]
For example click on any file in this list: https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210617/linux/src/cryptofuzz/modules/openssl/report.html

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
</Details>
</Error>
```

Seems to affect all projects (I tested a few random ones)

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by guidovranken** [comment]
Yes, coverage report for today (19 06 2021): https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210619/linux/src/cryptofuzz/modules/openssl/report.html

Files still can't be accessed.

**Comment by inferno-chromium** [comment]
Something has gone wrong with the links, instead of
https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210617/linux/src/cryptofuzz/modules/openssl/bn_ops.cpp.html

it is now
https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210617/coverage/src/cryptofuzz/modules/botan/bn_ops.cpp.html

**Comment by inferno-chromium** [comment]
Ok culprit is https://chromium-review.googlesource.com/c/chromium/src/+/2967483 
These chromium code coverage script changes are painful, hardcoding the commit hash for now.

**Comment by inferno-chromium** [comment]
and it works now - https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210620/linux/src/cryptofuzz/modules/openssl/report.html
with
https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20210620/linux/src/cryptofuzz/modules/openssl/bn_ops.cpp.html

Thanks a lot @guidovranken @MarcoFalke , reports should be fixed by tmrw for all projects.

**Comment by guidovranken** [comment]
Thank you!
