### ISSUE TITLE
Access to varnish project

### ISSUE THREAD

**Issue by bsdphk** [google/oss-fuzz#5940]
Hi,

I dont have (and dont want) all my online identities linked together, and the address used for the Varnish cache project (phk@varnish.org)  is not linked to my gmail account (bsdphk), so how do I get access to the results for the varnish cache project ?

**Comment by DavidKorczynski** [comment]
In order to get access to the reports the email must be linked to a google account. All emails listed under `primary_contact` and `auto_ccs` in the `project.yaml` for a given project has access. We can put whichever emails the maintainers prefer in the `project.yaml` https://github.com/google/oss-fuzz/blob/master/projects/varnish/project.yaml so if you are happy to have your gmail account email in the `auto_ccs` field in the `project.yaml` then that would be an easy solution.

**Comment by bsdphk** [comment]
That works for me.

**Comment by bsdphk** [comment]
How long time should I expec

**Comment by bsdphk** [comment]
Ok, works now.
