### ISSUE TITLE
oss-fuzz build for Myanmar Tools failing

### ISSUE THREAD

**Issue by sffc** [google/oss-fuzz#6035]
No recent changes have been made in the Myanmar Tools project, but the oss-fuzz build is failing.

This is not the first time the build has spontaneously been broken by changes outside of the Myanmar Tools project. See: google/oss-fuzz#3202, google/oss-fuzz#3656

Upstream bug: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35901

Downstream: https://github.com/google/myanmar-tools/issues/89

The error is:

```
Step #13: /usr/local/bin/clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp -stdlib=libc++ -rdynamic CMakeFiles/myanmartools_c_test.dir/zawgyi_detector_unittest.c.o -o myanmartools_c_test  -Wl,-rpath,/src/myanmar-tools/clients/cpp/build libmyanmartools.so /builder/home/.hunter/_Base/5ead1e0/386ce2b/ead1bc1/Install/lib/libglogd.a -lunwind 
Step #13: libmyanmartools.so: undefined reference to `__afl_area_ptr'
Step #13: clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

CC @inferno-chromium @gnrunge

**Comment by inferno-chromium** [comment]
looks like some afl++ failure, @vanhauser-thc - thoughts?

**Comment by jonathanmetzman** [comment]
I think this is the honggfuzz build thats broken.

**Comment by vanhauser-thc** [comment]
well the issue is plainly to see:
`/usr/local/bin/clang++ ...` 
it would need to be afl-clang-fast++ instead. so CXX is either not picked up, or it also has to set as the linker.

**Comment by vanhauser-thc** [comment]
also this is all wrong: "-fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp"
seems like a bug in oss-fuzz itself as with the compile_afl it is impossible to happen

**Comment by jonathanmetzman** [comment]
So the build that is failing here is the libfuzzer build, not the AFL build.
What's weird is this works fine (both AFL and libFuzzer builds) locally.

**Comment by jonathanmetzman** [comment]
I have no idea what's going on here but this seems to be a somewhat similar issue to https://github.com/google/oss-fuzz/issues/5317 where one build seems to affect another.

**Comment by jonathanmetzman** [comment]
I can repro this by requesting this build https://console.cloud.google.com/logs/query;query=resource.type%3D%22build%22%0Aresource.labels.build_id%3D%2261a28d33-38cb-46f3-afb6-983f4c947ffe%22;timeRange=PT1H;cursorTimestamp=2021-07-15T16:15:56.119920958Z?pli=1&rapt=AEjHL4NCwdOkwcIgvVRKcw3c_Pxw0WwHLMFnfGWuDuOpwmaTtryXD9rOr0huzZIB1DFcAJ59Ymd7kxYm4iCc6CZenpqkB96dMg&project=oss-fuzz

**Comment by jonathanmetzman** [comment]
Build seems to fail for a different reason when I comment out AFL. https://pantheon.corp.google.com/cloud-build/builds;region=global/e001a981-3887-434e-82de-b2498de67c9b;step=13?project=oss-fuzz unclear to me what is going on.

**Comment by sffc** [comment]
Could the solution be similar to the one from 2 years ago here?

https://github.com/google/oss-fuzz/commit/e612b88c67befee843338e13f734fb6426a0e054

where we had to explicitly copy *libunwind.so* into the container.

**Comment by jonathanmetzman** [comment]
> Could the solution be similar to the one from 2 years ago here?
> 
> [e612b88](https://github.com/google/oss-fuzz/commit/e612b88c67befee843338e13f734fb6426a0e054)
> 
> where we had to explicitly copy _libunwind.so_ into the container.

I don't know. To be honest I have a very poor understanding of what's going on here and I'm unable to repro this locally at all despite trying to redo what the build infra does. But I think this is the fault of OSS-Fuzz and not the project. I think the AFL build is affecting the honggfuzz build and it should not.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman sorry you are wrong, it is not a libfuzzer issue, it is the project's issue that not correctly set up their build.

> Step #13: libmyanmartools.so: undefined reference to `__afl_area_ptr'

this means that afl++ instrumentation was used to build the shared library, not libfuzzer

> /usr/local/bin/clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp -stdlib=libc++ -rdynamic CMakeFiles/myanmartools_c_test.dir/zawgyi_detector_unittest.c.o -o myanmartools_c_test  -Wl,-rpath,/src/myanmar-tools/clients/cpp/build libmyanmartools.so /builder/home/.hunter/_Base/5ead1e0/386ce2b/ead1bc1/Install/lib/libglogd.a -lunwind 

this shows that not afl-clang-fast is used as it should be, and that the CFLAGS are likely set hard somewhere in the projects which is wrong too.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman sorry you are wrong, it is not a libfuzzer issue, it is the project's issue that not correctly set up their build.

I think I am right. This bug is confusing.
If you look at the [build failure logs](https://oss-fuzz-build-logs.storage.googleapis.com/log-d09bc284-765a-42d3-97ba-2d09bfe36b2f.txt), at the very bottom of the page right where the failure happens, the following message is printed:

```
Step #13: ********************************************************************************
Step #13: Failed to build.
Step #13: To reproduce, run:
Step #13: python infra/helper.py build_image myanmar-tools
Step #13: python infra/helper.py build_fuzzers --sanitizer address --engine honggfuzz --architecture x86_64 myanmar-tools
Step #13: ********************************************************************************
```

This means that the honggfuzz build failed. Further up in the logs by searching for afl-clang-fast you can see the AFL build succeeded.
You can verify the AFL build of this project works by building it locally: `python infra/helper.py build_fuzzers myanmar-tools --engine afl`
I think what is going on here is some library built during the AFL++ is somehow being reused in later builds which is causing things to break.

**Comment by vanhauser-thc** [comment]
ah you were looking at the full log. my bad - I thought the lines pasted in the issue were the full picture :)

**Comment by jonathanmetzman** [comment]
@oliverchang I was able to debug this locally and conclude that docker containers are reused across fuzzer/sanitizer builds.
I debugged this using the following command (which uses [cloud-build-local](https://cloud.google.com/build/docs/build-debug-locally)) and this command:
```
cloud-build-local --write-workspace=/tmp/workspace --config=/tmp/steps2.yaml --dryrun=false --push=false ~/oss-fuzz
``` 
Note you may need to use a fresh checkout of oss-fuzz since the build directory interferes with things.
[steps2.txt](https://github.com/google/oss-fuzz/files/6841811/steps2.txt) is a minimal version of the build steps and is attached.

In this project specifically I was able to workaround this issue by adding `rm -rf rm -rf /builder/home/.hunter` to build.sh.
I'm going to do this in a PR to prove what I am saying in this comment.
I don't know what the long term solution is to this issue. My best idea is we find a way to name each container we use based on gcr.io/oss-fuzz/$PROJECT_NAME

**Comment by jonathanmetzman** [comment]
I'll hedge a little and add I could be wrong if cloud-build-local has different behavior than the real google cloud build.
But let's find out. I'm going to kick off a new build. If it passes then state is being preserved.

**Comment by jonathanmetzman** [comment]
Running cloud-build-local and then ps, I see these arguments passed to docker that I think are problematic:
```
-volume cloudbuild_vol_fff5cf43-7ff1-4fd7-8b1a-b9cdbdc5236b:/workspace --workdir /workspace --volume homevol:/builder/home --env HOME=/builder/home --network cloudbuild --volume /tmp/step-1/:/builder/outputs --env BUILDER_OUTPUT=/builder/outputs
```
This means that /builder/outputs /builder/home /workspace are persisted across builds.
I think /builder/home is most problematic because this is the HOME directory and it seems likely some build processes will reuse this. I think we can probably safeguard most users by resetting HOME to /root.
However, to be thorough we probably should wipe the other directories as well.

**Comment by jonathanmetzman** [comment]
> I'll hedge a little and add I could be wrong if cloud-build-local has different behavior than the real google cloud build.
> But let's find out. I'm going to kick off a new build. If it passes then state is being preserved.

The [last build](https://oss-fuzz-build-logs.storage.googleapis.com/log-b4ded61c-707f-45a7-9b12-408858547daa.txt) passed. It confirms that this problem is caused by /builder/home being persisted.

**Comment by MarcoFalke** [comment]
Can this be closed?
