### ISSUE TITLE
cifuzz: remove for "oss-fuzz-project-name" requirement for external projects

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6051]
This seems unnecessary -- we can probably derive a value for this elsewhere or just use some placeholder where some name is needed.

We can instead use "oss-fuzz-project-name" to distinguish between whether a project is in OSS-Fuzz or not. This should solve this comment: https://github.com/google/oss-fuzz/blob/991d91f8c38785ea8be4f405a53238d15744ba52/infra/cifuzz/actions/run_fuzzers/action.yml#L51)

@jonathanmetzman WDYT?

**Comment by jonathanmetzman** [comment]
I think having oss-fuzz-project-name for non-git projects is a wart and i wanted to let them specify project-name instead.
However, having worked on CIFuzz some, I think something explicit wrt OSS-Fuzz is the way to go (maybe OSS-Fuzz-project-name is explicit enough).
Instead of being explicit cifuzz has relied on a lot of implicit things, like if X then Y must be true. And this has come back to bite me.

**Comment by oliverchang** [comment]
Yeah, "oss-fuzz-project-name" does seem explicit enough. 

Do we need a "project-name" at all for the external case? Seems like we can just omit that and derive that from somewhere else.

**Comment by oliverchang** [comment]
Looking through the code, it seems like there's no real dependency on a project name being some specified value for external fuzzing environments. 

I think we should actually rename config_utils's `project_name` to `oss_fuzz_project_name` here, as it's really only needed in this case, and then keying `is_internal` off the existence of that instead.

**Comment by oliverchang** [comment]
This was done.
