### ISSUE TITLE
cifuzz: corpus pruning

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6064]

**Comment by oliverchang** [comment]
CF side issue: https://github.com/google/clusterfuzz/issues/2380

**Comment by jonathanmetzman** [comment]
I think this is going to involve something more complex than having some scripts call libFuzzer merge.
I'm pretty sure the only reason prune works in ClusterFuzz is because CF bots only merge back the new testcases they have found during fuzzing and not old ones. Otherwise if fuzzing started while pruning was happening, the pruned files would be written back to the corpus by fuzzing task.

I don't think we can do the same thing with artifacts. I don't think a corpus artifact is something multiple fuzzers can write to at the same time either.
I haven't been so pro-parallel fuzzing for CFLite and so I haven't put enough thought into it.

Another reason I don't like the ClusterFuzz prune model is it seems to add complexity for not much value. Fuzzing is basically the same thing as pruning. Everytime we fuzz, the fuzzer knows which testcases are redundant and can be removed. I'd rather users didn't have to set a prune job as well.

**Comment by oliverchang** [comment]
We can do something similar here. I think it's important to expand the scope here so allow parallel fuzzing.

#6052 will make this easier as well.
