### ISSUE TITLE
[CIFuzz] Should source code of external project be copied into the container?

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6119]
CIFuzz for OSS-Fuzz assumes that the source code of the project must be copied into the container.
However, for external users this assumption is false. We do it anyway to avoid having extra logic, but this is kind of ugly.

**Comment by jonathanmetzman** [comment]
Having this requirement can mess up external users because the implementation of the source code copying depends on knowing the `GITHUB_REPOSITORY` of the project.

**Comment by oliverchang** [comment]
> project must be copied into the repo.

You mean "copied into the container" right? :)

Am I understanding correctly that the issue here is:

- The build integration Dockerfile copies in the project source at build time, which is expected to be at the right revision. 
- We copy this back to /src/project_repo_name, which may not even be the correct place. 

If so, agreed that we should skip the copy here. Just need to figure out a clean way to have this logic. 

> Having this requirement can mess up external users because the implementation of the source code copying depends on knowing the GITHUB_REPOSITORY of the project.

Can you expand more on why this is also a problem? Most CI / environments will have an equivalent to "GITHUB_REPOSITORY" right?

**Comment by jonathanmetzman** [comment]
> > project must be copied into the repo.
> 
> You mean "copied into the container" right? :)

Yes.

> 
> Am I understanding correctly that the issue here is:
> 
> * The build integration Dockerfile copies in the project source at build time, which is expected to be at the right revision.
> * We copy this back to /src/project_repo_name, which may not even be the correct place.

Yes.


> 
> If so, agreed that we should skip the copy here. Just need to figure out a clean way to have this logic.
> 
> > Having this requirement can mess up external users because the implementation of the source code copying depends on knowing the GITHUB_REPOSITORY of the project.
> 
> Can you expand more on why this is also a problem? Most CI / environments will have an equivalent to "GITHUB_REPOSITORY" right?

I suppose it's not a problem to require this. But it being redundant is a problem.
