### ISSUE TITLE
don't report actual null derefs as potential

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#614]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1638
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1641

Here, we have one bug that reports NULL deref, the other one that reports Potential-null-reference.
The report is: 
```
...cpp:184:49: runtime error: load of null pointer of type double
```
First, this is one not 'potential', but a real null deref. 
Second, there is no point in reporting such NULL deref in two different ways. 

We should only leave the UBSAN reports that show "potential-null-reference".
Not sure if it's easy w/o changing ubsan. 

(not a huge deal, but we seem to have a few dups like this)

**Comment by inferno-chromium** [comment]
Only option i see is to disable noisy UBSan's null feature. On clusterfuzz, we can group these two crash types, but then we have to also prioritize null crasher vs potential null crasher which brings us the question why we detect potential null crasher in first place.

@Dor1s - thoughts ?

**Comment by Dor1s** [comment]
I think that we shouldn't disable `-fsanitize=null`, since it's not too noisy and the findings are not useless. Developers sometimes write code that implies null-derefs, but it works well for them since popular compilers process it in a way that does not lead to real crashes, e.g.:

```cpp
$ cat null_deref.c 
#include <stdio.h>

typedef struct _S {
  int a;
  int b;
  int c;
} S;

int main() {
  int offset = (int)&((S*)0)->c;
  printf("Offset of ->c: %d\n", offset);
  return 0;
}

$ clang null_deref.c -o null_deref && ./null_deref 
Offset of ->c: 8
```

Since null-deref is UB as per the standard, I believe that UBSan reports make total sense:

```bash
$ clang null_deref.c -fsanitize=null -o null_deref && ./null_deref 
null_deref.c:10:31: runtime error: member access within null pointer of type 'S' (aka 'struct _S')
Offset of ->c: 8
```

UBSan reports seem to be correct, as UB is there no matter whether the program crashes or not.

Also, I think it's fine that there is some overlap between NULL-deref crashes and UBSan `null` reports.  We have some overlap between MSan and ASan, for example, when **use-of-uninitialized-value** is a **use-after-free** essentially. We may get two different reports with the same root cause, as both statements are technically correct.

To resolve this particular issue, we can apply **Null-dereference** crash type for signatures like:
* `runtime error: load of null pointer`
* `runtime error: store to null pointer`

and still apply **Potential-null-reference** for other cases (e.g. [reference binding, member call, etc](http://llvm.org/svn/llvm-project/compiler-rt/trunk/test/ubsan/TestCases/TypeCheck/null.cpp) ). How does it sound?

Or we can keep an eye on these crashes a bit more to see how often such duplicates do happen.

**Comment by Dor1s** [comment]
I've uploaded a CL to report read/write as actual null-deref.

**Comment by inferno-chromium** [comment]
This is now fixed, thanks Max.
