### ISSUE TITLE
0 bytes (empty) file causes SEGV in FuzzerMutate.cpp:473

### ISSUE THREAD

**Issue by joachimmetz** [google/oss-fuzz#6222]
A fuzzer finding was reported to me in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37241&q=libyal&can=2 

However taking a closer look the test case is a 0 bytes (empty) file

Which causes a SEGV in lib/fuzzer/FuzzerMutate.cpp:473

Let me know if you need the full stack trace details can also be found in https://oss-fuzz.com/testcase-detail/5740511217451008

**Comment by joachimmetz** [comment]
A similar issue https://github.com/google/oss-fuzz/issues/5857 has been observed before though this looks to be a different code path

**Comment by jonathanmetzman** [comment]
Reposting my comment from #5857 that I mean to write here:

Sorry for not realizing what this is earlier.
I think this because ASAN is buggy on i386. People have reported this to us before:
#2746

I don't have a solution here. I don't think we can invest the resources to fix it. If the bugs are causing too much noise for you, I'd recommend dropping i386 (particularly if you haven't found it is giving you useful i386/32-bit specific bugs.

**Comment by joachimmetz** [comment]
@jonathanmetzman thx for the context, it is fine for now, volume of these have been quite low so far.

Feel free to close this issue then. I'll reference it if I encounter more of these and if the volume becomes too high, I'll drop 32-bit fuzzing. For now I'll keep it in, since the code I'm fuzzing has variation in the 32-bit and 64-bit code paths.
