### ISSUE TITLE
Q: Can't reproduce issue with fuzz target

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#632]
oss-fuzz found [issue 1915](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1915), a Heap-buffer-overflow READ 1.

I *can* reproduce that overflow using `valgrind <fuzz target> < reproducer`.

But afl-fuzz doesn't find any crash, neither with or without ASAN.
Any hints are highly welcome, maybe it's just compiler / flags !?

System:
- Debian unstable amd64
- afl-fuzz 2.36b

Library built with
`CC=afl-clang-fast CFLAGS="-g -O2" AFL_USE_ASAN=1 ./configure`

Fuzzer target built with
`AFL_USE_ASAN=1 afl-clang-fast -g -O2 main.c libwget_xml_parse_buffer_fuzzer.cc -I../lib/ -L../libwget/.libs -Wl,-rpath=../libwget/.libs -lwget -o libwget_xml_parse_buffer_fuzzer`

**Comment by rockdaboot** [comment]
Sorry, have to correct myself. The original reproducer reproduces the issue using the ASAN fuzz target.

I used valgrind to reduce the problem from a 2061 byte to a 3 byte input (valgrind still sees a READ 1 problem). Using this reduced input doesn't trigger afl-fuzz at all. Of course I would like to use the reduced variant as future corpus...

**Comment by kcc** [comment]
You are running the AFL binary with your own main(), right? 
https://gitlab.com/gnuwget/wget2/blob/master/fuzz/main.c
This main() function may not be sufficient to find some buffer overflows as it uses a fixed size stack buffer: 
```
unsigned char buf[64 * 1024];
```

You may want to look at this main() function as a better example:
https://github.com/llvm-mirror/llvm/blob/master/lib/Fuzzer/standalone/StandaloneFuzzTargetMain.c
The difference is that it allocates a heap buffer of the exact needed size. 

For this bug, it's probably not that important because the buffer being overflown is not the input buffer. 

Also, you should not need AFL to reproduce bugs like this, just make a plain build and run it with valgrind, or build with AddressSanitizer.

Depending on your compiler flags or other extra steps the bug may get hidden. 
If you want to repeat the exact build steps that oss-fuzz does, see https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

And I see you've fixed the bug already. Thanks!

**Comment by rockdaboot** [comment]
> This main() function may not be sufficient to find some buffer overflows as it uses a fixed size stack buffer

Ups, I tried to be clever 🤣. Sounds reasonable.

> ... reproducing.md

Each little (local) code change requires a complete build, that that takes awfully long (gnulib ./bootstrap + ./configure + make). What do you suggest here ? A build.sh that checks if these steps are needed ? I am not so into docker yet - is there a possibility to set a variable that can be tested in the build script when executing `python infra/helper.py build_fuzzers ... <source path>` ?

**Comment by kcc** [comment]
ideally, build.sh should be a very thin script that invokes your native build system. 
Here is the "ideal" example: https://github.com/google/oss-fuzz/blob/master/projects/example/build.sh

If so, you won't need to use docker yourself, except maybe for some rare cases

**Comment by rockdaboot** [comment]
Thanks for the 'ideal' example, I re-thought everything and on a pretty good way now (at least it feels good). BTW, the example is not really ideal ... but will eventually open a new issue about it.

The issue is already closed ;-)
