### ISSUE TITLE
Code coverage report unclear

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#638]
Regarding the [New Project Guide](https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md), the code coverage report is generated by (example)
```
$ python infra/helper.py coverage wget2 libwget_robots_parse_fuzzer
```

The report view via http://127.0.0.1:8001/ says 25% code coverage. 
Regarding the corpora that are provided, this is simply much too less.

The code itself is colored orange, green, red and white. While I can intuitively interpret orange and green lines, the red and white seems to be pretty random. How exactly should this be interpreted ?

And it looks wrong - e.g. the corpora contain "User-Agent: *" and "User-Agent: wget2" but the corresponding code block is a mixture of red and white. However I interpret red & white lines, 25% coverage seems wrong. The HMTL file is attached as .zip (no .html upload allowed).

Is this a bug or am I doing it wrong ?

[src_wget2_libwget_robots.c.html.zip](https://github.com/google/oss-fuzz/files/1040794/src_wget2_libwget_robots.c.html.zip)

**Comment by kcc** [comment]
* green: covered
* red: instrumented and never covered. 
* orange: this line has both covered and non-covered code
* white: no information

(I admit our code coverage visualization is very far from perfect)

> And it looks wrong - e.g. the corpora contain "User-Agent: *" and "User-Agent: wget2" but ...

Let me look at the actual coverage data...

**Comment by kcc** [comment]
@oliverchang 
when you run 
```
python infra/helper.py coverage wget2 libwget_robots_parse_fuzzer
```
runs the fuzzer w/o the seed corpus for 60 seconds:

```
Running: docker run --rm -i --cap-add SYS_PTRACE -v /usr/local/google/home/kcc/oss-fuzz/build/out/wget2:/out -v /tmp/tmpDZF7dm:/cov -w /cov -t gcr.io/oss-fuzz-base/base-runner /out/libwget_robots_parse_fuzzer -dump_coverage=1 -max_total_time=60

```

This feature is not supposed to be a full coverage reporting tool, we are unlikely to improve it. 

The coverage that oss-fuzz has is shown [here](https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_wget2_libwget_robots_parse_fuzzer/2017-05-30/f/%2Fsrc%2Fwget2%2Flibwget%2Frobots.c) and as you can see there is much more green 

However, this particular case shows that your fuzz target is hard to crack w/o a corpus and w/o a dictionary. Now, I also see your dictionary, but it's not getting used since it's named incorrectly. 
(should be `libwget_robots_parse_fuzzer.dict`, not `libwget_robots_parse.dict`)

With the dictionary the coverage should be much higher. 
(Hm, Olver, will infra/helper.py coverage pick up the dictionary)?

One more comment: 
libwget_metalink_parse.options and libwget_xml_parse_buffer.options can be removed if you add something like 
```
if (size > 4096) return 0; 
```
to the corresponding fuzz targets.

**Comment by oliverchang** [comment]
> With the dictionary the coverage should be much higher.
(Hm, Olver, will infra/helper.py coverage pick up the dictionary)?

It didn't but after https://github.com/google/oss-fuzz/commit/c093b7101d2a655544a0445132e29ae02034961d it should.

**Comment by rockdaboot** [comment]
Thanks for the size/max_len trick.

Meanwhile I integrated the fuzz targets closer into the upstream build process. So now I can 'make check' it, with or w/o sanitizers, valgrind, coverage using the fuzz corpora. The gcc/lcov coverage report is perfect (no comparison to clang's report).

Next step is to integrate the crash/leak corpora from oss-fuzz into the standard test procedure to avoid regressions. Starts to make fun...
