### ISSUE TITLE
Badge status is not updated

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#6403]
The @ImageMagick project is part of OSS fuzz and has had successful builds the last week: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#imagemagick. But the badge is still claiming the build is failing:
![](https://oss-fuzz-build-logs.storage.googleapis.com/badges/imagemagick.svg)

Am I missing something or is this an issue in the oss-fuzz platform?

**Comment by inferno-chromium** [comment]
So, coverage build started failing a day back. Fuzzing build is fine.

For coverage build, go to https://oss-fuzz-build-logs.storage.googleapis.com/index.html#imagemagick, click on "Coverage Builds" tab, and then scroll down to imagemagick. Failure log is
https://oss-fuzz-build-logs.storage.googleapis.com/log-5848f60f-f8d1-4343-83ad-97ab586d425a.txt

An OSS-Fuzz bug is not filed yet since we wait for 2 consecutive builds to fail before a new bug is filed. It should get filed tmrw if the failure continue. 

You can reproduce using
```
Step #7: ********************************************************************************
Step #7: Code coverage report generation failed.
Step #7: To reproduce, run:
Step #7: python infra/helper.py build_image imagemagick
Step #7: python infra/helper.py build_fuzzers --sanitizer coverage imagemagick
Step #7: python infra/helper.py coverage imagemagick
Step #7: ********************************************************************************
```

**Comment by dlemstra** [comment]
Thanks for your response @inferno-chromium. It looks like we are hitting some kind of build timeout limit. Would it be possible to increase this for certain projects? Our project has a lot of external dependencies and that is why it takes a lot of time to build.

**Comment by inferno-chromium** [comment]
> Thanks for your response @inferno-chromium. It looks like we are hitting some kind of build timeout limit. Would it be possible to increase this for certain projects? Our project has a lot of external dependencies and that is why it takes a lot of time to build.

I think 6 hr is the max, can we think of any build optimizations or exclude unneeded test targets or fuzzers ?

@oliverchang for any other ideas.
