### ISSUE TITLE
What about Google's AOSP/Android?

### ISSUE THREAD

**Issue by jawz101** [google/oss-fuzz#655]
Why is Android/AOSP not listed?

**Comment by kcc** [comment]
"not listed" where?

**Comment by jawz101** [comment]
I was wondering if it could be included as a project to scan.  Considering both this app and that product are Google products, I wonder why it is not a scanned project.

**Comment by kcc** [comment]
Sure, any target from Android/AOSP would be welcome on OSS-Fuzz. 
Someone just needs to do this. :)

**Comment by jawz101** [comment]
Wouldn't Google need to submit the protect, considering a request requires a point of contact?  And, since this project is made by Google and Android is as well... this project's owner is a co-worker of the Android maintainer.  I'm just some person.

Like, you're literally a contact at that company.


I don't know how to say it another way.

**Comment by stephenhines** [comment]
Fuzzing "AOSP" doesn't make sense. AOSP is an entire operating system + userland + more. There are many components of AOSP that are fuzzed internally by our security folks, so it isn't accurate to say that AOSP isn't being fuzzed just because it isn't part of the public oss-fuzz project. If people want to see public fuzzing of sub-components, they can write/modify configurations to do so.
