### ISSUE TITLE
Uploading artifacts fails with Access to the path is denied

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#6557]
We are using standard github actions for fuzzing/uploading crashes:
https://github.com/google/syzkaller/blob/ce697b49e30d07d5c08d0849410efc8797f1cb66/.github/workflows/oss-fuzz.yml

Recently the upload action started to fail with:
```
Uploading artifact 'artifacts' from '/home/runner/work/syzkaller/syzkaller/out/artifacts' for run #4128
Uploading 2 files
File error 'Access to the path '/home/runner/work/syzkaller/syzkaller/out/artifacts/tmp0z_9zgjq' is denied.' when uploading file '/home/runner/work/syzkaller/syzkaller/out/artifacts/tmp0z_9zgjq'.
Associated artifact artifacts (27950460) with run #4128
Error: Access to the path '/home/runner/work/syzkaller/syzkaller/out/artifacts/tmp0z_9zgjq' is denied.
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.283.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```
https://github.com/google/syzkaller/runs/3800247729?check_suite_focus=true

**Comment by jonathanmetzman** [comment]
Thanks. I'll look into this.

**Comment by jonathanmetzman** [comment]
tmp0z_9zgjq is weird. It looks like the name of a temporary file/directory made by python.

**Comment by jonathanmetzman** [comment]
OK. I'm pretty sure I know what's going on here.
[Here](https://github.com/google/syzkaller/runs/3800247729?check_suite_focus=true#step:5:117) we see the libFuzzer run gets interrupted .
[This means libFuzzer will exit with a nonzero exit code](https://github.com/llvm/llvm-project/blob/7c921753e0f5e95aadee8728ddbcb843a272b48a/compiler-rt/lib/fuzzer/FuzzerLoop.cpp#L271).
When libFuzzer exits with a nonzero returncode and doesn't write a testcase (as is the case here, I assume it's because libclusterfuzz is reaching the timeout for libFuzzer and thus sending sigterm to it), libClusterFuzz [will make an empty testcase](https://github.com/google/clusterfuzz/blob/master/src/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py#L304) using `mkstemp`.
That temp file `is readable and writable only by the creating user ID` according to the python docs.

There are two ways to fix this.
1. Make sure artifacts are world readable.
2. Make ClusterFuzz handle when it shuts down libFuzzer properly.

I think 2 is better because I think this issue is also affecting CF.

**Comment by jonathanmetzman** [comment]
I was able to get the tempfile with this short snippet:
```
import clusterfuzz.environment
import clusterfuzz.fuzz

target_path = '/tmp/report_fuzzer'
engine = 'libfuzzer'

with clusterfuzz.environment.Environment(engine,
                                         'address',
                                         target_path,
                                         interactive=True):
    engine_impl = clusterfuzz.fuzz.get_engine(engine)
    options = engine_impl.prepare('/tmp/corpus2', target_path, '/tmp')
    options.merge_back_new_testcases = False
    options.analyze_dictionary = False
    result = engine_impl.fuzz(target_path, options,
                              '/tmp/working', 1)
```

**Comment by jonathanmetzman** [comment]
@oliverchang WDYT?
