### ISSUE TITLE
CFL: Coverage Report job not recognizing fuzz targets with go fuzzer

### ISSUE THREAD

**Issue by mpherman2** [google/oss-fuzz#6768]
Logs:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/test-infra-cfl-coverage-report/1456224223201595392
env:
      - name: MODE
        value: coverage
      - name: REPO_NAME
        value: test-infra
      - name: SANITIZER
        value: coverage
      - name: CLOUD_BUCKET
        value: gs://prow-cifuzz-test/
      - name: CFL_PLATFORM
        value: prow
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
      - name: GOPROXY
        value: https://proxy.golang.org

To see file structure hit Artifacts on top of logs page. Fuzzer exists (and local tests show it is executable)

**Comment by jonathanmetzman** [comment]
I figured out why this.
Go fuzz targets don't seem to have LLVMFuzzerTestOneInput so they [fail this check](https://github.com/google/oss-fuzz/blob/master/infra/utils.py#L166).
https://github.com/google/oss-fuzz/issues/5777 tried to consolidate fuzzer detection but I don't think it will work here. I think coverage targets need to use the really simple check done in the coverage script ([here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/coverage#L22)) because of this issue.
