### ISSUE TITLE
CIFuzz can't be pinned to a specific version

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#6836]
Currently CIFuzz is the only action I use on a regular basis that can't be pinned to specific versions and that makes `scorecard` very unhappy:
```
      "details": [
        "Warn: no lock files detected for a package manager",
        "Warn: dependency not pinned by hash (job 'fuzzing'): .github/workflows/cifuzz.yml:37",
        "Warn: dependency not pinned by hash (job 'fuzzing'): .github/workflows/cifuzz.yml:44",
        "Info: GitHub-owned actions are pinned",
```
It would be great if was possible to jump from one version to another automatically with Dependabot to make it easier to prevent CI from accidentally pulling breaking changes.

**Comment by evverx** [comment]
Just to clarify, I can make that warning go away by pointing it to the latest SHA an let dependabot update it daily to follow the master branch but since the OSS-Fuzz repository receives updates often it would lead to a lot of PRs opened by Dependabot and I'd like to avoid that :-) so it would be great if the action could be pointed to a version of some kind. It's probably kind of related to https://github.com/google/oss-fuzz/issues/6324

**Comment by jonathanmetzman** [comment]
CC @oliverchang

**Comment by jonathanmetzman** [comment]
What would this look like? instead of running build_fuzzers@master you run build_fuzzers@v1 ?
Because projects have dependencies in the OSS-Fuzz repo I don't think it's a good idea to ever run CIFuzz on anything but HEAD.
That said, I suppose I could have an action that updates the v1 tag everytime there is a commit to the OSS-Fuzz repo.
I really don't know how this benefits security though, but we can make scorecard happy Igues.

**Comment by evverx** [comment]
> I really don't know how this benefits security though, but we can make scorecard happy I guess.

I don't think it does :-) I'm more interested in catching issues during updates. The latest example of what it looks like is https://github.com/systemd/systemd/pull/21410

> Because projects have dependencies in the OSS-Fuzz repo I don't think it's a good idea to ever run CIFuzz on anything but HEAD

That's a good point. Given that I switched from daily updates to weekly updates I guess I would have no problem with receiving PRs following the tip of OSS-Fuzz once a week.

I think the issue can be closed.

Thanks!

**Comment by evverx** [comment]
The correct link was https://github.com/systemd/systemd/pull/21340

**Comment by evverx** [comment]
> Suppose you change the dockerfile in OSS-Fuzz repo

I kind of always wanted to move it to the systemd repository because well it feels weird that I can change `build.sh` (which simply runs tools/oss-fuzz.sh) and test it with CIFuzz but Dockerfile is somehow different. @jonathanmetzman before I break anything I wonder if the following patch would be fine by OSS-Fuzz
```diff
diff --git a/projects/systemd/Dockerfile b/projects/systemd/Dockerfile
index 09369d2b..ff2be27f 100644
--- a/projects/systemd/Dockerfile
+++ b/projects/systemd/Dockerfile
@@ -15,11 +15,6 @@
 ################################################################################

 FROM gcr.io/oss-fuzz-base/base-builder
-RUN apt-get update &&\
-    apt-get install -y gperf m4 gettext python3-pip \
-        libcap-dev libmount-dev libkmod-dev \
-        pkg-config wget &&\
-    pip3 install meson ninja jinja2
 RUN git clone --depth 1 https://github.com/systemd/systemd systemd
 WORKDIR systemd
 COPY build.sh $SRC/
```

**Comment by evverx** [comment]
Looks like Dependabot can't follow the master branch automatically without versions of some kind

**Comment by evverx** [comment]
In the meantime I opened https://github.com/google/oss-fuzz/pull/6858, which I think should make it unnecessary for the systemd project to change Dockerfile ever again hopefully

**Comment by cpovirk** [comment]
As Google rolls out https://docs.zizmor.sh/ more widely, I've been anticipating hearing about this there in the form of a finding like this one, which I see during a local `zizmor` run:

```
error[unpinned-uses]: unpinned action reference
  --> .github/workflows/cifuzz.yml:14:13
   |
14 |       uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ action is not pinned to a hash (required by blanket policy)
   |
   = note: audit confidence → High

error[unpinned-uses]: unpinned action reference
  --> .github/workflows/cifuzz.yml:21:13
   |
21 |       uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ action is not pinned to a hash (required by blanket policy)
   |
   = note: audit confidence → High
```

I haven't yet seen it in CI for that repo, https://github.com/google/gson, but I think that's mostly because that repo doesn't yet appear to run "GitHub Actions Scan" at all. \[edit: Or [maybe it does](https://github.com/google/gson/actions/runs/30754497470/job/91514300047)?\] I'd expect that to change.

It looks like the finding can be suppressed with `# zizmor: ignore[unpinned-uses]` (and maybe alternatively with [`config.policies`](https://docs.zizmor.sh/audits/#rulesunpinned-usesconfigpolicies)), so that might be what we do in the future.

My comments above are of course all focused on the `zizmor` finding and not on [the security-focused spirit behind it](https://docs.zizmor.sh/audits/#unpinned-uses). Admittedly, `zizmor` itself documents:

> If the upstream repository is trusted, then symbolic references are often suitable. However, if the upstream repository is not trusted, then actions should be pinned by SHA reference.

So there's a question of to what extent some people are nervous to treat a Google repo as trusted. If nothing else, it seems valuable to pin to a specific commit so that Dependabot will apply its [new default](https://github.blog/changelog/2026-07-14-dependabot-version-updates-introduce-default-package-cooldown/) of a three-day [cooldown period](https://blog.yossarian.net/2025/11/21/We-should-all-be-using-dependency-cooldowns), rather than picking up a new version immediately in the unlikely event of a repo compromise.

**Comment by jonathanmetzman** [comment]
Pinning CIFuzz can break projects if they are on any sort of delay. For projects that rarely modify their integration in Google/oss-fuzz it's probably unlikely to matter, but the only way to keep using CIFuzz securely without experiencing weird errors is to drop the privileges granted to cifuzz so that a compromise of CIFuzz cannot harm you.

**Comment by evverx** [comment]
> the only way to keep using CIFuzz securely without experiencing weird errors is to drop the privileges granted to cifuzz so that a compromise of CIFuzz cannot harm you

The problem is that it's necessary to add policies like https://github.com/avahi/avahi/blob/master/.github/zizmor.yml to silence zizmor. That being said I of course agree that since it's read-only it doesn't matter much whether it's pinned or not in practice.

**Comment by jonathanmetzman** [comment]
Actually thinking about this again, it may be OK to pin the action because the action pulls the unpinned docker image that contains the latest oss-fuzz code. So while pinning does 0 for security, I think it won't break users either.

**Comment by evverx** [comment]
As far as I can remember Dependabot struggles with hashes that point to the master branch without tags so I wouldn't do that just to make zizmor happy.

**Comment by Marcono1234** [comment]
> As far as I can remember Dependabot struggles with hashes that point to the master branch without tags so I wouldn't do that just to make zizmor happy.

Yes, at least for these projects which had pinned `google/oss-fuzz` for a while it seems that pinned version hadn't been updated:
- https://github.com/google/brotli/blame/master/.github/workflows/fuzz.yml
- https://github.com/google/double-conversion/blame/master/.github/workflows/cifuzz.yml
- https://github.com/google/jpegli/blame/main/.github/workflows/fuzz.yml

(could also have other reasons though)

**Comment by evverx** [comment]
> (could also have other reasons though)

I have to admit I don't fully understand the logic behind Dependabot updates in those cases. I have an unversioned action that is supposed to be pinned to specific hashes to be in sync with the repository where it's used but Dependabot randomly updated it and those updates were bogus and annoying so it just ended up being turned off for that specific action in the Dependabot config. It was before cooldowns were introduced though so I can't even imagine what it does with unversioned actions when the cooldown is set to, say, 14 days. Does it look at the age of the latest commit at the time it happens to run at? I don't know.
