### ISSUE TITLE
"Random" build failures with GDAL and AFL

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#6844]
I've notice recently frequent reports about build failures that are closed the next day or so, and reappear a few days after, without any change in the GDAL code base being specifically made to address those issues. This is a bit irritating and I'd wish a reliable solution could be found. Last in date is https://oss-fuzz-build-logs.storage.googleapis.com/log-eabe1d3c-d96b-44c1-9b80-dced4693e198.txt / https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41093. The build itself succeeds but the "performing bad build checks" not.
There's this message " Possibly the target requires a huge coverage map and has CTORS. Retry with setting AFL_MAP_SIZE=10000000." . Huge coverage map wouldn't be super surprising given the size of GDAL and the dependencies we build from source. If that's a reasonable track to attempt, where should this environment variable be defined ?

**Comment by DavidKorczynski** [comment]
I believe this is related to: https://github.com/google/oss-fuzz/issues/6839

**Comment by DavidKorczynski** [comment]
The issue with unreliable builds is most likely because AFL builds has nondeterminism when building a project, and likely some of the settings are causing GDAL to fail whereas others don't:
https://github.com/google/oss-fuzz/blob/a21768ce6a5056d27f82b2f412c86261ad2dc8d0/infra/base-images/base-builder/compile_afl#L52-L73

It seems like there are two issues here:
- nondeterminism in builds causing unreliability
- in some settings AFL builds fail.

I guess both should be solved but the unreliable aspect seems to be more of an OSS-Fuzz thing to solve. @jonathanmetzman do you have thoughts here?

**Comment by vanhauser-thc** [comment]
the issue is from 2 days ago, so likely did not yet have the fix. is it still happening?

**Comment by DavidKorczynski** [comment]
This is a build log from 19/11/2021: https://oss-fuzz-build-logs.storage.googleapis.com/log-0555c90b-ccf1-4170-bd39-2f98ccacc808.txt and the issue persists

This issue https://github.com/google/oss-fuzz/issues/6839 was resolved though - the two most recent PHP builds passed

**Comment by vanhauser-thc** [comment]
yes, this was a different issue, fixed with #6866

**Comment by vanhauser-thc** [comment]
is he issue fixed now?

**Comment by rouault** [comment]
> is he issue fixed now?

it seems so. Closing
