### ISSUE TITLE
Shared corpus sets?

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#693]
Hi.

The following is somewhat simplified:
Let's suppose there is a library `X`.
It consists of two parts, `A` and `B`.
Library is feed with some data, and depending on the data, either part `A` or part `B` is called.

Now, in context of fuzzing, to have better coverage/etc, it makes sense to have three different fuzzing targets (`X_fuzz`, `A_fuzz`, `B_fuzz`).
All of them will feed exactly the same input into it's designated target.
However, that currently results in three separate corpus sets...

I would think it makes sense to be able to tell it to share corpus sets, because that would avoid work duplication - i.e. if `A_fuzz` has already found some interesting corpus that triggers some part of the library `X`; `X_fuzz` would still need to find that very same corpus on it's own.

Having only the `A_fuzz` and `B_fuzz` is not really an option, because there is always some logic in the library `X`, which decides whether to call `A` or `B`, which needs to be fuzzed too, and so on.

The obvious downside is that for `-merge`, each fuzzing target would need to be called, to see if any of them consider new corpus as interesting.

**Comment by Dor1s** [comment]
That seems reasonable to me. We do `-merge=1` automatically once a day, so each target has a minimized corpus after that. Due to that, we still have to store 3 different corpus directories, but this is not an issue. As for sharing the corpus, we have 3 options:

1) do it manually once in a while :)

2) rely on global cross-pollination (we try to use corpus from different targets), but it wouldn't exchange the corpus between X, A and B too often, as we have hundreds of fuzz targets

3) implement some automated and scalable logic for "corpus groups", so it would be possible to mark different fuzz targets as a one corpus group, so they would take corpus from each other on a regular basis

**Comment by nsajko** [comment]
Just for the sake of cross-referencing information, I am linking the related issue https://github.com/google/oss-fuzz/issues/2681

**Comment by inferno-chromium** [comment]
Corpora is crosspollinated with other fuzz targets in same project.
