### ISSUE TITLE
kubernetes - fuzzers do not seem to run and 404 on stats page

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#6980]
Getting "Got error with status: 404 No stats." on fuzzer stats page in the dashboard on oss-fuzz.com.

Looks like similar issue as https://github.com/google/oss-fuzz/issues/6857 but this time for Kubernetes.

@oliverchang PTAL.

**Comment by jonathanmetzman** [comment]
@oliverchang Looks like another disk issue: https://pantheon.corp.google.com/logs/query;query=kubernetes;cursorTimestamp=2021-12-07T20:58:36.952358266Z?project=clusterfuzz-external
https://pantheon.corp.google.com/logs/query;cursorTimestamp=2021-12-07T20:58:36.952358266Z;query=kubernetes%0Atimestamp%3D%222021-12-07T20:58:14.674061880Z%22%0AinsertId%3D%22g4pbhlvbnwu7gu31n%22?project=clusterfuzz-external

Wonder if this is related to go static linking instead of dynamic.

**Comment by oliverchang** [comment]
Bumped the disk to be the same size as istio.
