### ISSUE TITLE
Ensure widespread breakages do not happen due to clang rolls or AFL++ rolls.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6986]

**Comment by DavidKorczynski** [comment]
Continue to use `FORCE_OUR_REVISION=1` and have some automated procedure for updating but only if builds pass may be an interesting starter?

Also, wasn't the issues with Rust coverage and builds earlier this year due to Clang updates? Does it make sense to think about that in this context, i.e. perhaps come up with something that is more robust across all the various tools that depend on clang (and perhaps different versions of Clang).
