### ISSUE TITLE
How to make issues private?

### ISSUE THREAD

**Issue by howardjohn** [google/oss-fuzz#7061]
We are having issues where we get false negative 'This bug has been fixed. It has been opened to the public.', which is opening issues to the public when we do not want them to. We are worried this may lead to public exposure of security sensitive information, and cannot find info on how to keep an issue private.

Is there a way we can mark issues as "do not open publicly"?

**Comment by DavidKorczynski** [comment]
There is not automatic way of doing this - atm maintainers simply ask here to get an issue closed and this will then be done by one of the OSS-Fuzz maintainers.. See here for an example: https://github.com/google/oss-fuzz/issues/6625

**Comment by howardjohn** [comment]
That seems... extremely problematic? Once it's public once it's too late - anyone can trivially watch issues. Opening a GitHub issue also brings public attention that maintainers are concerned about a particular issue. Far worse if the issue had comments describing more details, etc about a vulnerability. 

This issue makes me pretty uncomfortable using OSS-fuzz.

**Comment by DavidKorczynski** [comment]
@inferno-chromium @jonathanmetzman @oliverchang do you have some thoughts here? Given that there are some issues that will be labelled as false negatives and thus opened it would be nice to have some guards in place that users of OSS-Fuzz can use automatically?

**Comment by inferno-chromium** [comment]
@howardjohn - i have given issue edit permission to your account. To restrict the bug, please add "Restrict-View-EditIssue" label to that bug and it will be hidden from then on.

**Comment by DavidKorczynski** [comment]
@howardjohn - Closing this as I believe it has been resolved. Please reopen if not.

**Comment by howardjohn** [comment]
Thanks for all the help here - very much appreciated. It would be ideal to never automatically disclose issues marked as `security` IMO, but this will work for us

**Comment by oliverchang** [comment]
To clarify the disclosure behaviour:
- We only disclose the reproducer 30 days after the issue is marked as fixed.
- The full stacktrace is never disclosed publicly. 

Does this alleviate some of your concerns? That said, we don't usually see this behaviour (false positives with closing) with other projects. Are these targets somehow inherently flaky in some way?

**Comment by AdamKorcz** [comment]
I think this happened because Istio bumped the latest go-fuzz-headers which has an update on how fuzz data is consumed. Istio commit https://github.com/istio/istio/pull/42745 updates go-fuzz-headers. The update in go-fuzz-headers which I think is the relevant one is https://github.com/AdaLogics/go-fuzz-headers/commit/fc0ce66dbb85eaefedb39fe334ed4101326fb903#diff-085e2330bdc0dc205f33ed49007f53508335e847bd122d70b29ba8835349bc82L377-L389 

The library that OSS-Fuzz uses to run native Go fuzzers uses go-fuzz-headers but this has been pinned: https://github.com/AdamKorcz/go-118-fuzz-build/blob/5330a85ea6528bb00bea0417b6d61f30deb61f2c/go.mod#L6, so OSS-Fuzz does not pull in the changes by default.

As I see it there are two types of breaking changes in go-fuzz-headers: those that modify the semantics of how data is handled and those that modify the API. The semantic changes are mainly a concern for cases like this, where issues are automatically publicly released, however, from a go-fuzz-headers perspective, would it help with explicit release cycles that indicate if e.g. the former type of breaking change happens?

On the OSS-Fuzz side, I think it would be nice to have some guards in place. We've got some other experience where issues are released that is not fixed, it's often cases such as:

- The fuzz harness itself was changed (renamed too, I think) while there were some outstanding issues.
- Code changes irrelevant to a given issue were pushed upstream, and these caused the given testcase to not retrigger the issue.
