### ISSUE TITLE
Testcase/crash in inconsistent state

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#7095]
https://oss-fuzz.com/testcase-detail/6195749197578240 still shows the "Create Issue" button although it already links to an issue number. That issue number is already used by a different crash from a different fuzzer. The only similarity I see is that both fail to allocate memory.

What should I do with this testcase now?

**Comment by oliverchang** [comment]
This particular testcase was grouped into the existing issue (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30924) due to our stacktrace similarity detection. If you click "Create Issue", it will create a new, separate issue from the existing one. 

You can ignore this one. If this still reproduces after the existing issue is fixed, it will be auto filed into its own issue.
