### ISSUE TITLE
Fixed issues still being opened.

### ISSUE THREAD

**Issue by mity** [google/oss-fuzz#7116]
I'm not sure whether this is really a bug or my poor understanding of how oss-fuzz actually works.

In the past days, I've made some commits into [MD4C](https://github.com/mity/md4c) repo addressing some of the issues identified by oss-fuzz. I would expect that the respective testcases of open issues are retried in a reasonable fashion to verify whether the problem is still there and, if so, close the issue (or at least those issues which were 100% reproducible). That did not happen though.

So I tried enforcing that manually by clicking on the small refresh icon next to the "Crash Stacktrace" on the Detailed Report of relevant issues (the one saying "Update last testing stacktrace using trunk build" in the popup label). That made some visible effect for many of the issues (e.g. 31343) as these lines were added into the Crash Stacktrace:

```
------------- Last Tested Stacktrace on revision c058e82c6a939f591059672dab08ddd0d4ce416e (1 lines) --------------
No crash occurred.
```

However status of the issues has been left unchanged and it's still "New" and not even a comment was added at the issue page.

Another related concern is that the revision [c058e82c6a939f591059672dab08ddd0d4ce416e](https://github.com/mity/md4c/commit/c058e82c6a939f591059672dab08ddd0d4ce416e) used in this manual verification was not the latest one available in the MD4C repo at the time and I'm wondering why the latest commit [4358c40ab740ed13b12921464467e6a90a689950](https://github.com/mity/md4c/commit/4358c40ab740ed13b12921464467e6a90a689950) was not used instead. (The latest commit should address the issue 43522.)

Am I doing anything in a wrong way?

**Comment by DavidKorczynski** [comment]
Looking at things, the commit  4358c40ab740ed13b12921464467e6a90a689950 is 3 hours old. In general, the OSS-Fuzz backend will use an update version within 24 hours, so give it a bit of time and it will rebuild the project using the latest upstream commit and recognise the issue is fixed. 

For each of the issues on the oss-fuzz dashboard you can see a "LAST TESTED REVISION" box, which will indicate which is the latest commit used for testing the issue. For example https://oss-fuzz.com/testcase-detail/5469403431436288 last used the following revision  cf5fe0c8c2d9d3398aa110cc66a14b50fd487479 - which still holds the bug according to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43473 

I think it's just a waiting game atm. 

I think the bot itself will have to discover a fix has been deployed rather than relying on the manual button click. Am not sure if manually re-triggering a testcase that shows the issues is fixed will also result in the database being updated with the fix, maybe @oliverchang or @jonathanmetzman can answer this?

**Comment by jonathanmetzman** [comment]
Oliver might know about retrying closing the issue. I don't.
Other than that, I can confirm what David said. Builds are done once a day, so you may have to wait up to 24 hours (or longer if the build is broken) for fixes to be confirmed by OSS-Fuzz.

**Comment by mity** [comment]
Ok, thank you for the explanation.

I was mainly afraid whether the revision was refused due the red cross from the CI checks on the gihub side (but that one comes only from slightly less good code coverage). No problem with the 1-day delay (once knowing it) so closing.
