### ISSUE TITLE
better de-duplication or throttling for stack-overflows

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#718]
We have a large inflow of stack-overflow reports that are apparently duplicates. 
E.g. see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2540 and ~50 similar reports. 
If we can't effectively de-dup those we should at least throttle them (e.g. don't file more than N stack-overflow bugs per target, until the old ones are fixed).

**Comment by oliverchang** [comment]
It seems like most of these are actually grouped on ClusterFuzz. Perhaps we could address this by giving more time for group task to complete before filing? @inferno-chromium

**Comment by kcc** [comment]
@epilk FYI

**Comment by oliverchang** [comment]
I believe this particular instance should no longer occur, since we now always do grouping before filing, and the stack overflows that were filed in this case all ended up being grouped after we filed. 

This may still happen though, for cases where grouping fails, but I'm not sure how likely this is. 

@inferno-chromium what do you think? is there anything left to do here, or should we close this for now?

**Comment by inferno-chromium** [comment]
Yes right, this shouldn't happen anymore since we do this every 2 hrs and we do grouping before filing in a sequential way. If we see this more often, we can look more, but grouping usually works for 99% cases unless we see something that just changes stack very randomly.
