### ISSUE TITLE
An auto-check for missing files?

### ISSUE THREAD

**Issue by Alan32Liu** [google/oss-fuzz#7224]
[Pull Request #7191](https://github.com/google/oss-fuzz/pull/7191) forgot to include a critical file (`$GOPATH/ossfuzz_coverage_runner.go`) and caused the failure of [PR #7222](https://github.com/google/oss-fuzz/pull/7222) later, yet it still passed all auto-checks.

How about adding an auto-check to ensure a list of critical files are present at where we need them?

**Comment by jonathanmetzman** [comment]
What would this check look like?
Note that our current tests would have caught this if you had modified an existing image instead of a new one: https://github.com/google/oss-fuzz/blob/master/infra/ci/build.py#L218

Our existing checks rebuild changed dockerfiles and then a canary project to check it worked (though the canary is not a go project).

**Comment by Alan32Liu** [comment]
Ah, I see...
Should I add `base-builder-go-codeintelligencetesting` in that list, like in [base_images.py](https://github.com/google/oss-fuzz/blob/057e2f121b9d2675359d10a729b5397484fc8b90/infra/build/functions/base_images.py#L28)?

**Comment by jonathanmetzman** [comment]
If you'd like. I don't know how long we will be using this image, if it is less than a week I wouldn't really bother.

**Comment by Alan32Liu** [comment]
Sure : )
