### ISSUE TITLE
Coverage build failures without changes to project

### ISSUE THREAD

**Issue by tysmith** [google/oss-fuzz#7232]
It is common to receive coverage build failure notifications from projects that have not changed since the previous successful build. Usually within a few days the issue is marked fixed.

@baumanj mentioned that he is usually not sure whether there a legitimate issue worth investigating or if he should just wait. He also mentioned that he is worried that if he filters the notifications issues might get missed.

**Comment by evverx** [comment]
I was going to open an issue about recent coverage failures but it seems this issue was most likely prompted by them as well. Since yesterday `systemd`, `selinux` and other projects have been failing to unpack their corpora with something like
```
Step #5: unzip:  cannot find zipfile directory in one of /corpus/binpolicy-fuzzer.zip or
Step #5:         /corpus/binpolicy-fuzzer.zip.zip, and cannot find /corpus/binpolicy-fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for binpolicy-fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: [/corpus/secilc-fuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/secilc-fuzzer.zip or
Step #5:         /corpus/secilc-fuzzer.zip.zip, and cannot find /corpus/secilc-fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for secilc-fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

**Comment by evverx** [comment]
> It is common to receive coverage build failure notifications from projects that have not changed since the previous successful build. Usually within a few days the issue is marked fixed.

I think it would be great if OSS-Fuzz could keep track of commits used to build projects and ignore transient failures like that. It wouldn't have helped in the case of systemd because it changed but other projects that are changed once a week or so could benefit from that.

**Comment by jonathanmetzman** [comment]
> It is common to receive coverage build failure notifications from projects that have not changed since the previous successful build. Usually within a few days the issue is marked fixed.
> 

Sorry about that. We've been making some changes to the build infra lately.
Which project is this for? I'd be happy to investigate what the issue is.
I fixed an issue recently https://github.com/google/oss-fuzz/pull/7229 that affected no C/C++ projects, maybe your project was affected?


> @baumanj mentioned that he is usually not sure whether there a legitimate issue worth investigating or if he should just wait. He also mentioned that he is worried that if he filters the notifications issues might get missed.

Sorry, we're sensitive to the fact that false positives can cause devs to disengage and want these to be as low as possible.

**Comment by jonathanmetzman** [comment]
> > It is common to receive coverage build failure notifications from projects that have not changed since the previous successful build. Usually within a few days the issue is marked fixed.
> 
> I think it would be great if OSS-Fuzz could keep track of commits used to build projects and ignore transient failures like that. It wouldn't have helped in the case of systemd because it changed but other projects that are changed once a week or so could benefit from that.

We recently changed our infra to only notify devs after 3 consecutive failures. Did you get an email about the failures or did it just show the failure on https://oss-fuzz-build-logs.storage.googleapis.com/index.html ?

**Comment by evverx** [comment]
@jonathanmetzman The badges in the README files turned "yellow": [![OSS-Fuzz Status](https://oss-fuzz-build-logs.storage.googleapis.com/badges/systemd.svg)](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#systemd).

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman The badges in the README files turned "yellow": [![OSS-Fuzz Status](https://camo.githubusercontent.com/b5a41d6090ea2b668442c113f5e261f3384a808bc6d9849a14979061135fc14c/68747470733a2f2f6f73732d66757a7a2d6275696c642d6c6f67732e73746f726167652e676f6f676c65617069732e636f6d2f6261646765732f73797374656d642e737667)](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#systemd).

Thanks for pointing this out. @oliverchang

**Comment by jonathanmetzman** [comment]
@evverx The latest coverage build for systemd that I kicked off seemed to pass. Might be a day before this is reflected in the badge.

**Comment by tysmith** [comment]
> Sorry about that. We've been making some changes to the build infra lately. Which project is this for? I'd be happy to investigate what the issue is. I fixed an issue recently #7229 that affected no C/C++ projects, maybe your project was affected?

@jonathanmetzman in this case it was [mp4parse-rust](https://github.com/google/oss-fuzz/tree/master/projects/mp4parse-rust).

**Comment by jonathanmetzman** [comment]
There seems to clearly be something wrong with that project for at least a week now.
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#mp4parse-rust
I'm surprised it ever passes at all. I'll take a look at some other rust projects and others and see if they have similar issues and try to figure out root cause and how to fix this.

**Comment by baumanj** [comment]
> We recently changed our infra to only notify devs after 3 consecutive failures. Did you get an email about the failures or did it just show the failure on https://oss-fuzz-build-logs.storage.googleapis.com/index.html ?

I got emails. There have been [about 12 of these since last April for mp4parse-rust](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=mp4parse-rust%3A%20Coverage%20build%20failure&can=1), none of which I think were indicative of issues in the repo being fuzzed.

> Sorry, we're sensitive to the fact that false positives can cause devs to disengage and want these to be as low as possible.

Yeah, it's getting into [normalization of deviance](https://en.wikipedia.org/wiki/Normalization_of_deviance) territory, which is why I raised the issue with @tysmith. Thank you for recognizing the importance.

If there _is_ something that can be done on our end, that would be great, but so far I haven't been able to figure it out.

**Comment by evverx** [comment]
FWIW I don't think projects can do anything about it because as far as I can tell it usually boils down to rolling out various OSS-Fuzz changes (including clang rolls) without testing them in a testing environment of some kind. Coverage builds are especially sensitive to that (for example I still have no idea what broke CIFuzz with those absolute paths in coverage reports or why shared libraries put to $OUT broke one day which led to some projects switching to static linking and so on). As far as I know OSS-Fuzz has been somewhat stabilized by addressing issues like https://github.com/google/oss-fuzz/issues/7039 but the oss-fuzz introspector causing all sorts of issues seems to show that it isn't enough.

**Comment by jonathanmetzman** [comment]
>FWIW I don't think projects can do anything about it because as far as I can tell it usually boils down to rolling out various OSS-Fuzz changes (including clang rolls) without testing them in a testing environment of some kind. 

that reasonably describes the issue. A lot can go wrong when we build 500+ projects.

>libraries put to $OUT broke one day 

Ugh, when was this? I don't remember that.

>but the oss-fuzz introspector causing all sorts of issues seems to show that it isn't enough.

Yeah, I'm working on a proper testing environment and less false positives in general.

>but the oss-fuzz introspector causing all sorts of issues seems to show that it isn't enough.

This is true, but I think those have been resolved.

**Comment by jonathanmetzman** [comment]
I don't really consider this a false positive to be honest. I think this fuzzer is sometimes hitting the memory limit.
Since our coverage instances are much beefier than fuzzing instances I think we can up this limit, but if the fuzzer were to get close to the new limit this issue may reoccur.

**Comment by evverx** [comment]
> Ugh, when was this? I don't remember that.

As far as I can remember it is https://github.com/google/oss-fuzz/issues/6524.

> A lot can go wrong when we build 500+ projects.

Agreed. I didn't mean to say that OSS-Fuzz isn't tested at all or that there is an easy way to fix all the things. Sorry about that.

**Comment by evverx** [comment]
Forgot to mention that the OSS-Fuzz CI doesn't seem to run something like `./infra/helper.py coverage` when PRs are opened so while it can make sure that projects are compiled with `-fsanitize=coverage` it can't verify that coverage reports are more or less fine. For example I accidentally broke the coverage reports of libbpf in https://github.com/libbpf/libbpf/commit/393a058d061d49d5c3055fa9eefafb4c0c31ccc3 but when I opened https://github.com/google/oss-fuzz/pull/7180 the CI didn't complain and https://github.com/google/oss-fuzz/runs/4929964664?check_suite_focus=true was green. I think it took me a few days to notice the breakage and fix it in https://github.com/libbpf/libbpf/commit/ae220adbb22010f109c8e54bdb949416ec424df1 but it would have been better if the OSS-Fuzz CI had caught it because at this point I tend to ignore coverage build failures reported by OSS-Fuzz. Interestingly, ClusterFuzzLite couldn't catch that either in "coverage" mode but it doesn't seem to be related to OSS-Fuzz so I'll try to figure out what happened there and hopefully report it at https://github.com/google/clusterfuzzlite

**Comment by tysmith** [comment]
I'm going to mark this closed now, since I seem to be receiving a consistent failure notification. A separate issue for the specific failure can be opened. That said, @jonathanmetzman is coverage for rust projects supported?
