### ISSUE TITLE
Access denied to oss-fuzz.com for new project

### ISSUE THREAD

**Issue by babenek** [google/oss-fuzz#7285]
Hello.

Should i wait untill #7278  will be merged to get access for https://github.com/google/oss-fuzz?

Currently i've got Access Denied :(

```
You (email=babenek@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Switch account
Logout

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

**Comment by DavidKorczynski** [comment]
Yes, in order to get access to https://oss-fuzz.com your project needs to be accepted (PR merged) first, https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/

Also, FYI, in order to get results you will need to have fuzzers, i.e. a `build.sh` and `Dockerfile` created, and the `project.yaml` file in itself won't make fuzzing happen (https://google.github.io/oss-fuzz/getting-started/new-project-guide/python-lang/)

**Comment by babenek** [comment]
Thanks. 
I'll wait. 
Added fuzzers, but not sure in correct configuration.

**Comment by babenek** [comment]
> Triggered CI over there - we should get some results shortly. Let's close this issue and keep discussion in the PR

Hello. I've finished PR and the main repo is ready for fuzzing.
I suppose, there should be some issues in configurations (paths and so on).
May you run CI again?
