### ISSUE TITLE
massive (and erroneous) WontFixing 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#737]
Almost 100 bugs were closed as WontFix tonight, most of them are not in fact fixed.

**Comment by oliverchang** [comment]
This was caused by a gRPC C extensions import breakage on ClusterFuzz. Still not sure how this happened, as we didn't make any changes here (likely our local development environment changed in some way that was incompatible with our bot environment).

I've re-opened those bugs on monorail, and on ClusterFuzz these bugs should be coming back as "reproducible" soon.

Thanks for noticing!
