### ISSUE TITLE
Inconsistency in sqlite3_ossfuzz

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#750]
I cannot understand behavior of that fuzz target. If I run it with an empty corpus, everything looks fine, I see only libFuzzer's output. But if I take corpus backup and run the target over that corpus, I get lots of excessive logging, e.g.:

```
SQL: [INSERT INTO vacuum_db.sqlite_master SELECT*FROM "main".sqlite_master WHERE type IN('view','trigger') OR(type='table'AND rootpage=0)]
VDBE Trace:
   0 Init             0   29    0               00 Start at 29
  29 Transaction      0    0    0 0             01 usesStmtJournal=0
  30 Transaction      2    1    0 0             01 usesStmtJournal=0
  31 String8          0    9    0 view          00 r[9]='view'
REG[9] =   t4[view](8)
  32 String8          0   10    0 trigger       00 r[10]='trigger'
REG[10] =   t7[trigger](8)
  33 String8          0   12    0 table         00 r[12]='table'
REG[12] =   t5[table](8)
  34 Integer          0   14    0               00 r[14]=0
REG[14] =  i:0
  35 Goto             0    1    0               00
   1 InitCoroutine    7   22    2               00
```

and

```
parser: Shift 'EQ', go to state 97
parser: Return. Stack=[explain with SELECT distinct selcollist from WHERE expr EQ]
parser: Input 'STRING'
parser: Shift 'STRING', go to state 451
parser: Return. Stack=[explain with SELECT distinct selcollist from WHERE expr EQ STRING]
parser: Input 'AND'
parser: Reduce [term ::= STRING], go to state 97.
parser: Shift 'term', go to state 109
parser: Reduce [expr ::= expr EQ|NE expr], go to state 72.
parser: Shift 'expr', go to state 44
parser: Shift 'AND', go to state 100

```

Looks like some of the inputs is changing behavior of fuzz target, e.g. enabling debugging output? Is that possible? //cc @drhsqlite

**Comment by alex** [comment]
Haha, I bet the fuzzer discovers `PRAGMA parser_trace = true`.

**Comment by Dor1s** [comment]
Oh yes, quite a bit:

```
corpus$ egrep -r "PRAGMA parser_trace=" . | wc -l
98
```

**Comment by Dor1s** [comment]
Ok, pros to libFuzzer for being that smart, but now we need a smart way to suppress that behavior, because it's literally crazy amount of logging and probably a significant performance downgrade.

Not sure how interesting it would be to fuzz parser tracer, plus we want to keep target stateless between different inputs...

**Comment by drhsqlite** [comment]
Somehow (not sure right this moment if it is on the SQLite side or on the OSSFuzz side) SQLite is being configured with -DSQLITE_DEBUG for fuzzing.  This is a good and desirable feature, since using SQLITE_DEBUG enables assert() statements in SQLite, which helps to find subtle problems faster.  The undesirable side-effect is that SQLITE_DEBUG also enables language features such as "PRAGMA parser_trace".

So, is the suggestion that SQLite be enhanced to provide a different compile-time option to enable assert() statements and other sanity checking logic, while leaving the debugging language features turned off?

FWIW:  Many projects leave assert() on by default.  But in SQLite, there are so many asserts() in inner loops that leaving them enabled slows the library down by a factor of 3x or more.  So it is important to leave assert() turned off in production builds.

**Comment by Dor1s** [comment]
Thanks Richard! Yes, having asserts enabled without enabling debugging features seems to be the best option.

**Comment by drhsqlite** [comment]
Fixed now.

I had a longer reply, but GitHub ate it when it went down just now.

**Comment by Dor1s** [comment]
Thanks a lot for the prompt fix. I've manually kicked off a fresh build of sqlite3 in order to pick up the fix faster.

**Comment by Dor1s** [comment]
I've verified locally, the issue has been fixed. Closing.
