### ISSUE TITLE
Asses the quality of wolfSSL integration

### ISSUE THREAD

**Issue by levi-wolfssl** [google/oss-fuzz#755]
We over here at wolfSSL have recently added ourselves to OSS-Fuzz, and we're looking for some feedback on how well we've integrated wolfSSL with OSS-Fuzz. We referred to the [Ideal Integration guide](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) when integrating ourself with OSS-Fuzz, but we're hoping for a more concrete assessment.

We know that we haven't followed the guide to the letter. Our main departure form the [Ideal Integration guide](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) is that we've put the fuzz targets into [their own repository](https://github.com/wolfssl/oss-fuzz-targets) rather than into [the wolfSSL source repository](https://github.com/wolfssl/wolfssl). Otherwise, we know that we are presently lacking on coverage. We plan to improve this later.

**Comment by Dor1s** [comment]
Hi @levi-wolfssl, thanks for asking! 

_Disclaimer: I don't think that we did any kind of assessment before, so we don't have a certain approach how to do that. Below are my thoughts and a few suggestions in the end. Other members of OSS-Fuzz project probably will add something or fix me if I'm wrong :)_

Speaking of repositories, our main goal here is to establish fuzz testing as a mandatory part of project development. The same way as developers (or a CI infrastructure) run unit tests before uploading a commit, they would run fuzz tests using some corpus (ideally, a minimized corpus from OSS-Fuzz). No need to execute fuzzers 24/7, just use it with `-runs=0` option and an existing corpus as a part of regression testing.

By the way, why did you decide to put fuzz target into a separate repository? Do you pull it as a submodule into the main repo?

From our side, we provide continuous 24/7 testing on Google Cloud infrastructure, as well as automation of bugs filing, verification etc. So you don't need to find new bugs, but need to set up the regression testing.

Speaking of fuzz targets, the easiest way to estimate its performance is to look at:
1) fuzzer stats: https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-07-26/2017-08-01/fuzzer/libFuzzer_wolfssl_pem_cert/job/libfuzzer_asan_wolfssl

2) performance report (there is a link on the stats page): https://oss-fuzz.com/v2/performance-report/libFuzzer_wolfssl_pem_cert/libfuzzer_asan_wolfssl/latest

For example, existing `pem_cert` fuzz target doesn't have known issues other than `coverage`, which is quite common and usually happens to all targets after some time. At this point, it would be useful to take a look at the coverage report (there is a link on the stats page as well):  https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_wolfssl_pem_cert/latest

There are some issues with visualization (we're working on that!), but the report gives a general understanding about functions and other blocks of code that are covered and are not. It's worth to think why some particular cases are not covered:
* are there any complex conditions that fuzzer cannot discover and satisfy? It would be great to add more seed corpus, or add a dictionary in order to reach those uncovered paths
* are there any arguments / flags that are required to reach uncovered functions? Can we add them to the existing fuzz target, or create a new target for another configuration?
* can we reach uncovered code with the existing fuzz target at all? e.g. existing [fuzz target](https://github.com/wolfSSL/oss-fuzz-targets/blob/master/pem_cert/target.c#L39) calls a single API function, but there are more of them available in wolfSSL

I guess that everything written above might not sound as an assessment, so **below are concrete points that can be improved**:

1) It would be better to have fuzz target(s) in the main repo, so everyone can build them right there by running `make all`, or `make fuzzers`, or whatever.

2) It should be easy to run the fuzzers over existing corpus. It looks like you have something like "make tests" to run the tests, the same approach is needed to run the fuzzers. Basically, the following command should not crash: `./fuzzer -runs=0 EXISTING_CORPUS_PATH`.

3) More fuzz targets. You are in a good position to easily write more, as there are plenty of [boringssl](https://github.com/google/oss-fuzz/tree/master/projects/boringssl), [openssl](https://github.com/google/oss-fuzz/tree/master/projects/openssl), and [nss](https://github.com/google/oss-fuzz/tree/master/projects/nss) targets for other crypto libraries. You can use them for inspiration :)

**Comment by kcc** [comment]
The cornerstone of "ideal" integration as we see it, is that the fuzz targets have owner-maintained corpora with good coverage that are used by the project's continuous testing infrastructure (e.g. as part of `make test` or some such). 

Note that your project's testing does not have to depend on Clang or libFuzzer -- all you need is to link the fuzz targets with something like [StandaloneFuzzTargetMain.c](https://github.com/llvm-mirror/llvm/blob/master/lib/Fuzzer/standalone/StandaloneFuzzTargetMain.c) and feed the corpus elements to it. We however, strongly recommend using ASan, UBSan, and (where possible) MSan in your regular testing. 

Having the fuzz targets and the corpora in the same git as the main code is not a hard requirement, but in many cases this is just the most natural way.

**Comment by levi-wolfssl** [comment]
We decided to to put the fuzz targets into their own repository because we were thinking of them as auxiliary to wolfSSL rather than part of the proper test suite. This is in part due to my own recommendations: I'd not known that we could write anything like that standalone and thought that building the fuzzers would require use of Clang and libFuzzer.

I'll start kicking the idea around the wolfSSL team about if/how we want to integrate the fuzz targets into our usual tests.

**Comment by kcc** [comment]
If you want examples from other crypto folks, here they are: 
https://github.com/openssl/openssl/tree/master/fuzz
https://github.com/google/boringssl/tree/master/fuzz
https://gitlab.com/gnutls/gnutls/tree/master/devel/fuzz
https://github.com/randombit/botan/tree/master/src/extra_tests/fuzzers/jigs
https://github.com/nss-dev/nss/tree/master/fuzz
