### ISSUE TITLE
Could you close fixed tickets ?

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#760]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1583 has been fixed since many weeks (see Statistics in https://oss-fuzz.com/v2/testcase-detail/5709498763182080?noredirect=1 ) and it is still not closed. Same for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2214 (see stats https://oss-fuzz.com/v2/testcase-detail/5798052881235968?noredirect=1)
Could you manually close them (since I can't find how to do that myself) ? Thanks

**Comment by oliverchang** [comment]
I've manually closed them. Thanks for pointing them out.

The first bug not being closed was caused by a race condition that should now be fixed.

The second, I'm not too sure, but we lost the bug association somehow. Unfortunately at this point it's hard to guess what happened since this was 2 months ago.

Closing this bug for now, but please let us know if this happens again!
