### ISSUE TITLE
Optional argument "source_path" ignored by build_fuzzers

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#7634]
The help text shown when calling
`python infra/helper.py build_fuzzers`
without further arguments reads that an optional argument "source_path" can be passed. Some months ago, this used to build sources from that path instead of those in the Dockerfile.

When I try it now, this argument seems to be ignored and the fuzzers are always being build from the Dockerfile. Am I missing something? It looks to me like either build_fuzzers has a bug or the help text is outdated.

**Comment by DavidKorczynski** [comment]
Is this related to the qt project? I think it might be because of this commit: https://github.com/google/oss-fuzz/commit/a0b3dc9895946d396f4a5f92b4cdf2d8dfe25430 where the project being cloned switched name from `qt` to `qt5`.

The code for `source_path` is a bit hacky in that it relies on matching lines in the Dockerfile with project names, see e.g.:
https://github.com/google/oss-fuzz/blob/5a889cfdf53e797d24798ac39cf88a50d8cbd9fe/infra/helper.py#L507-L528

Do you by any chance run into this logging error https://github.com/google/oss-fuzz/blob/5a889cfdf53e797d24798ac39cf88a50d8cbd9fe/infra/helper.py#L664 ?

**Comment by DavidKorczynski** [comment]
Is this related to the qt project? I think it might be because of this commit: https://github.com/google/oss-fuzz/commit/a0b3dc9895946d396f4a5f92b4cdf2d8dfe25430 where the project was switched from `qt` to `qt5` in the docker container.

The code for `source_path` is a bit hacky in that it relies on matching lines in the Dockerfile with project names, see e.g.:
https://github.com/google/oss-fuzz/blob/5a889cfdf53e797d24798ac39cf88a50d8cbd9fe/infra/helper.py#L507-L528

Do you by any chance run into this logging error https://github.com/google/oss-fuzz/blob/5a889cfdf53e797d24798ac39cf88a50d8cbd9fe/infra/helper.py#L664 ?
