### ISSUE TITLE
[osquery] Fixed issue closure keeps getting delayed because it cannot be reliably reproduced

### ISSUE THREAD

**Issue by Smjert** [google/oss-fuzz#8033]
We have the following issue found by oss-fuzz https://oss-fuzz.com/testcase-detail/5754205078028288 that should've been solved by not making available the `hash` table in osquery, thanks to work done here: https://github.com/osquery/osquery/pull/7419
I've also re-confirmed that the `hash` table is not available to query for the `osqueryfuzz-sqlquery` binary.

Not only that, but recently we have removed a part of the code that still shows in the stack trace presented in the issue, so it's impossible for that stack trace to be still valid (removed here https://github.com/osquery/osquery/pull/7525)

I already tried to use (once) the REDO TASK button to force it to run on newer osquery commits, that definitely don't have that code path anymore, but it seems like it keeps delaying the closure because it cannot reliably reproduce the original testcase (at the original commit I suppose); though it was my understanding/guess that the sentence `Will be auto-closed on <date> if flaky crash no longer seen` meant that if the crash was not seen anymore on **current** commits, then the issue would've been auto-closed.
So I'm not sure what's happening, because it should've been closed months ago.

**Comment by jonathanmetzman** [comment]
Assigning to current sherriff.

**Comment by oliverchang** [comment]
This is because we don't have an effective way to deduplicate Timeout bugs. If we scroll down to crash stats on the details page we can see that Timeouts are still occurring in the same target. 

We have a deadlock here where -- the original timeout is flaky/no longer reproducible. Our logic here is to keep this bug open if there are other "same" crashes in the crash stats. At the same time, we only ever open one "Timeout" bug at any given time, which is this one. 

I'll open an issue on https://github.com/google/clusterfuzz to track this. In the meantime, we've manually closed the bug you pointed out. Thanks for filing this issue!
