### ISSUE TITLE
Update clang

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8059]
Theres a few different reasons why we should update clang
- discrepancies between what is used in the rest of Google and OSS-Fuzz
- needing a newer version of clang for centipede

We're currently on clang-14.
@vanhauser-thc Do you know if we can upgrade to 15 with AFL++ (sorry for asking this again, can't remember your answer)

**Comment by vanhauser-thc** [comment]
yes you can upgrade. Our LTO instrumentation doesnt work on llvm 15 as they removed the ability to load own plugins in lld, but LTO is not used (and doesn't make sense to be used) in clusterfuzz.
however they might always change something in llvm 15-dev that breaks external plugins like ours.
But native clang-15 already broke a few configure scripts for things I wanted to compile normally :)

**Comment by evverx** [comment]
> We're currently on clang-14.

@jonathanmetzman as far as I can see https://github.com/llvm/llvm-project/commit/bc56097817bec3446edd9f06e2d78eab95033027 hasn't been included in the base-builder yet so it seems clang is pinned somewhere between clang-13 and clang-14 on OSS-Fuzz. I wonder if it would be possible to bump it to 14? I saw https://github.com/google/oss-fuzz/pull/8108 but looks like it might take a while.

**Comment by jonathanmetzman** [comment]
We are currently on clang 14 aee49255074fd4ef38d97e6e70cbfbf2f9fd0fa7

**Comment by jonathanmetzman** [comment]
I don't think it should take longer than a week or two to update to clang 15 so I don't think we will do anything temporary in the meantime

**Comment by evverx** [comment]
That commit is older than https://github.com/llvm/llvm-project/commit/bc56097817bec3446edd9f06e2d78eab95033027. The problem is that distributions ship clang-14 with both those commits included and there it's kind of safe to assume that `-fno-semantic-interposition` doesn't work with `-fuzzer-no-link` with `clang < 14`. On OSS-Fuzz that assumption isn't correct so it should be handled differently. More generally it would be great if OSS-Fuzz pinned clang to tags pointing to releases instead of release candidates.

> I don't think we will do anything temporary in the meantime

Fair enough.
