### ISSUE TITLE
libpng contact info out of date

### ISSUE THREAD

**Issue by tysmith** [google/oss-fuzz#8380]
In the libpng `project.yml` the following fields require review:

```
primary_contact: "glennrp@gmail.com"
main_repo: 'https://github.com/glennrp/libpng.git'
homepage: "http://www.libpng.org/pub/png/libpng.html"
```

@ctruta are these correct?

Also the current maintainer (@ctruta) is not cc'ed on the issues.

**Comment by oliverchang** [comment]
Please feel free to propose a PR to fix this. Thanks!

**Comment by thealberto** [comment]
A gentle reminder @ctruta @jbowler

**Comment by ctruta** [comment]
@tysmith @thealberto FYI, in a few days, I will publicly announce the new canonical location of the libpng repo:
https://github.com/pnggroup/libpng.git

In that public announcement, I will also let everybody know that I will archive glennrp/libpng. I won't do it immediately because I'd rather close as many issues as possible, but it will happen eventually.

Feel free to use my personal email address `ctruta@gmail.com` for the primary contact.

**Comment by jbowler** [comment]
I didn't even know about that new repo...

**Comment by jbowler** [comment]
Incidentally I don't think it can be _just_ archived.  I still have the canonical repo as git:://git.code.sf.net/p/libpng/code; I assume that is what should be used by distros, however glennrp is forked by many people and it will take them a long time to update the fork (years) unless there is some way of doing it under their feet, e.g. via something like a symlink?

**Comment by tysmith** [comment]
@jbowler can you please provide me with a contact email to use with oss-fuzz?

**Comment by jbowler** [comment]
jbowler@acm.org

**Comment by tysmith** [comment]
Thanks! :)

Also @jbowler @ctruta whch address should be listed as primary contact?

**Comment by jbowler** [comment]
Not me :-)  I'm not actually on any of the libpng mailing lists (I think) or at least I just file messages sent to them.
