### ISSUE TITLE
a way to shift the blame/responsibility for an issue

### ISSUE THREAD

**Issue by dtardon** [google/oss-fuzz#896]
The fuzzers occasionally find a problem in a library one's project uses. E.g., for dlplibs, there have been https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1021 (libxml2) or https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2894 (Boost.Spirit). I fixed both of these myself, because they were rather simple cases, but I don't think this works well in general. Also, the fixes won't become visible immediately, unless one also starts pulling from the library's upstream's repository. It would be great to have a way to shift the blame to the respective project, if it's already present on oss-fuzz; or, as a minimum, to be able to say "this issue is out of my hands". And the release-to-public deadline should not be used in this case, at least for Bug-Security issues.

**Comment by kcc** [comment]
That's a very good point, and you are not the only one who has such problems (@rouault deals with other projects regularly). 

Unfortunately, it's not easy if the project where the bug is found does not participate in OSS-Fuzz. 
In your example: 
* libxml2: we have it here, but the upstream doesn't really support it. 
* Boost.Spirit: we've just started fuzzing some other part of boost (regex) and so far we don't see any involvement from the boost community. 

Today, I don't see a one-size-fits-all solution for these situations -- we'll have to resolve them case by case.
