### ISSUE TITLE
miniz_oxide: coverage build failure

### ISSUE THREAD

**Issue by manunio** [google/oss-fuzz#8993]
Hi, I'm getting coverage build failure for miniz_oxide. No changes were made at upstream or here, since its integration.

Issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52660
Build Log: https://oss-fuzz-build-logs.storage.googleapis.com/log-91c22854-e01b-45db-91d5-cf4c7b2d92a0.txt

```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: Running inflate_nonwrapping
Step #5: du: cannot access '/workspace/out/libfuzzer-coverage-x86_64/dumps/inflate_nonwrapping.*.profraw': No such file or directory
Step #5: error: /workspace/out/libfuzzer-coverage-x86_64/dumps/*.profdata: No such file or directory
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image miniz_oxide
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage miniz_oxide
Step #5: python infra/helper.py coverage miniz_oxide
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1
```

**Comment by oliverchang** [comment]
Hi! According to https://oss-fuzz-build-logs.storage.googleapis.com/index.html, the coverage build was never successful.

I think the issue is here:

https://github.com/google/oss-fuzz/blob/42b53f467346c6016a1c1c5a434a64c00a2ef199/projects/miniz_oxide/build.sh#L19

Our RUSTFLAGS (which includes the coverage instrumentation flags) is getting overwritten. I'll create a PR to fix this.
