### ISSUE TITLE
Fuzz Chakra, SpiderMonkey, JavascriptCore

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#925]
Not with libFuzzer, but with our custom JS fuzzing engine and minimizer.

**Comment by djn3m0** [comment]
Is "JS fuzzing engine" is public/open source?

**Comment by oliverchang** [comment]
> Is "JS fuzzing engine" is public/open source?

Unfortunately not at this point.

**Comment by alex** [comment]
Is there anything y'all need in terms of setting up SpiderMonkey? I see you already got Chakra done.

**Comment by inferno-chromium** [comment]
@alex, @choller - i see several other build arguments used in https://bugzilla.mozilla.org/show_bug.cgi?id=1415571 like --enable-posix-nspr-emulation --enable-valgrind --enable-gczeal --disable-tests --enable-stdcxx-compat --disable-profiling --enable-debug --enable-optimize, run with --fuzzing-safe --cpu-count=2 --disable-oom-functions - Should these be added to spidermonkey build

**Comment by choller** [comment]
Many of those build arguments are probably not needed for your build (some like posix-nspr etc. are required for standalone builds, but I believe you do a full build?). One important build flag is `--enable-gczeal` which enables the `gczeal()` function that helps finding many garbage collector problems. However, if you build with `--enable-debug`, then it is enabled by default. I'm not sure if `--enable-optimize` is the default, but I believe it is nowadays. I guess your builds have both debug and opt enabled?

If so, that should suffice for the build flags, but there are several interesting runtime flags that you should consider adding randomly, like:

- `--ion-eager`
- `--baseline-eager`
- `--ion-offthread-compile=off`
- `--ion-extra-checks`
- `--ion-aa=flow-sensitive`

The last option is an example for a feature that we haven't enabled yet anywhere except in the JS shell because we want to fuzz it before making the feature available to content.

Also if you run multiple JS engines on a single machine, use `--cpu-count=2` to limit the amount of threads used by the engine.

**Comment by inferno-chromium** [comment]
Thanks @choller.

Just added --enable-optimize explicitly in https://github.com/google/oss-fuzz/commit/fdd0cff32a7bf678fc6a69e929def6ae9787c220

Also, added --cpu-count=2 to current app args. We will now pass --cpu-count=2 --disable-oom-functions --fuzzing-safe

Regarding the random runtime flags, thanks for the list. Will let @oliverchang decide how to pull those in. @oliverchang - i think we should support this in job definition rather than hardcoding in fuzzer, that way we can easily add stuff, something like RANDOM_APP_ARGS ?

**Comment by inferno-chromium** [comment]
@oliverchang - or i remember Marty had some way to run APP args trial (he did it for v8) - @mbarbella

**Comment by oliverchang** [comment]
Adding Trial entities SGTM. Thanks!

**Comment by oliverchang** [comment]
Ok, I've added Trial entities for each of the arguments in https://github.com/google/oss-fuzz/issues/925#issuecomment-342858750. 

@choller Is it safe (or good) to use any combination of these flags together, or are there specific combinations that make more sense?

**Comment by choller** [comment]
@oliverchang Yes, these options can (and are meant) to be combined.
