### ISSUE TITLE
Python projects fail to generate coverage summary.json

### ISSUE THREAD

**Issue by Navidem** [google/oss-fuzz#9441]
These projects correctly have coverage index.html generated, but the summary.json is empty.

https://oss-fuzz-coverage.storage.googleapis.com/python-rsa/reports/20230103/linux/index.html 
https://oss-fuzz-coverage.storage.googleapis.com/python-rsa/reports/20230103/linux/summary.json 

https://oss-fuzz-coverage.storage.googleapis.com/gunicorn/reports/20230103/linux/index.html
https://oss-fuzz-coverage.storage.googleapis.com/gunicorn/reports/20230103/linux/summary.json

**Comment by Navidem** [comment]
@DavidKorczynski should this line be copying into `summary.json` instead?
https://github.com/google/oss-fuzz/blob/63e38959bf4efe8f49f855f53069bbddcf0cee0f/infra/base-images/base-runner/coverage#L339

**Comment by DavidKorczynski** [comment]
The `summary.json` file is llvm-specific, see e.g. https://github.com/google/oss-fuzz/blob/7efd35c1f23e804e4f707eb0b51c9498c810daa3/infra/base-images/base-runner/coverage#L240

What are we looking for here? jvm has a converter: jacoco_report_converter.py which is used for converting jacoco output to llvm-like json (I assume, didn't verify). Do we need something similar for Python?

One problem is that the python coverage is a bit tricky in format, due to the use of `pyinstaller` for wrapping Python programs. 

`html_status.json` is used by Fuzz Introspector here: https://github.com/ossf/fuzz-introspector/blob/54584d2846119b6aead7731e7ce49b8115b979fd/src/fuzz_introspector/utils.py#L293 so the name is correct in that sense. Note that Fuzz Introspector has a bunch of logic for translating the generated .json files into paths that resemble the real paths more closely (as opposed to the paths as they are shown in the pyinstaller `.pkg`).

**Comment by Navidem** [comment]
This `summary.json` has usages outside FuzzIntrospector.

> jvm has a converter: [jacoco_report_converter.py](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/jacoco_report_converter.py) which is used for converting jacoco output to llvm-like json (I assume, didn't verify). Do we need something similar for Python?

I assume so. We need similar code to post-process python coverage into `summary.json` with a llvm-like structure [like this](https://oss-fuzz-coverage.storage.googleapis.com/grpc-go/reports/20230103/linux/summary.json).

> One problem is that the python coverage is a bit tricky in format, due to the use of pyinstaller for wrapping Python programs.

AFIK, line coverage is the most important part of that summary.

**Comment by Navidem** [comment]
> AFIK, line coverage is the most important part of that summary.

@ anurag06 WDYT?

**Comment by anurag06** [comment]
> > AFIK, line coverage is the most important part of that summary.
> 
> @anurag06 WDYT?

I agree that total line coverage is important as its the very first metric someone will look at to ascertain quality of coverage.

**Comment by Navidem** [comment]
> We need similar code to post-process python coverage into summary.json with a llvm-like structure

@DavidKorczynski could you please add this to python coverage and make sure the line coverage summary is getting emitted into `summary.json`?

```
{
"coverage_data": [
   ...
       "lines":{
          "count":35673,
          "covered":23843,
          "notcovered":11830,
          "percent":66.83766433997701
        }
   ...
   ]
}

**Comment by DavidKorczynski** [comment]
Yep, I got this on my list now. Is this high priority time-wise?

**Comment by Navidem** [comment]
> Yep, I got this on my list now. Is this high priority time-wise?

Thanks, it would be nice to have it by next week.

**Comment by anurag06** [comment]
Hi @DavidKorczynski

Any update on this?

**Comment by DavidKorczynski** [comment]
I'll try to do this today or tomorrow @anurag06

**Comment by DavidKorczynski** [comment]
I started this now and it looks like we should already have most of it!

This line https://github.com/google/oss-fuzz/blob/36e0de348cf29b73b628f807eec027f17d085e99/infra/base-images/base-runner/coverage#L336

outputs coverage data from the project to a json format. The `all_cov.json` includes elements such as a the snippet pasted below from running coverage of the `idna`(https://github.com/kjd/idna) project:
```
"/pythoncovmergedfiles/medio/medio/usr/local/lib/python3.8/site-packages/idna/idnadata.py":
    "executed_lines": [
        3,
        4,
        102,
        932
    ],
    "summary": {
        "covered_lines": 4,
        "num_statements": 4,
        "percent_covered": 100.0,
        "percent_covered_display": "100",
        "missing_lines": 0,
        "excluded_lines": 0
    },
    "missing_lines": [],
    "excluded_lines": []
},
"/pythoncovmergedfiles/medio/medio/usr/local/lib/python3.8/site-packages/idna/intranges.py": {
    "executed_lines": [
        1,
        8,
        9,
        11,
        32,
        33,
        35,
        36,
        39,
        41,
        42,
        45,
        46,
        47,
        48,
        50,
        51,
        52,
        53,
        54
    ],
    "summary": {
        "covered_lines": 19,
        "num_statements": 30,
        "percent_covered": 63.333333333333336,
        "percent_covered_display": "63",
        "missing_lines": 11,
        "excluded_lines": 0
    },
    "missing_lines": [
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        30
    ],
    "excluded_lines": []
},
```
I can fix it up Wednesday UK time so the data is in a similar format to the existing `summary.json` formats.

@anurag06 notice the paths are a bit special. This is due to the use of `pyinstaller` and the way python fuzzers are packaged in OSS-Fuzz. For example, in the above element the path
`/pythoncovmergedfiles/medio/medio/usr/local/lib/python3.8/site-packages/idna/intranges.py` refers to https://github.com/kjd/idna/blob/master/idna/intranges.py -- i.e. `idna/intranges.py` is the actual path within the idna source code. What's your prefernce here @anurag06 ? In `summary.json` would you like the path to be:
1) `/pythoncovmergedfiles/medio/medio/usr/local/lib/python3.8/site-packages/idna/intranges.py`
2) `/usr/local/lib/python3.8/site-packages/idna/intranges.py`
3) `idna/intranges.py`
4) `intranges.py`

(1) and (2) above are easy and reliable from my side. (3) and (4) can probably be achieved in the vast majority of cases but I can see sometimes it may not be possible to remove the prefixing.

**Comment by DavidKorczynski** [comment]
@anurag06 -- Have you had any thoughts on the above? Which path would you prefer to have of the four listed?

**Comment by anurag06** [comment]
Ideally option (3) will be preferred since it gives the path with respect to root of source code. 

However, if its not possible to do it in all the cases, (2) should also be fine to start with. We can do simpler one to start with and then enhance later if required.

For my understanding, when we go with 2, are there different prefixes possible? Any patterns to them?

**Comment by DavidKorczynski** [comment]
Made a pull request https://github.com/google/oss-fuzz/pull/9650 @anurag06 we can continue discussions there

**Comment by DavidKorczynski** [comment]
@anurag06 the change has now been deployed.

See for example `pyyaml`:
- json report: https://storage.googleapis.com/oss-fuzz-coverage/pyyaml/reports/20230215/linux/summary.json
- html report: https://storage.googleapis.com/oss-fuzz-coverage/pyyaml/reports/20230215/linux/index.html
