### ISSUE TITLE
Add FuzzIntrospector documentation to index

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#9444]
We should link FuzzIntrospector documentation to https://oss-fuzz-introspector.storage.googleapis.com/index.html

@DavidKorczynski @AdamKorcz let us know when the user documentation you've been working on is ready.

**Comment by DavidKorczynski** [comment]
> https://oss-fuzz-introspector.storage.googleapis.com/index.html

The links is: https://fuzz-introspector.readthedocs.io/en/latest/index.html

I'd say it's ready to linked to at this moment. It will continue to evolve in the coming days, but is already providing value for a users.

I also think we should update the OSS-Fuzz docs not only with links to Fuzz Introspector but additional updates since https://github.com/google/oss-fuzz/pull/9243 was added. Maybe just make a copy of the content from here: https://fuzz-introspector.readthedocs.io/en/latest/oss-fuzz/index.html

**Comment by jonathanmetzman** [comment]
@DavidKorczynski Would you please be able to do this? I'm not sure who else from our side can at this point.
