### ISSUE TITLE
Timeout bug only reports initial example, not a contemporary one

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#960]
I mean, in this frequent, but unreproducible bug, https://oss-fuzz.com/v2/testcase-detail/4955193562103808 the original stacktrace and an original unminimized testcase are available.

On the 9th October this commit landed
https://cgit.freedesktop.org/libreoffice/core/commit/?id=5fcfa368d8a4aa3156674fe38365f57218a6952e
and the stats in oss-fuzz shows a drop from ~20 to around ~1 timeouts per day on the 10th Oct. But the numbers then grow again.

It would be nice to get the timeout reports updated with contemporary examples and backtraces.

**Comment by inferno-chromium** [comment]
We get the stacktrace from tip-of-tree trunk in "Last tested stacktrace" section for Reproducible crashes only (e.g. see 2nd stacktrace in https://oss-fuzz.com/v2/testcase-detail/5533260961546240). This one is marked unreproducible/flaky, so we don't run the cron to update last tested stacktrace for unreproducible crashes. You can try clicking the icon next to "CRASH STACKTRACE" to update last tested stacktrace, but i suspect it will fail since it will first try to reproduce in original revision, then it wont reproduce, so it will bail out.
