### ISSUE TITLE
Add Git repo URL to build logs

### ISSUE THREAD

**Issue by raghavkaul** [google/oss-fuzz#9782]
OSS-Fuzz stores build logs here: https://oss-fuzz-build-logs.storage.googleapis.com/status.json. This output contains the repo name, but not the Repo URL.

In Scorecard, we [check](https://github.com/ossf/scorecard/blob/48813a3c380172e45e7b6410aec5a6be60acf0cc/checks/raw/fuzzing.go#L169) for a git repo's project.yaml in the OSS-Fuzz repo, but it would be more reliable if we read structured logs instead of GitHub's Search API.

Adding the Repo URL to the data structure would allow Scorecard to tell whether a specific GitHub project was fuzzed, and how recently.

**Comment by evverx** [comment]
> Adding the Repo URL to the data structure would allow Scorecard to tell whether a specific GitHub project was fuzzed, and how recently.

Repository urls aren't reliable because of possible redirects: https://github.com/ossf/scorecard/pull/1241#issuecomment-966528907.

By the way it's good to know that scorecard appears to have started fixing its false positives. It should hopefully fix that issue where projects that aren't actually fuzzed (like scorecard itself in https://github.com/ossf/scorecard/pull/1816#issuecomment-1101894399 last year) receive high "fuzzing" scores nonetheless.

**Comment by oliverchang** [comment]
> > Adding the Repo URL to the data structure would allow Scorecard to tell whether a specific GitHub project was fuzzed, and how recently.
> 
> Repository urls aren't reliable because of possible redirects: [ossf/scorecard#1241 (comment)](https://github.com/ossf/scorecard/pull/1241#issuecomment-966528907).

What else is there available in these cases?

**Comment by evverx** [comment]
> What else is there available in these cases?

I don't think there is anything apart from `main_repo`. The problem is that `main_repo` isn't always up to date so either `main_repo` or whatever it redirects to should be taken into account. On GitHub repositories like that can be detected via the API because their `full_name`s are different and for example `libra/libra` redirects to `diem/diem`. It doesn't work outside of GitHub though but I don't think `scorecard` covers anything other than GitHub at the moment.
