### ISSUE TITLE
I'd like to access some binutils testcases

### ISSUE THREAD

**Issue by hjl-tools** [google/oss-fuzz#9940]
I'd like to access the following testcases:

https://oss-fuzz.com/testcase-detail/5870018505342976
https://oss-fuzz.com/testcase-detail/4651718416924672
https://oss-fuzz.com/testcase-detail/5452642448179200

to investigate segfaults in GNU binutils.

**Comment by DavidKorczynski** [comment]
Hi, the testcases are only available for maintainers of the project.

@jonathanmetzman @oliverchang @Alan32Liu -- the issues above should not be public as far as I can tell, a common feature of the issues is they are found by Centipede. Am I missing something here? Looking at the monorail relevant part https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57127 does not have the usual "This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public." disclosure text too and the sheriffbot is missing from the comments.

**Comment by oliverchang** [comment]
Closing as the access issues have been resolved.
